(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite5 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite6 - satellite
	instrument15 - instrument
	satellite7 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite8 - satellite
	instrument19 - instrument
	instrument20 - instrument
	satellite9 - satellite
	instrument21 - instrument
	instrument22 - instrument
	thermograph1 - mode
	thermograph3 - mode
	image2 - mode
	spectrograph0 - mode
	Star6 - direction
	Star11 - direction
	Star5 - direction
	Star0 - direction
	GroundStation2 - direction
	GroundStation9 - direction
	Star3 - direction
	GroundStation10 - direction
	Star7 - direction
	Star4 - direction
	GroundStation8 - direction
	Star1 - direction
	Star12 - direction
	Phenomenon13 - direction
	Planet14 - direction
	Planet15 - direction
	Planet16 - direction
)
(:init
	(supports instrument0 image2)
	(calibration_target instrument0 Star7)
	(calibration_target instrument0 GroundStation8)
	(calibration_target instrument0 GroundStation9)
	(calibration_target instrument0 Star11)
	(supports instrument1 spectrograph0)
	(supports instrument1 thermograph1)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 Star5)
	(calibration_target instrument1 GroundStation9)
	(calibration_target instrument1 GroundStation10)
	(supports instrument2 image2)
	(supports instrument2 thermograph1)
	(calibration_target instrument2 Star4)
	(calibration_target instrument2 Star7)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star0)
	(supports instrument3 spectrograph0)
	(supports instrument3 thermograph1)
	(calibration_target instrument3 Star5)
	(calibration_target instrument3 Star4)
	(supports instrument4 thermograph3)
	(calibration_target instrument4 Star4)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet15)
	(supports instrument5 thermograph1)
	(supports instrument5 image2)
	(calibration_target instrument5 Star6)
	(calibration_target instrument5 Star4)
	(calibration_target instrument5 Star7)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star7)
	(supports instrument6 thermograph3)
	(supports instrument6 spectrograph0)
	(supports instrument6 image2)
	(calibration_target instrument6 Star6)
	(calibration_target instrument6 Star7)
	(supports instrument7 thermograph1)
	(calibration_target instrument7 Star7)
	(calibration_target instrument7 Star11)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 GroundStation8)
	(supports instrument8 spectrograph0)
	(supports instrument8 thermograph1)
	(supports instrument8 image2)
	(calibration_target instrument8 GroundStation2)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 Star4)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star6)
	(supports instrument9 thermograph3)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 Star5)
	(calibration_target instrument9 Star1)
	(calibration_target instrument9 Star3)
	(supports instrument10 thermograph3)
	(supports instrument10 image2)
	(supports instrument10 spectrograph0)
	(calibration_target instrument10 Star5)
	(supports instrument11 spectrograph0)
	(supports instrument11 image2)
	(calibration_target instrument11 Star1)
	(calibration_target instrument11 Star4)
	(calibration_target instrument11 GroundStation8)
	(calibration_target instrument11 Star6)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet14)
	(supports instrument12 thermograph3)
	(calibration_target instrument12 Star11)
	(calibration_target instrument12 GroundStation9)
	(supports instrument13 thermograph1)
	(calibration_target instrument13 Star7)
	(supports instrument14 thermograph3)
	(supports instrument14 image2)
	(supports instrument14 thermograph1)
	(calibration_target instrument14 GroundStation9)
	(calibration_target instrument14 GroundStation10)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet16)
	(supports instrument15 thermograph3)
	(calibration_target instrument15 GroundStation8)
	(calibration_target instrument15 Star5)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 Star7)
	(on_board instrument15 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star6)
	(supports instrument16 image2)
	(supports instrument16 thermograph1)
	(calibration_target instrument16 Star4)
	(calibration_target instrument16 GroundStation2)
	(supports instrument17 thermograph3)
	(calibration_target instrument17 Star0)
	(supports instrument18 thermograph1)
	(calibration_target instrument18 GroundStation8)
	(calibration_target instrument18 GroundStation2)
	(on_board instrument16 satellite7)
	(on_board instrument17 satellite7)
	(on_board instrument18 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet16)
	(supports instrument19 thermograph3)
	(supports instrument19 thermograph1)
	(calibration_target instrument19 GroundStation8)
	(calibration_target instrument19 GroundStation9)
	(supports instrument20 thermograph3)
	(supports instrument20 spectrograph0)
	(supports instrument20 image2)
	(calibration_target instrument20 Star4)
	(calibration_target instrument20 Star7)
	(calibration_target instrument20 GroundStation10)
	(calibration_target instrument20 Star3)
	(on_board instrument19 satellite8)
	(on_board instrument20 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation10)
	(supports instrument21 thermograph3)
	(supports instrument21 thermograph1)
	(supports instrument21 image2)
	(calibration_target instrument21 Star1)
	(calibration_target instrument21 GroundStation8)
	(supports instrument22 thermograph1)
	(supports instrument22 image2)
	(calibration_target instrument22 Star1)
	(on_board instrument21 satellite9)
	(on_board instrument22 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star11)
)
(:goal (and
	(pointing satellite0 Planet16)
	(pointing satellite2 GroundStation9)
	(pointing satellite3 Star4)
	(pointing satellite6 GroundStation8)
	(pointing satellite8 GroundStation2)
	(have_image Star12 image2)
	(have_image Phenomenon13 thermograph3)
	(have_image Planet14 spectrograph0)
	(have_image Planet15 image2)
	(have_image Planet16 thermograph1)
))

)
