(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite6 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite7 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite8 - satellite
	instrument19 - instrument
	instrument20 - instrument
	satellite9 - satellite
	instrument21 - instrument
	instrument22 - instrument
	thermograph1 - mode
	spectrograph0 - mode
	spectrograph2 - mode
	thermograph3 - mode
	GroundStation3 - direction
	GroundStation5 - direction
	GroundStation2 - direction
	GroundStation1 - direction
	GroundStation4 - direction
	Star7 - direction
	GroundStation6 - direction
	Star0 - direction
	Star8 - direction
	Phenomenon9 - direction
	Planet10 - direction
	Planet11 - direction
	Star12 - direction
)
(:init
	(supports instrument0 thermograph3)
	(supports instrument0 spectrograph2)
	(calibration_target instrument0 GroundStation4)
	(supports instrument1 spectrograph0)
	(supports instrument1 thermograph1)
	(supports instrument1 spectrograph2)
	(calibration_target instrument1 GroundStation1)
	(supports instrument2 thermograph1)
	(supports instrument2 thermograph3)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 GroundStation4)
	(calibration_target instrument2 GroundStation5)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation6)
	(supports instrument3 spectrograph2)
	(supports instrument3 thermograph3)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 GroundStation5)
	(calibration_target instrument3 GroundStation1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation4)
	(supports instrument4 thermograph3)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 GroundStation6)
	(supports instrument5 spectrograph2)
	(supports instrument5 thermograph3)
	(supports instrument5 thermograph1)
	(calibration_target instrument5 Star7)
	(calibration_target instrument5 GroundStation1)
	(supports instrument6 thermograph1)
	(supports instrument6 thermograph3)
	(supports instrument6 spectrograph2)
	(calibration_target instrument6 GroundStation2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet10)
	(supports instrument7 spectrograph2)
	(supports instrument7 thermograph3)
	(supports instrument7 thermograph1)
	(calibration_target instrument7 Star7)
	(calibration_target instrument7 GroundStation1)
	(supports instrument8 thermograph1)
	(supports instrument8 spectrograph2)
	(calibration_target instrument8 GroundStation1)
	(calibration_target instrument8 GroundStation5)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 GroundStation2)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star12)
	(supports instrument10 spectrograph0)
	(supports instrument10 thermograph3)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 GroundStation5)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star0)
	(supports instrument11 thermograph3)
	(supports instrument11 spectrograph0)
	(supports instrument11 spectrograph2)
	(calibration_target instrument11 GroundStation2)
	(calibration_target instrument11 GroundStation1)
	(supports instrument12 thermograph1)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star7)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star7)
	(supports instrument13 spectrograph0)
	(supports instrument13 spectrograph2)
	(supports instrument13 thermograph3)
	(calibration_target instrument13 GroundStation4)
	(calibration_target instrument13 GroundStation5)
	(supports instrument14 thermograph1)
	(calibration_target instrument14 Star0)
	(calibration_target instrument14 GroundStation3)
	(supports instrument15 spectrograph0)
	(supports instrument15 thermograph1)
	(calibration_target instrument15 GroundStation6)
	(on_board instrument13 satellite6)
	(on_board instrument14 satellite6)
	(on_board instrument15 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet11)
	(supports instrument16 thermograph3)
	(supports instrument16 spectrograph0)
	(calibration_target instrument16 GroundStation5)
	(calibration_target instrument16 Star7)
	(supports instrument17 spectrograph2)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 GroundStation2)
	(calibration_target instrument17 GroundStation4)
	(supports instrument18 spectrograph2)
	(supports instrument18 spectrograph0)
	(supports instrument18 thermograph1)
	(calibration_target instrument18 GroundStation1)
	(calibration_target instrument18 GroundStation6)
	(on_board instrument16 satellite7)
	(on_board instrument17 satellite7)
	(on_board instrument18 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation2)
	(supports instrument19 spectrograph2)
	(supports instrument19 thermograph3)
	(supports instrument19 thermograph1)
	(calibration_target instrument19 GroundStation6)
	(supports instrument20 spectrograph2)
	(supports instrument20 spectrograph0)
	(supports instrument20 thermograph1)
	(calibration_target instrument20 GroundStation4)
	(calibration_target instrument20 GroundStation1)
	(on_board instrument19 satellite8)
	(on_board instrument20 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet10)
	(supports instrument21 spectrograph0)
	(calibration_target instrument21 Star7)
	(calibration_target instrument21 GroundStation6)
	(supports instrument22 spectrograph2)
	(supports instrument22 thermograph3)
	(supports instrument22 thermograph1)
	(calibration_target instrument22 Star0)
	(calibration_target instrument22 GroundStation6)
	(on_board instrument21 satellite9)
	(on_board instrument22 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star12)
)
(:goal (and
	(pointing satellite0 GroundStation6)
	(pointing satellite3 GroundStation1)
	(pointing satellite6 Star8)
	(pointing satellite7 Star0)
	(have_image Star8 thermograph1)
	(have_image Phenomenon9 spectrograph2)
	(have_image Planet10 thermograph1)
	(have_image Planet11 spectrograph2)
	(have_image Star12 thermograph1)
))

)
