(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	instrument11 - instrument
	satellite5 - satellite
	instrument12 - instrument
	instrument13 - instrument
	satellite6 - satellite
	instrument14 - instrument
	instrument15 - instrument
	thermograph0 - mode
	spectrograph1 - mode
	Star8 - direction
	Star3 - direction
	Star10 - direction
	Star6 - direction
	GroundStation0 - direction
	GroundStation11 - direction
	Star5 - direction
	GroundStation7 - direction
	GroundStation1 - direction
	GroundStation2 - direction
	Star4 - direction
	Star9 - direction
	GroundStation12 - direction
	Planet13 - direction
	Star14 - direction
	Phenomenon15 - direction
	Planet16 - direction
	Planet17 - direction
	Planet18 - direction
	Planet19 - direction
)
(:init
	(supports instrument0 thermograph0)
	(calibration_target instrument0 GroundStation11)
	(calibration_target instrument0 Star8)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 Star6)
	(supports instrument1 spectrograph1)
	(supports instrument1 thermograph0)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 Star4)
	(calibration_target instrument1 GroundStation1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation2)
	(supports instrument2 spectrograph1)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 Star9)
	(supports instrument3 spectrograph1)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 GroundStation11)
	(calibration_target instrument3 Star8)
	(calibration_target instrument3 Star4)
	(supports instrument4 thermograph0)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 Star10)
	(calibration_target instrument4 GroundStation11)
	(calibration_target instrument4 Star5)
	(calibration_target instrument4 Star3)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star14)
	(supports instrument5 spectrograph1)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 Star4)
	(calibration_target instrument5 GroundStation0)
	(calibration_target instrument5 GroundStation2)
	(supports instrument6 spectrograph1)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 Star6)
	(calibration_target instrument6 GroundStation1)
	(calibration_target instrument6 Star4)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet16)
	(supports instrument7 spectrograph1)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 Star6)
	(supports instrument8 thermograph0)
	(supports instrument8 spectrograph1)
	(calibration_target instrument8 Star6)
	(calibration_target instrument8 GroundStation12)
	(calibration_target instrument8 Star5)
	(supports instrument9 thermograph0)
	(supports instrument9 spectrograph1)
	(calibration_target instrument9 Star6)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet18)
	(supports instrument10 spectrograph1)
	(calibration_target instrument10 GroundStation0)
	(calibration_target instrument10 Star5)
	(supports instrument11 spectrograph1)
	(calibration_target instrument11 GroundStation1)
	(calibration_target instrument11 Star4)
	(calibration_target instrument11 GroundStation11)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet17)
	(supports instrument12 spectrograph1)
	(supports instrument12 thermograph0)
	(calibration_target instrument12 GroundStation0)
	(calibration_target instrument12 GroundStation2)
	(calibration_target instrument12 Star4)
	(supports instrument13 thermograph0)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 Star5)
	(calibration_target instrument13 GroundStation2)
	(calibration_target instrument13 GroundStation11)
	(calibration_target instrument13 Star9)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation7)
	(supports instrument14 spectrograph1)
	(supports instrument14 thermograph0)
	(calibration_target instrument14 Star4)
	(calibration_target instrument14 GroundStation2)
	(calibration_target instrument14 GroundStation1)
	(calibration_target instrument14 GroundStation7)
	(supports instrument15 spectrograph1)
	(supports instrument15 thermograph0)
	(calibration_target instrument15 GroundStation12)
	(calibration_target instrument15 Star9)
	(on_board instrument14 satellite6)
	(on_board instrument15 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star9)
)
(:goal (and
	(pointing satellite0 GroundStation7)
	(pointing satellite1 GroundStation7)
	(pointing satellite4 Planet18)
	(pointing satellite5 Star5)
	(have_image Planet13 spectrograph1)
	(have_image Star14 spectrograph1)
	(have_image Phenomenon15 spectrograph1)
	(have_image Planet16 spectrograph1)
	(have_image Planet17 spectrograph1)
	(have_image Planet18 thermograph0)
	(have_image Planet19 spectrograph1)
))

)
