(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite6 - satellite
	instrument13 - instrument
	satellite7 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite8 - satellite
	instrument17 - instrument
	satellite9 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite10 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	image1 - mode
	infrared0 - mode
	image2 - mode
	GroundStation5 - direction
	GroundStation8 - direction
	GroundStation2 - direction
	GroundStation6 - direction
	Star9 - direction
	Star3 - direction
	GroundStation7 - direction
	Star4 - direction
	Star0 - direction
	GroundStation1 - direction
	Star10 - direction
	Phenomenon11 - direction
	Phenomenon12 - direction
	Phenomenon13 - direction
	Star14 - direction
	Star15 - direction
)
(:init
	(supports instrument0 image1)
	(supports instrument0 image2)
	(supports instrument0 infrared0)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 image2)
	(supports instrument1 image1)
	(calibration_target instrument1 Star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation5)
	(supports instrument2 infrared0)
	(supports instrument2 image1)
	(calibration_target instrument2 GroundStation6)
	(calibration_target instrument2 Star9)
	(supports instrument3 image2)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 Star0)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star4)
	(supports instrument4 infrared0)
	(supports instrument4 image1)
	(calibration_target instrument4 Star3)
	(calibration_target instrument4 Star4)
	(calibration_target instrument4 GroundStation5)
	(supports instrument5 infrared0)
	(calibration_target instrument5 Star0)
	(supports instrument6 image1)
	(supports instrument6 infrared0)
	(calibration_target instrument6 GroundStation1)
	(calibration_target instrument6 GroundStation6)
	(calibration_target instrument6 Star3)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation1)
	(supports instrument7 image1)
	(supports instrument7 infrared0)
	(supports instrument7 image2)
	(calibration_target instrument7 Star3)
	(supports instrument8 infrared0)
	(supports instrument8 image1)
	(calibration_target instrument8 Star4)
	(supports instrument9 image2)
	(supports instrument9 infrared0)
	(supports instrument9 image1)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 Star3)
	(calibration_target instrument9 GroundStation5)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star10)
	(supports instrument10 image1)
	(supports instrument10 image2)
	(calibration_target instrument10 Star9)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation7)
	(supports instrument11 image2)
	(calibration_target instrument11 Star0)
	(supports instrument12 infrared0)
	(supports instrument12 image2)
	(supports instrument12 image1)
	(calibration_target instrument12 Star4)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star15)
	(supports instrument13 infrared0)
	(supports instrument13 image1)
	(calibration_target instrument13 GroundStation8)
	(calibration_target instrument13 GroundStation2)
	(calibration_target instrument13 Star4)
	(on_board instrument13 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star4)
	(supports instrument14 infrared0)
	(calibration_target instrument14 Star9)
	(calibration_target instrument14 GroundStation8)
	(supports instrument15 image2)
	(calibration_target instrument15 GroundStation8)
	(supports instrument16 image1)
	(calibration_target instrument16 GroundStation8)
	(calibration_target instrument16 Star0)
	(calibration_target instrument16 GroundStation2)
	(on_board instrument14 satellite7)
	(on_board instrument15 satellite7)
	(on_board instrument16 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation7)
	(supports instrument17 image1)
	(supports instrument17 image2)
	(supports instrument17 infrared0)
	(calibration_target instrument17 GroundStation6)
	(calibration_target instrument17 Star4)
	(on_board instrument17 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star3)
	(supports instrument18 image1)
	(supports instrument18 image2)
	(calibration_target instrument18 Star0)
	(calibration_target instrument18 GroundStation6)
	(calibration_target instrument18 GroundStation2)
	(supports instrument19 image2)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 Star9)
	(supports instrument20 infrared0)
	(calibration_target instrument20 Star0)
	(calibration_target instrument20 Star4)
	(on_board instrument18 satellite9)
	(on_board instrument19 satellite9)
	(on_board instrument20 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon12)
	(supports instrument21 image2)
	(calibration_target instrument21 GroundStation7)
	(calibration_target instrument21 GroundStation1)
	(calibration_target instrument21 Star3)
	(supports instrument22 image2)
	(supports instrument22 image1)
	(supports instrument22 infrared0)
	(calibration_target instrument22 Star4)
	(supports instrument23 image2)
	(calibration_target instrument23 GroundStation1)
	(calibration_target instrument23 Star0)
	(on_board instrument21 satellite10)
	(on_board instrument22 satellite10)
	(on_board instrument23 satellite10)
	(power_avail satellite10)
	(pointing satellite10 GroundStation2)
)
(:goal (and
	(pointing satellite0 Phenomenon13)
	(pointing satellite2 Star14)
	(pointing satellite5 Phenomenon12)
	(pointing satellite6 Star14)
	(pointing satellite7 Star0)
	(pointing satellite8 Phenomenon12)
	(pointing satellite9 GroundStation8)
	(have_image Star10 image2)
	(have_image Phenomenon11 infrared0)
	(have_image Phenomenon12 infrared0)
	(have_image Phenomenon13 infrared0)
	(have_image Star14 image1)
	(have_image Star15 image1)
))

)
