(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	satellite5 - satellite
	instrument13 - instrument
	instrument14 - instrument
	satellite6 - satellite
	instrument15 - instrument
	instrument16 - instrument
	satellite7 - satellite
	instrument17 - instrument
	satellite8 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite9 - satellite
	instrument21 - instrument
	instrument22 - instrument
	satellite10 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite11 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite12 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	thermograph3 - mode
	infrared0 - mode
	spectrograph2 - mode
	infrared1 - mode
	Star5 - direction
	Star7 - direction
	GroundStation2 - direction
	Star1 - direction
	GroundStation4 - direction
	GroundStation0 - direction
	GroundStation3 - direction
	GroundStation6 - direction
	Phenomenon8 - direction
	Phenomenon9 - direction
	Phenomenon10 - direction
	Star11 - direction
	Star12 - direction
	Phenomenon13 - direction
)
(:init
	(supports instrument0 infrared0)
	(supports instrument0 thermograph3)
	(calibration_target instrument0 Star7)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 thermograph3)
	(supports instrument1 infrared0)
	(supports instrument1 infrared1)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 GroundStation3)
	(supports instrument2 spectrograph2)
	(supports instrument2 thermograph3)
	(supports instrument2 infrared1)
	(calibration_target instrument2 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star11)
	(supports instrument3 infrared0)
	(supports instrument3 spectrograph2)
	(calibration_target instrument3 GroundStation0)
	(supports instrument4 infrared0)
	(calibration_target instrument4 GroundStation2)
	(calibration_target instrument4 GroundStation3)
	(supports instrument5 thermograph3)
	(supports instrument5 infrared0)
	(calibration_target instrument5 GroundStation2)
	(calibration_target instrument5 GroundStation0)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation0)
	(supports instrument6 infrared1)
	(calibration_target instrument6 GroundStation6)
	(supports instrument7 infrared1)
	(calibration_target instrument7 GroundStation3)
	(supports instrument8 infrared0)
	(calibration_target instrument8 GroundStation3)
	(calibration_target instrument8 Star7)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon13)
	(supports instrument9 spectrograph2)
	(supports instrument9 infrared1)
	(supports instrument9 infrared0)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 GroundStation0)
	(supports instrument10 infrared1)
	(supports instrument10 thermograph3)
	(supports instrument10 infrared0)
	(calibration_target instrument10 GroundStation3)
	(supports instrument11 spectrograph2)
	(supports instrument11 infrared0)
	(calibration_target instrument11 Star1)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon9)
	(supports instrument12 thermograph3)
	(supports instrument12 spectrograph2)
	(calibration_target instrument12 GroundStation6)
	(calibration_target instrument12 GroundStation3)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon10)
	(supports instrument13 infrared0)
	(supports instrument13 infrared1)
	(calibration_target instrument13 GroundStation2)
	(supports instrument14 thermograph3)
	(supports instrument14 spectrograph2)
	(calibration_target instrument14 GroundStation3)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star7)
	(supports instrument15 infrared1)
	(calibration_target instrument15 GroundStation2)
	(supports instrument16 spectrograph2)
	(supports instrument16 infrared1)
	(calibration_target instrument16 Star1)
	(calibration_target instrument16 Star5)
	(on_board instrument15 satellite6)
	(on_board instrument16 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation4)
	(supports instrument17 spectrograph2)
	(supports instrument17 infrared1)
	(calibration_target instrument17 Star7)
	(on_board instrument17 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star5)
	(supports instrument18 infrared1)
	(supports instrument18 thermograph3)
	(calibration_target instrument18 GroundStation4)
	(supports instrument19 thermograph3)
	(calibration_target instrument19 Star5)
	(supports instrument20 spectrograph2)
	(supports instrument20 thermograph3)
	(supports instrument20 infrared1)
	(calibration_target instrument20 Star1)
	(calibration_target instrument20 GroundStation4)
	(on_board instrument18 satellite8)
	(on_board instrument19 satellite8)
	(on_board instrument20 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star12)
	(supports instrument21 thermograph3)
	(calibration_target instrument21 GroundStation0)
	(supports instrument22 infrared1)
	(supports instrument22 infrared0)
	(supports instrument22 spectrograph2)
	(calibration_target instrument22 GroundStation3)
	(calibration_target instrument22 GroundStation4)
	(on_board instrument21 satellite9)
	(on_board instrument22 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon10)
	(supports instrument23 thermograph3)
	(calibration_target instrument23 GroundStation3)
	(supports instrument24 infrared1)
	(supports instrument24 spectrograph2)
	(supports instrument24 infrared0)
	(calibration_target instrument24 Star7)
	(supports instrument25 infrared0)
	(calibration_target instrument25 GroundStation2)
	(calibration_target instrument25 GroundStation3)
	(on_board instrument23 satellite10)
	(on_board instrument24 satellite10)
	(on_board instrument25 satellite10)
	(power_avail satellite10)
	(pointing satellite10 GroundStation0)
	(supports instrument26 spectrograph2)
	(calibration_target instrument26 GroundStation6)
	(supports instrument27 thermograph3)
	(supports instrument27 infrared0)
	(calibration_target instrument27 GroundStation2)
	(supports instrument28 thermograph3)
	(calibration_target instrument28 Star1)
	(calibration_target instrument28 GroundStation0)
	(on_board instrument26 satellite11)
	(on_board instrument27 satellite11)
	(on_board instrument28 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Star1)
	(supports instrument29 infrared0)
	(supports instrument29 thermograph3)
	(supports instrument29 infrared1)
	(calibration_target instrument29 GroundStation0)
	(calibration_target instrument29 GroundStation4)
	(supports instrument30 thermograph3)
	(calibration_target instrument30 GroundStation3)
	(supports instrument31 spectrograph2)
	(supports instrument31 infrared0)
	(supports instrument31 infrared1)
	(calibration_target instrument31 GroundStation6)
	(on_board instrument29 satellite12)
	(on_board instrument30 satellite12)
	(on_board instrument31 satellite12)
	(power_avail satellite12)
	(pointing satellite12 Star11)
)
(:goal (and
	(pointing satellite0 Star5)
	(pointing satellite1 Star12)
	(pointing satellite3 Star12)
	(pointing satellite4 GroundStation4)
	(pointing satellite5 GroundStation2)
	(pointing satellite7 Star5)
	(pointing satellite8 Star12)
	(pointing satellite10 Star7)
	(pointing satellite11 Phenomenon9)
	(have_image Phenomenon8 spectrograph2)
	(have_image Phenomenon9 thermograph3)
	(have_image Phenomenon10 infrared0)
	(have_image Star11 spectrograph2)
	(have_image Star12 infrared1)
	(have_image Phenomenon13 spectrograph2)
))

)
