(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	instrument11 - instrument
	satellite5 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite6 - satellite
	instrument15 - instrument
	instrument16 - instrument
	satellite7 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite8 - satellite
	instrument20 - instrument
	satellite9 - satellite
	instrument21 - instrument
	instrument22 - instrument
	infrared0 - mode
	infrared1 - mode
	infrared2 - mode
	Star1 - direction
	Star10 - direction
	Star6 - direction
	Star5 - direction
	Star8 - direction
	Star0 - direction
	Star3 - direction
	Star4 - direction
	Star7 - direction
	GroundStation2 - direction
	Star9 - direction
	Star11 - direction
	Phenomenon12 - direction
	Star13 - direction
	Planet14 - direction
	Planet15 - direction
	Phenomenon16 - direction
)
(:init
	(supports instrument0 infrared1)
	(supports instrument0 infrared2)
	(calibration_target instrument0 Star10)
	(calibration_target instrument0 Star9)
	(calibration_target instrument0 Star0)
	(supports instrument1 infrared2)
	(supports instrument1 infrared1)
	(calibration_target instrument1 Star3)
	(supports instrument2 infrared2)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 Star4)
	(calibration_target instrument2 Star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet15)
	(supports instrument3 infrared2)
	(supports instrument3 infrared0)
	(supports instrument3 infrared1)
	(calibration_target instrument3 Star8)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 Star5)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star7)
	(supports instrument4 infrared2)
	(supports instrument4 infrared0)
	(calibration_target instrument4 Star7)
	(supports instrument5 infrared0)
	(supports instrument5 infrared1)
	(supports instrument5 infrared2)
	(calibration_target instrument5 Star0)
	(supports instrument6 infrared2)
	(supports instrument6 infrared1)
	(supports instrument6 infrared0)
	(calibration_target instrument6 Star5)
	(calibration_target instrument6 Star6)
	(calibration_target instrument6 Star0)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star13)
	(supports instrument7 infrared2)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 Star9)
	(calibration_target instrument7 Star10)
	(supports instrument8 infrared2)
	(supports instrument8 infrared1)
	(supports instrument8 infrared0)
	(calibration_target instrument8 Star9)
	(calibration_target instrument8 Star10)
	(supports instrument9 infrared2)
	(supports instrument9 infrared1)
	(calibration_target instrument9 Star7)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon16)
	(supports instrument10 infrared2)
	(supports instrument10 infrared0)
	(supports instrument10 infrared1)
	(calibration_target instrument10 Star8)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 Star5)
	(supports instrument11 infrared0)
	(supports instrument11 infrared2)
	(supports instrument11 infrared1)
	(calibration_target instrument11 Star9)
	(calibration_target instrument11 Star4)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon12)
	(supports instrument12 infrared0)
	(calibration_target instrument12 Star8)
	(calibration_target instrument12 Star5)
	(supports instrument13 infrared1)
	(supports instrument13 infrared2)
	(supports instrument13 infrared0)
	(calibration_target instrument13 Star6)
	(calibration_target instrument13 GroundStation2)
	(supports instrument14 infrared2)
	(supports instrument14 infrared0)
	(supports instrument14 infrared1)
	(calibration_target instrument14 Star4)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon16)
	(supports instrument15 infrared2)
	(supports instrument15 infrared1)
	(supports instrument15 infrared0)
	(calibration_target instrument15 Star3)
	(calibration_target instrument15 Star8)
	(supports instrument16 infrared2)
	(supports instrument16 infrared0)
	(supports instrument16 infrared1)
	(calibration_target instrument16 Star5)
	(on_board instrument15 satellite6)
	(on_board instrument16 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star7)
	(supports instrument17 infrared1)
	(supports instrument17 infrared0)
	(calibration_target instrument17 GroundStation2)
	(calibration_target instrument17 Star9)
	(supports instrument18 infrared2)
	(supports instrument18 infrared1)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 Star8)
	(calibration_target instrument18 Star4)
	(supports instrument19 infrared0)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 Star9)
	(on_board instrument17 satellite7)
	(on_board instrument18 satellite7)
	(on_board instrument19 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star13)
	(supports instrument20 infrared0)
	(supports instrument20 infrared2)
	(calibration_target instrument20 Star7)
	(calibration_target instrument20 Star3)
	(calibration_target instrument20 Star0)
	(on_board instrument20 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon16)
	(supports instrument21 infrared0)
	(supports instrument21 infrared1)
	(supports instrument21 infrared2)
	(calibration_target instrument21 Star4)
	(calibration_target instrument21 Star9)
	(supports instrument22 infrared0)
	(supports instrument22 infrared1)
	(calibration_target instrument22 Star9)
	(calibration_target instrument22 GroundStation2)
	(calibration_target instrument22 Star7)
	(on_board instrument21 satellite9)
	(on_board instrument22 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star13)
)
(:goal (and
	(pointing satellite6 Star13)
	(have_image Star11 infrared1)
	(have_image Phenomenon12 infrared1)
	(have_image Star13 infrared2)
	(have_image Planet14 infrared0)
	(have_image Planet15 infrared0)
	(have_image Phenomenon16 infrared2)
))

)
