(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	instrument11 - instrument
	satellite5 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite6 - satellite
	instrument15 - instrument
	satellite7 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite8 - satellite
	instrument19 - instrument
	satellite9 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	thermograph0 - mode
	thermograph1 - mode
	Star2 - direction
	GroundStation7 - direction
	GroundStation4 - direction
	GroundStation6 - direction
	GroundStation1 - direction
	Star8 - direction
	GroundStation0 - direction
	Star3 - direction
	GroundStation5 - direction
	Phenomenon9 - direction
	Phenomenon10 - direction
	Star11 - direction
	Phenomenon12 - direction
	Planet13 - direction
	Star14 - direction
	Star15 - direction
	Planet16 - direction
	Planet17 - direction
)
(:init
	(supports instrument0 thermograph0)
	(calibration_target instrument0 Star2)
	(supports instrument1 thermograph0)
	(supports instrument1 thermograph1)
	(calibration_target instrument1 GroundStation7)
	(calibration_target instrument1 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation4)
	(supports instrument2 thermograph0)
	(supports instrument2 thermograph1)
	(calibration_target instrument2 GroundStation7)
	(calibration_target instrument2 GroundStation6)
	(supports instrument3 thermograph0)
	(supports instrument3 thermograph1)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 GroundStation7)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star2)
	(supports instrument4 thermograph0)
	(supports instrument4 thermograph1)
	(calibration_target instrument4 GroundStation1)
	(calibration_target instrument4 GroundStation4)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 GroundStation0)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 GroundStation7)
	(supports instrument6 thermograph1)
	(calibration_target instrument6 GroundStation5)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star11)
	(supports instrument7 thermograph0)
	(supports instrument7 thermograph1)
	(calibration_target instrument7 GroundStation5)
	(supports instrument8 thermograph1)
	(supports instrument8 thermograph0)
	(calibration_target instrument8 GroundStation6)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 GroundStation7)
	(calibration_target instrument9 GroundStation5)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star14)
	(supports instrument10 thermograph1)
	(supports instrument10 thermograph0)
	(calibration_target instrument10 GroundStation1)
	(supports instrument11 thermograph1)
	(supports instrument11 thermograph0)
	(calibration_target instrument11 GroundStation7)
	(calibration_target instrument11 GroundStation5)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet13)
	(supports instrument12 thermograph0)
	(supports instrument12 thermograph1)
	(calibration_target instrument12 GroundStation5)
	(calibration_target instrument12 GroundStation0)
	(calibration_target instrument12 GroundStation6)
	(supports instrument13 thermograph1)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 GroundStation6)
	(calibration_target instrument13 GroundStation0)
	(calibration_target instrument13 Star2)
	(supports instrument14 thermograph0)
	(supports instrument14 thermograph1)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 Star2)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation1)
	(supports instrument15 thermograph0)
	(supports instrument15 thermograph1)
	(calibration_target instrument15 GroundStation0)
	(calibration_target instrument15 Star8)
	(calibration_target instrument15 GroundStation5)
	(on_board instrument15 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star14)
	(supports instrument16 thermograph1)
	(supports instrument16 thermograph0)
	(calibration_target instrument16 Star8)
	(supports instrument17 thermograph1)
	(supports instrument17 thermograph0)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 GroundStation7)
	(calibration_target instrument17 Star8)
	(supports instrument18 thermograph1)
	(calibration_target instrument18 GroundStation6)
	(on_board instrument16 satellite7)
	(on_board instrument17 satellite7)
	(on_board instrument18 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star15)
	(supports instrument19 thermograph0)
	(supports instrument19 thermograph1)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 GroundStation6)
	(on_board instrument19 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation1)
	(supports instrument20 thermograph0)
	(supports instrument20 thermograph1)
	(calibration_target instrument20 GroundStation1)
	(calibration_target instrument20 Star8)
	(supports instrument21 thermograph1)
	(supports instrument21 thermograph0)
	(calibration_target instrument21 Star8)
	(supports instrument22 thermograph1)
	(calibration_target instrument22 GroundStation5)
	(calibration_target instrument22 Star3)
	(calibration_target instrument22 GroundStation0)
	(on_board instrument20 satellite9)
	(on_board instrument21 satellite9)
	(on_board instrument22 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star11)
)
(:goal (and
	(pointing satellite4 GroundStation7)
	(pointing satellite5 Phenomenon10)
	(pointing satellite9 Star15)
	(have_image Phenomenon9 thermograph1)
	(have_image Phenomenon10 thermograph0)
	(have_image Star11 thermograph0)
	(have_image Phenomenon12 thermograph0)
	(have_image Planet13 thermograph1)
	(have_image Star14 thermograph0)
	(have_image Star15 thermograph0)
	(have_image Planet16 thermograph1)
	(have_image Planet17 thermograph0)
))

)
