(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite6 - satellite
	instrument14 - instrument
	satellite7 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite8 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	infrared1 - mode
	image0 - mode
	infrared2 - mode
	GroundStation6 - direction
	Star3 - direction
	Star10 - direction
	Star11 - direction
	Star0 - direction
	Star8 - direction
	GroundStation9 - direction
	GroundStation4 - direction
	Star1 - direction
	Star7 - direction
	GroundStation2 - direction
	GroundStation5 - direction
	Phenomenon12 - direction
	Planet13 - direction
	Star14 - direction
	Planet15 - direction
	Star16 - direction
	Phenomenon17 - direction
)
(:init
	(supports instrument0 infrared1)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 Star11)
	(calibration_target instrument0 Star1)
	(supports instrument1 infrared1)
	(supports instrument1 infrared2)
	(supports instrument1 image0)
	(calibration_target instrument1 GroundStation5)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 GroundStation4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star1)
	(supports instrument2 image0)
	(supports instrument2 infrared2)
	(supports instrument2 infrared1)
	(calibration_target instrument2 Star1)
	(supports instrument3 infrared2)
	(supports instrument3 infrared1)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 Star1)
	(calibration_target instrument3 Star10)
	(supports instrument4 infrared1)
	(calibration_target instrument4 Star11)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 GroundStation4)
	(calibration_target instrument4 Star10)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(supports instrument5 image0)
	(supports instrument5 infrared2)
	(supports instrument5 infrared1)
	(calibration_target instrument5 GroundStation9)
	(calibration_target instrument5 Star7)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 GroundStation5)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet15)
	(supports instrument6 infrared2)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 Star10)
	(supports instrument7 image0)
	(calibration_target instrument7 Star1)
	(calibration_target instrument7 Star0)
	(calibration_target instrument7 Star10)
	(supports instrument8 infrared1)
	(supports instrument8 infrared2)
	(supports instrument8 image0)
	(calibration_target instrument8 Star11)
	(calibration_target instrument8 Star1)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 Star0)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation6)
	(supports instrument9 infrared2)
	(calibration_target instrument9 Star10)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 Star8)
	(calibration_target instrument9 GroundStation2)
	(supports instrument10 infrared2)
	(supports instrument10 infrared1)
	(calibration_target instrument10 GroundStation6)
	(calibration_target instrument10 Star7)
	(calibration_target instrument10 Star1)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation4)
	(supports instrument11 infrared2)
	(supports instrument11 image0)
	(supports instrument11 infrared1)
	(calibration_target instrument11 Star0)
	(supports instrument12 image0)
	(calibration_target instrument12 Star3)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star1)
	(calibration_target instrument12 Star10)
	(supports instrument13 infrared2)
	(supports instrument13 infrared1)
	(calibration_target instrument13 Star10)
	(calibration_target instrument13 GroundStation9)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 GroundStation6)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation5)
	(supports instrument14 infrared1)
	(calibration_target instrument14 GroundStation5)
	(calibration_target instrument14 Star3)
	(on_board instrument14 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star7)
	(supports instrument15 infrared1)
	(calibration_target instrument15 Star8)
	(calibration_target instrument15 Star3)
	(supports instrument16 infrared2)
	(supports instrument16 infrared1)
	(calibration_target instrument16 Star11)
	(calibration_target instrument16 Star7)
	(calibration_target instrument16 Star10)
	(calibration_target instrument16 GroundStation9)
	(supports instrument17 infrared2)
	(calibration_target instrument17 GroundStation9)
	(calibration_target instrument17 Star8)
	(calibration_target instrument17 Star0)
	(calibration_target instrument17 GroundStation5)
	(on_board instrument15 satellite7)
	(on_board instrument16 satellite7)
	(on_board instrument17 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star10)
	(supports instrument18 infrared1)
	(calibration_target instrument18 GroundStation4)
	(calibration_target instrument18 Star1)
	(supports instrument19 image0)
	(supports instrument19 infrared1)
	(supports instrument19 infrared2)
	(calibration_target instrument19 Star1)
	(calibration_target instrument19 GroundStation4)
	(calibration_target instrument19 GroundStation9)
	(calibration_target instrument19 GroundStation5)
	(supports instrument20 infrared1)
	(supports instrument20 infrared2)
	(supports instrument20 image0)
	(calibration_target instrument20 GroundStation5)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 Star7)
	(on_board instrument18 satellite8)
	(on_board instrument19 satellite8)
	(on_board instrument20 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star3)
)
(:goal (and
	(pointing satellite0 GroundStation9)
	(pointing satellite1 Star14)
	(pointing satellite3 GroundStation2)
	(pointing satellite4 Star8)
	(have_image Phenomenon12 infrared1)
	(have_image Planet13 infrared2)
	(have_image Star14 infrared2)
	(have_image Planet15 image0)
	(have_image Star16 infrared1)
	(have_image Phenomenon17 image0)
))

)
