(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	satellite5 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite6 - satellite
	instrument13 - instrument
	instrument14 - instrument
	spectrograph2 - mode
	thermograph1 - mode
	spectrograph0 - mode
	Star12 - direction
	GroundStation5 - direction
	Star11 - direction
	GroundStation1 - direction
	Star10 - direction
	Star13 - direction
	Star0 - direction
	Star2 - direction
	Star8 - direction
	Star7 - direction
	Star4 - direction
	Star14 - direction
	GroundStation6 - direction
	GroundStation3 - direction
	GroundStation9 - direction
	Star15 - direction
	Planet16 - direction
	Planet17 - direction
	Star18 - direction
	Planet19 - direction
	Star20 - direction
)
(:init
	(supports instrument0 spectrograph0)
	(supports instrument0 thermograph1)
	(calibration_target instrument0 Star14)
	(calibration_target instrument0 Star4)
	(calibration_target instrument0 GroundStation6)
	(calibration_target instrument0 Star7)
	(supports instrument1 spectrograph0)
	(supports instrument1 spectrograph2)
	(calibration_target instrument1 Star11)
	(calibration_target instrument1 Star10)
	(supports instrument2 spectrograph2)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 GroundStation6)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star12)
	(supports instrument3 spectrograph0)
	(supports instrument3 thermograph1)
	(supports instrument3 spectrograph2)
	(calibration_target instrument3 Star13)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation5)
	(supports instrument4 thermograph1)
	(supports instrument4 spectrograph0)
	(supports instrument4 spectrograph2)
	(calibration_target instrument4 Star8)
	(supports instrument5 spectrograph2)
	(calibration_target instrument5 GroundStation5)
	(calibration_target instrument5 Star7)
	(calibration_target instrument5 GroundStation3)
	(calibration_target instrument5 Star11)
	(calibration_target instrument5 Star14)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star12)
	(supports instrument6 spectrograph0)
	(supports instrument6 spectrograph2)
	(calibration_target instrument6 Star2)
	(supports instrument7 spectrograph0)
	(supports instrument7 spectrograph2)
	(supports instrument7 thermograph1)
	(calibration_target instrument7 Star11)
	(calibration_target instrument7 GroundStation6)
	(supports instrument8 spectrograph2)
	(supports instrument8 spectrograph0)
	(supports instrument8 thermograph1)
	(calibration_target instrument8 Star8)
	(calibration_target instrument8 GroundStation1)
	(calibration_target instrument8 Star4)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet19)
	(supports instrument9 thermograph1)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 Star10)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 GroundStation3)
	(calibration_target instrument9 Star2)
	(on_board instrument9 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet19)
	(supports instrument10 spectrograph0)
	(supports instrument10 thermograph1)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 Star13)
	(supports instrument11 spectrograph2)
	(supports instrument11 spectrograph0)
	(supports instrument11 thermograph1)
	(calibration_target instrument11 Star7)
	(calibration_target instrument11 GroundStation9)
	(supports instrument12 spectrograph0)
	(supports instrument12 thermograph1)
	(calibration_target instrument12 Star2)
	(calibration_target instrument12 Star14)
	(calibration_target instrument12 Star0)
	(on_board instrument10 satellite5)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star7)
	(supports instrument13 spectrograph2)
	(calibration_target instrument13 Star4)
	(calibration_target instrument13 Star7)
	(calibration_target instrument13 Star8)
	(calibration_target instrument13 GroundStation3)
	(supports instrument14 spectrograph2)
	(supports instrument14 thermograph1)
	(supports instrument14 spectrograph0)
	(calibration_target instrument14 GroundStation9)
	(calibration_target instrument14 GroundStation3)
	(calibration_target instrument14 GroundStation6)
	(calibration_target instrument14 Star14)
	(on_board instrument13 satellite6)
	(on_board instrument14 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star13)
)
(:goal (and
	(pointing satellite0 GroundStation9)
	(pointing satellite1 GroundStation9)
	(pointing satellite2 Planet16)
	(pointing satellite3 GroundStation3)
	(pointing satellite5 Star4)
	(pointing satellite6 Star15)
	(have_image Star15 thermograph1)
	(have_image Planet16 thermograph1)
	(have_image Planet17 thermograph1)
	(have_image Star18 spectrograph2)
	(have_image Planet19 thermograph1)
	(have_image Star20 spectrograph0)
))

)
