(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	satellite4 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite5 - satellite
	instrument9 - instrument
	satellite6 - satellite
	instrument10 - instrument
	instrument11 - instrument
	satellite7 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite8 - satellite
	instrument15 - instrument
	instrument16 - instrument
	satellite9 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite10 - satellite
	instrument20 - instrument
	instrument21 - instrument
	image4 - mode
	infrared2 - mode
	image3 - mode
	infrared1 - mode
	thermograph0 - mode
	GroundStation8 - direction
	GroundStation5 - direction
	Star0 - direction
	GroundStation2 - direction
	Star3 - direction
	Star6 - direction
	Star9 - direction
	GroundStation1 - direction
	GroundStation7 - direction
	Star4 - direction
	Phenomenon10 - direction
	Planet11 - direction
	Phenomenon12 - direction
	Star13 - direction
	Star14 - direction
)
(:init
	(supports instrument0 image4)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 Star3)
	(calibration_target instrument0 GroundStation5)
	(supports instrument1 image4)
	(supports instrument1 infrared2)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 Star4)
	(calibration_target instrument1 Star9)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star3)
	(supports instrument2 infrared1)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 Star9)
	(calibration_target instrument2 Star6)
	(supports instrument3 thermograph0)
	(supports instrument3 image4)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 GroundStation1)
	(calibration_target instrument3 Star6)
	(supports instrument4 infrared1)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 GroundStation5)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(supports instrument5 image3)
	(supports instrument5 thermograph0)
	(supports instrument5 image4)
	(calibration_target instrument5 GroundStation8)
	(calibration_target instrument5 GroundStation5)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation7)
	(supports instrument6 infrared1)
	(supports instrument6 thermograph0)
	(supports instrument6 image3)
	(calibration_target instrument6 GroundStation7)
	(calibration_target instrument6 GroundStation1)
	(on_board instrument6 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation2)
	(supports instrument7 thermograph0)
	(supports instrument7 infrared1)
	(supports instrument7 image4)
	(calibration_target instrument7 GroundStation5)
	(calibration_target instrument7 Star0)
	(calibration_target instrument7 Star3)
	(supports instrument8 infrared2)
	(supports instrument8 image4)
	(supports instrument8 image3)
	(calibration_target instrument8 GroundStation8)
	(calibration_target instrument8 GroundStation7)
	(calibration_target instrument8 GroundStation1)
	(on_board instrument7 satellite4)
	(on_board instrument8 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star9)
	(supports instrument9 infrared1)
	(supports instrument9 thermograph0)
	(supports instrument9 image4)
	(calibration_target instrument9 GroundStation5)
	(on_board instrument9 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation5)
	(supports instrument10 infrared1)
	(calibration_target instrument10 GroundStation8)
	(calibration_target instrument10 Star6)
	(supports instrument11 thermograph0)
	(supports instrument11 infrared2)
	(calibration_target instrument11 GroundStation2)
	(calibration_target instrument11 GroundStation5)
	(on_board instrument10 satellite6)
	(on_board instrument11 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet11)
	(supports instrument12 image3)
	(supports instrument12 infrared1)
	(supports instrument12 image4)
	(calibration_target instrument12 Star9)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star6)
	(supports instrument13 thermograph0)
	(supports instrument13 image3)
	(calibration_target instrument13 GroundStation2)
	(calibration_target instrument13 GroundStation1)
	(calibration_target instrument13 GroundStation7)
	(supports instrument14 image3)
	(supports instrument14 image4)
	(supports instrument14 infrared2)
	(calibration_target instrument14 Star4)
	(calibration_target instrument14 GroundStation1)
	(calibration_target instrument14 GroundStation2)
	(on_board instrument12 satellite7)
	(on_board instrument13 satellite7)
	(on_board instrument14 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star4)
	(supports instrument15 infrared2)
	(supports instrument15 infrared1)
	(supports instrument15 thermograph0)
	(calibration_target instrument15 Star3)
	(calibration_target instrument15 Star4)
	(calibration_target instrument15 Star6)
	(supports instrument16 infrared2)
	(calibration_target instrument16 Star6)
	(on_board instrument15 satellite8)
	(on_board instrument16 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star3)
	(supports instrument17 infrared1)
	(calibration_target instrument17 Star6)
	(calibration_target instrument17 Star4)
	(calibration_target instrument17 Star3)
	(supports instrument18 thermograph0)
	(supports instrument18 image4)
	(calibration_target instrument18 GroundStation1)
	(supports instrument19 thermograph0)
	(supports instrument19 infrared2)
	(calibration_target instrument19 GroundStation1)
	(calibration_target instrument19 Star9)
	(calibration_target instrument19 Star4)
	(on_board instrument17 satellite9)
	(on_board instrument18 satellite9)
	(on_board instrument19 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star9)
	(supports instrument20 infrared2)
	(supports instrument20 infrared1)
	(calibration_target instrument20 Star4)
	(calibration_target instrument20 GroundStation7)
	(supports instrument21 thermograph0)
	(supports instrument21 infrared2)
	(supports instrument21 image3)
	(calibration_target instrument21 Star4)
	(on_board instrument20 satellite10)
	(on_board instrument21 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Star0)
)
(:goal (and
	(pointing satellite2 Star13)
	(pointing satellite3 Star4)
	(pointing satellite6 Star13)
	(pointing satellite7 Star6)
	(pointing satellite8 Phenomenon10)
	(pointing satellite9 GroundStation5)
	(have_image Phenomenon10 image4)
	(have_image Planet11 image4)
	(have_image Phenomenon12 infrared1)
	(have_image Star13 image3)
	(have_image Star14 image3)
))

)
