(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite5 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	image0 - mode
	spectrograph1 - mode
	Star11 - direction
	GroundStation4 - direction
	GroundStation10 - direction
	GroundStation8 - direction
	Star9 - direction
	Star5 - direction
	GroundStation2 - direction
	GroundStation6 - direction
	GroundStation7 - direction
	GroundStation0 - direction
	Star14 - direction
	GroundStation1 - direction
	Star3 - direction
	GroundStation12 - direction
	Star13 - direction
	Star15 - direction
	Planet16 - direction
	Star17 - direction
	Phenomenon18 - direction
	Phenomenon19 - direction
	Phenomenon20 - direction
	Star21 - direction
)
(:init
	(supports instrument0 image0)
	(calibration_target instrument0 GroundStation4)
	(calibration_target instrument0 GroundStation0)
	(supports instrument1 spectrograph1)
	(supports instrument1 image0)
	(calibration_target instrument1 GroundStation4)
	(calibration_target instrument1 Star5)
	(supports instrument2 image0)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 Star11)
	(calibration_target instrument2 GroundStation12)
	(calibration_target instrument2 GroundStation7)
	(calibration_target instrument2 GroundStation4)
	(calibration_target instrument2 Star14)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation4)
	(supports instrument3 image0)
	(supports instrument3 spectrograph1)
	(calibration_target instrument3 GroundStation0)
	(calibration_target instrument3 Star14)
	(calibration_target instrument3 GroundStation4)
	(calibration_target instrument3 GroundStation7)
	(supports instrument4 spectrograph1)
	(supports instrument4 image0)
	(calibration_target instrument4 GroundStation12)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation12)
	(supports instrument5 spectrograph1)
	(supports instrument5 image0)
	(calibration_target instrument5 GroundStation1)
	(calibration_target instrument5 GroundStation7)
	(calibration_target instrument5 Star5)
	(calibration_target instrument5 GroundStation12)
	(calibration_target instrument5 GroundStation2)
	(supports instrument6 image0)
	(supports instrument6 spectrograph1)
	(calibration_target instrument6 GroundStation12)
	(calibration_target instrument6 GroundStation1)
	(calibration_target instrument6 Star9)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon19)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 GroundStation12)
	(calibration_target instrument7 Star13)
	(calibration_target instrument7 GroundStation2)
	(calibration_target instrument7 Star14)
	(calibration_target instrument7 GroundStation10)
	(supports instrument8 spectrograph1)
	(calibration_target instrument8 GroundStation12)
	(calibration_target instrument8 Star5)
	(supports instrument9 spectrograph1)
	(supports instrument9 image0)
	(calibration_target instrument9 Star5)
	(calibration_target instrument9 GroundStation12)
	(calibration_target instrument9 Star9)
	(calibration_target instrument9 GroundStation8)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star17)
	(supports instrument10 spectrograph1)
	(supports instrument10 image0)
	(calibration_target instrument10 Star13)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 GroundStation2)
	(calibration_target instrument10 Star5)
	(calibration_target instrument10 GroundStation6)
	(supports instrument11 spectrograph1)
	(supports instrument11 image0)
	(calibration_target instrument11 GroundStation0)
	(calibration_target instrument11 Star13)
	(calibration_target instrument11 GroundStation6)
	(supports instrument12 image0)
	(supports instrument12 spectrograph1)
	(calibration_target instrument12 Star3)
	(calibration_target instrument12 Star13)
	(calibration_target instrument12 Star14)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star3)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 GroundStation0)
	(calibration_target instrument13 GroundStation7)
	(calibration_target instrument13 GroundStation6)
	(supports instrument14 spectrograph1)
	(supports instrument14 image0)
	(calibration_target instrument14 GroundStation0)
	(calibration_target instrument14 GroundStation1)
	(supports instrument15 image0)
	(calibration_target instrument15 Star13)
	(calibration_target instrument15 GroundStation12)
	(calibration_target instrument15 Star3)
	(calibration_target instrument15 GroundStation1)
	(calibration_target instrument15 Star14)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet16)
)
(:goal (and
	(pointing satellite1 Phenomenon18)
	(pointing satellite3 Star17)
	(pointing satellite5 GroundStation2)
	(have_image Star15 spectrograph1)
	(have_image Planet16 spectrograph1)
	(have_image Star17 spectrograph1)
	(have_image Phenomenon18 spectrograph1)
	(have_image Phenomenon19 spectrograph1)
	(have_image Phenomenon20 image0)
	(have_image Star21 spectrograph1)
))

)
