(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite6 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite7 - satellite
	instrument16 - instrument
	satellite8 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite9 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	image5 - mode
	image1 - mode
	infrared0 - mode
	image3 - mode
	image2 - mode
	thermograph4 - mode
	Star3 - direction
	Star2 - direction
	Star1 - direction
	Star4 - direction
	GroundStation6 - direction
	GroundStation5 - direction
	Star0 - direction
	Planet7 - direction
	Star8 - direction
	Star9 - direction
	Phenomenon10 - direction
	Star11 - direction
	Phenomenon12 - direction
	Star13 - direction
)
(:init
	(supports instrument0 image1)
	(supports instrument0 image2)
	(supports instrument0 image5)
	(calibration_target instrument0 Star4)
	(supports instrument1 image1)
	(supports instrument1 image2)
	(supports instrument1 infrared0)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 Star4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star3)
	(supports instrument2 image2)
	(calibration_target instrument2 Star0)
	(supports instrument3 image2)
	(supports instrument3 image1)
	(calibration_target instrument3 GroundStation5)
	(supports instrument4 infrared0)
	(calibration_target instrument4 Star2)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star2)
	(supports instrument5 image3)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 Star2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet7)
	(supports instrument6 image3)
	(calibration_target instrument6 Star0)
	(calibration_target instrument6 GroundStation6)
	(supports instrument7 image1)
	(supports instrument7 infrared0)
	(calibration_target instrument7 Star2)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet7)
	(supports instrument8 infrared0)
	(supports instrument8 image1)
	(supports instrument8 image5)
	(calibration_target instrument8 Star1)
	(supports instrument9 image2)
	(supports instrument9 image1)
	(calibration_target instrument9 Star3)
	(supports instrument10 image2)
	(calibration_target instrument10 GroundStation5)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon10)
	(supports instrument11 image1)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 Star2)
	(supports instrument12 image5)
	(supports instrument12 image1)
	(supports instrument12 image3)
	(calibration_target instrument12 Star2)
	(calibration_target instrument12 Star4)
	(supports instrument13 thermograph4)
	(supports instrument13 image3)
	(supports instrument13 image2)
	(calibration_target instrument13 Star0)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star1)
	(supports instrument14 image3)
	(calibration_target instrument14 Star0)
	(calibration_target instrument14 Star4)
	(supports instrument15 image2)
	(supports instrument15 thermograph4)
	(supports instrument15 image5)
	(calibration_target instrument15 GroundStation5)
	(calibration_target instrument15 Star3)
	(on_board instrument14 satellite6)
	(on_board instrument15 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star8)
	(supports instrument16 image3)
	(supports instrument16 image5)
	(calibration_target instrument16 Star0)
	(on_board instrument16 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star11)
	(supports instrument17 image3)
	(supports instrument17 image2)
	(supports instrument17 image1)
	(calibration_target instrument17 Star1)
	(calibration_target instrument17 Star2)
	(supports instrument18 infrared0)
	(supports instrument18 image5)
	(supports instrument18 image2)
	(calibration_target instrument18 Star4)
	(supports instrument19 image3)
	(calibration_target instrument19 Star0)
	(on_board instrument17 satellite8)
	(on_board instrument18 satellite8)
	(on_board instrument19 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation6)
	(supports instrument20 image1)
	(calibration_target instrument20 GroundStation6)
	(calibration_target instrument20 GroundStation5)
	(supports instrument21 infrared0)
	(supports instrument21 image3)
	(supports instrument21 thermograph4)
	(calibration_target instrument21 Star0)
	(supports instrument22 image5)
	(supports instrument22 image3)
	(calibration_target instrument22 Star0)
	(calibration_target instrument22 GroundStation5)
	(on_board instrument20 satellite9)
	(on_board instrument21 satellite9)
	(on_board instrument22 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star8)
)
(:goal (and
	(pointing satellite0 GroundStation5)
	(pointing satellite3 Star1)
	(pointing satellite5 Star13)
	(pointing satellite7 GroundStation5)
	(pointing satellite9 Star0)
	(have_image Planet7 infrared0)
	(have_image Planet7 thermograph4)
	(have_image Star8 image3)
	(have_image Star9 infrared0)
	(have_image Star9 thermograph4)
	(have_image Phenomenon10 image1)
	(have_image Phenomenon10 image2)
	(have_image Star11 thermograph4)
	(have_image Phenomenon12 thermograph4)
	(have_image Phenomenon12 image5)
	(have_image Star13 image5)
))

)
