(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite5 - satellite
	instrument13 - instrument
	instrument14 - instrument
	thermograph3 - mode
	thermograph0 - mode
	infrared2 - mode
	image1 - mode
	Star5 - direction
	GroundStation10 - direction
	GroundStation11 - direction
	Star7 - direction
	GroundStation2 - direction
	Star12 - direction
	Star4 - direction
	GroundStation9 - direction
	Star6 - direction
	Star8 - direction
	Star0 - direction
	Star1 - direction
	Star3 - direction
	Phenomenon13 - direction
	Phenomenon14 - direction
	Star15 - direction
	Phenomenon16 - direction
	Star17 - direction
	Star18 - direction
	Phenomenon19 - direction
)
(:init
	(supports instrument0 image1)
	(supports instrument0 thermograph3)
	(supports instrument0 thermograph0)
	(calibration_target instrument0 Star7)
	(supports instrument1 infrared2)
	(supports instrument1 thermograph3)
	(calibration_target instrument1 Star7)
	(calibration_target instrument1 Star8)
	(calibration_target instrument1 GroundStation9)
	(calibration_target instrument1 Star12)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 Star6)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon13)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 Star7)
	(calibration_target instrument3 GroundStation10)
	(calibration_target instrument3 Star8)
	(supports instrument4 thermograph0)
	(supports instrument4 infrared2)
	(supports instrument4 thermograph3)
	(calibration_target instrument4 Star3)
	(supports instrument5 thermograph0)
	(supports instrument5 image1)
	(supports instrument5 infrared2)
	(calibration_target instrument5 GroundStation2)
	(calibration_target instrument5 Star3)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon16)
	(supports instrument6 thermograph3)
	(supports instrument6 thermograph0)
	(supports instrument6 image1)
	(calibration_target instrument6 Star8)
	(calibration_target instrument6 Star3)
	(calibration_target instrument6 Star6)
	(supports instrument7 infrared2)
	(supports instrument7 thermograph0)
	(supports instrument7 thermograph3)
	(calibration_target instrument7 Star12)
	(calibration_target instrument7 Star8)
	(calibration_target instrument7 Star7)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon14)
	(supports instrument8 image1)
	(supports instrument8 thermograph3)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 Star7)
	(calibration_target instrument8 GroundStation11)
	(calibration_target instrument8 Star6)
	(supports instrument9 image1)
	(supports instrument9 infrared2)
	(calibration_target instrument9 Star12)
	(calibration_target instrument9 GroundStation9)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 Star6)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star18)
	(supports instrument10 image1)
	(supports instrument10 thermograph0)
	(calibration_target instrument10 GroundStation9)
	(calibration_target instrument10 Star12)
	(supports instrument11 thermograph0)
	(supports instrument11 infrared2)
	(calibration_target instrument11 Star4)
	(supports instrument12 thermograph3)
	(supports instrument12 image1)
	(supports instrument12 infrared2)
	(calibration_target instrument12 Star6)
	(calibration_target instrument12 Star1)
	(calibration_target instrument12 GroundStation9)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star7)
	(supports instrument13 image1)
	(calibration_target instrument13 Star1)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 Star8)
	(supports instrument14 infrared2)
	(supports instrument14 thermograph0)
	(supports instrument14 thermograph3)
	(calibration_target instrument14 Star3)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon16)
)
(:goal (and
	(pointing satellite1 Star8)
	(pointing satellite3 Star1)
	(pointing satellite5 Star1)
	(have_image Phenomenon13 image1)
	(have_image Phenomenon14 image1)
	(have_image Star15 thermograph0)
	(have_image Phenomenon16 thermograph3)
	(have_image Star17 thermograph0)
	(have_image Star18 infrared2)
	(have_image Phenomenon19 infrared2)
))

)
