(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite4 - satellite
	instrument11 - instrument
	satellite5 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite6 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite7 - satellite
	instrument18 - instrument
	satellite8 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite9 - satellite
	instrument22 - instrument
	instrument23 - instrument
	satellite10 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite11 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite12 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite13 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite14 - satellite
	instrument36 - instrument
	image0 - mode
	image1 - mode
	GroundStation5 - direction
	GroundStation6 - direction
	GroundStation4 - direction
	GroundStation0 - direction
	GroundStation2 - direction
	Star8 - direction
	Star3 - direction
	GroundStation1 - direction
	Star7 - direction
	Phenomenon9 - direction
	Phenomenon10 - direction
	Star11 - direction
	Planet12 - direction
	Phenomenon13 - direction
)
(:init
	(supports instrument0 image1)
	(supports instrument0 image0)
	(calibration_target instrument0 GroundStation6)
	(calibration_target instrument0 Star7)
	(calibration_target instrument0 GroundStation0)
	(supports instrument1 image0)
	(supports instrument1 image1)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 GroundStation4)
	(supports instrument2 image1)
	(supports instrument2 image0)
	(calibration_target instrument2 GroundStation6)
	(calibration_target instrument2 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation2)
	(supports instrument3 image1)
	(supports instrument3 image0)
	(calibration_target instrument3 GroundStation4)
	(calibration_target instrument3 GroundStation0)
	(supports instrument4 image1)
	(supports instrument4 image0)
	(calibration_target instrument4 Star8)
	(calibration_target instrument4 GroundStation6)
	(supports instrument5 image1)
	(calibration_target instrument5 GroundStation0)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation6)
	(supports instrument6 image0)
	(calibration_target instrument6 GroundStation6)
	(calibration_target instrument6 Star8)
	(supports instrument7 image0)
	(supports instrument7 image1)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 GroundStation6)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation2)
	(supports instrument8 image0)
	(calibration_target instrument8 Star8)
	(supports instrument9 image1)
	(supports instrument9 image0)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 GroundStation2)
	(supports instrument10 image0)
	(calibration_target instrument10 Star3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation0)
	(supports instrument11 image1)
	(supports instrument11 image0)
	(calibration_target instrument11 GroundStation6)
	(calibration_target instrument11 GroundStation5)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation4)
	(supports instrument12 image0)
	(supports instrument12 image1)
	(calibration_target instrument12 Star7)
	(calibration_target instrument12 Star3)
	(supports instrument13 image0)
	(supports instrument13 image1)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 GroundStation5)
	(supports instrument14 image0)
	(supports instrument14 image1)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 GroundStation6)
	(calibration_target instrument14 GroundStation0)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation0)
	(supports instrument15 image1)
	(supports instrument15 image0)
	(calibration_target instrument15 Star3)
	(calibration_target instrument15 GroundStation0)
	(supports instrument16 image0)
	(supports instrument16 image1)
	(calibration_target instrument16 GroundStation5)
	(supports instrument17 image1)
	(supports instrument17 image0)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 GroundStation6)
	(on_board instrument15 satellite6)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation2)
	(supports instrument18 image0)
	(calibration_target instrument18 Star8)
	(calibration_target instrument18 GroundStation6)
	(calibration_target instrument18 Star7)
	(on_board instrument18 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon10)
	(supports instrument19 image1)
	(supports instrument19 image0)
	(calibration_target instrument19 GroundStation5)
	(calibration_target instrument19 GroundStation0)
	(calibration_target instrument19 Star7)
	(supports instrument20 image0)
	(supports instrument20 image1)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 GroundStation4)
	(supports instrument21 image1)
	(supports instrument21 image0)
	(calibration_target instrument21 GroundStation1)
	(calibration_target instrument21 GroundStation5)
	(calibration_target instrument21 Star7)
	(on_board instrument19 satellite8)
	(on_board instrument20 satellite8)
	(on_board instrument21 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon13)
	(supports instrument22 image1)
	(calibration_target instrument22 GroundStation0)
	(calibration_target instrument22 GroundStation1)
	(calibration_target instrument22 GroundStation5)
	(supports instrument23 image0)
	(supports instrument23 image1)
	(calibration_target instrument23 Star8)
	(on_board instrument22 satellite9)
	(on_board instrument23 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation0)
	(supports instrument24 image1)
	(supports instrument24 image0)
	(calibration_target instrument24 GroundStation4)
	(calibration_target instrument24 GroundStation2)
	(calibration_target instrument24 GroundStation0)
	(supports instrument25 image1)
	(supports instrument25 image0)
	(calibration_target instrument25 Star8)
	(calibration_target instrument25 GroundStation2)
	(supports instrument26 image1)
	(supports instrument26 image0)
	(calibration_target instrument26 Star3)
	(calibration_target instrument26 GroundStation2)
	(calibration_target instrument26 GroundStation1)
	(on_board instrument24 satellite10)
	(on_board instrument25 satellite10)
	(on_board instrument26 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Planet12)
	(supports instrument27 image0)
	(supports instrument27 image1)
	(calibration_target instrument27 Star3)
	(calibration_target instrument27 Star8)
	(calibration_target instrument27 GroundStation0)
	(supports instrument28 image0)
	(calibration_target instrument28 Star7)
	(calibration_target instrument28 GroundStation4)
	(calibration_target instrument28 GroundStation2)
	(supports instrument29 image0)
	(supports instrument29 image1)
	(calibration_target instrument29 Star7)
	(on_board instrument27 satellite11)
	(on_board instrument28 satellite11)
	(on_board instrument29 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Star7)
	(supports instrument30 image0)
	(calibration_target instrument30 GroundStation6)
	(calibration_target instrument30 Star8)
	(calibration_target instrument30 GroundStation1)
	(supports instrument31 image1)
	(calibration_target instrument31 GroundStation0)
	(supports instrument32 image1)
	(supports instrument32 image0)
	(calibration_target instrument32 GroundStation4)
	(on_board instrument30 satellite12)
	(on_board instrument31 satellite12)
	(on_board instrument32 satellite12)
	(power_avail satellite12)
	(pointing satellite12 Star7)
	(supports instrument33 image0)
	(supports instrument33 image1)
	(calibration_target instrument33 Star7)
	(calibration_target instrument33 GroundStation0)
	(calibration_target instrument33 GroundStation1)
	(supports instrument34 image0)
	(calibration_target instrument34 GroundStation2)
	(supports instrument35 image1)
	(calibration_target instrument35 GroundStation1)
	(calibration_target instrument35 Star8)
	(calibration_target instrument35 Star7)
	(on_board instrument33 satellite13)
	(on_board instrument34 satellite13)
	(on_board instrument35 satellite13)
	(power_avail satellite13)
	(pointing satellite13 GroundStation1)
	(supports instrument36 image0)
	(supports instrument36 image1)
	(calibration_target instrument36 Star7)
	(calibration_target instrument36 GroundStation1)
	(calibration_target instrument36 Star3)
	(on_board instrument36 satellite14)
	(power_avail satellite14)
	(pointing satellite14 Star3)
)
(:goal (and
	(pointing satellite4 Star3)
	(pointing satellite5 Phenomenon10)
	(pointing satellite6 Star7)
	(pointing satellite7 Phenomenon9)
	(pointing satellite8 Star3)
	(pointing satellite10 Planet12)
	(have_image Phenomenon9 image1)
	(have_image Phenomenon10 image1)
	(have_image Star11 image0)
	(have_image Planet12 image1)
	(have_image Phenomenon13 image0)
))

)
