(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite6 - satellite
	instrument13 - instrument
	satellite7 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite8 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite9 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite10 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite11 - satellite
	instrument25 - instrument
	satellite12 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	spectrograph0 - mode
	image4 - mode
	infrared2 - mode
	spectrograph3 - mode
	image1 - mode
	Star4 - direction
	Star0 - direction
	GroundStation5 - direction
	GroundStation3 - direction
	Star6 - direction
	Star2 - direction
	GroundStation1 - direction
	Star7 - direction
	Planet8 - direction
	Star9 - direction
	Planet10 - direction
	Phenomenon11 - direction
)
(:init
	(supports instrument0 image1)
	(supports instrument0 spectrograph3)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 Star6)
	(supports instrument1 infrared2)
	(supports instrument1 spectrograph3)
	(supports instrument1 spectrograph0)
	(calibration_target instrument1 Star2)
	(calibration_target instrument1 Star0)
	(supports instrument2 infrared2)
	(supports instrument2 image4)
	(calibration_target instrument2 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation5)
	(supports instrument3 image4)
	(calibration_target instrument3 GroundStation5)
	(calibration_target instrument3 Star6)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon11)
	(supports instrument4 image4)
	(supports instrument4 spectrograph0)
	(supports instrument4 spectrograph3)
	(calibration_target instrument4 Star4)
	(calibration_target instrument4 Star6)
	(supports instrument5 spectrograph3)
	(supports instrument5 image1)
	(calibration_target instrument5 Star2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star6)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 Star2)
	(calibration_target instrument6 Star4)
	(supports instrument7 image4)
	(supports instrument7 infrared2)
	(supports instrument7 spectrograph0)
	(calibration_target instrument7 Star4)
	(calibration_target instrument7 GroundStation3)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star6)
	(supports instrument8 image1)
	(calibration_target instrument8 GroundStation1)
	(calibration_target instrument8 Star4)
	(supports instrument9 spectrograph3)
	(supports instrument9 image1)
	(calibration_target instrument9 Star0)
	(supports instrument10 image4)
	(calibration_target instrument10 GroundStation3)
	(calibration_target instrument10 Star4)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star9)
	(supports instrument11 image1)
	(supports instrument11 spectrograph3)
	(supports instrument11 image4)
	(calibration_target instrument11 Star0)
	(calibration_target instrument11 Star2)
	(supports instrument12 infrared2)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 Star6)
	(calibration_target instrument12 Star4)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star0)
	(supports instrument13 spectrograph0)
	(calibration_target instrument13 GroundStation5)
	(calibration_target instrument13 GroundStation1)
	(on_board instrument13 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation3)
	(supports instrument14 infrared2)
	(supports instrument14 spectrograph0)
	(calibration_target instrument14 Star6)
	(calibration_target instrument14 Star4)
	(supports instrument15 image4)
	(supports instrument15 spectrograph0)
	(calibration_target instrument15 GroundStation5)
	(calibration_target instrument15 GroundStation1)
	(on_board instrument14 satellite7)
	(on_board instrument15 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation5)
	(supports instrument16 infrared2)
	(supports instrument16 image4)
	(supports instrument16 spectrograph3)
	(calibration_target instrument16 Star6)
	(supports instrument17 infrared2)
	(supports instrument17 spectrograph3)
	(supports instrument17 image4)
	(calibration_target instrument17 Star0)
	(calibration_target instrument17 Star2)
	(supports instrument18 image4)
	(supports instrument18 infrared2)
	(supports instrument18 spectrograph0)
	(calibration_target instrument18 GroundStation5)
	(on_board instrument16 satellite8)
	(on_board instrument17 satellite8)
	(on_board instrument18 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star7)
	(supports instrument19 spectrograph0)
	(supports instrument19 spectrograph3)
	(calibration_target instrument19 Star6)
	(calibration_target instrument19 Star0)
	(supports instrument20 image1)
	(supports instrument20 image4)
	(calibration_target instrument20 Star0)
	(supports instrument21 spectrograph3)
	(supports instrument21 infrared2)
	(calibration_target instrument21 Star6)
	(on_board instrument19 satellite9)
	(on_board instrument20 satellite9)
	(on_board instrument21 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet8)
	(supports instrument22 image1)
	(supports instrument22 image4)
	(calibration_target instrument22 GroundStation3)
	(supports instrument23 image4)
	(supports instrument23 infrared2)
	(calibration_target instrument23 Star6)
	(supports instrument24 image4)
	(supports instrument24 spectrograph3)
	(supports instrument24 infrared2)
	(calibration_target instrument24 Star6)
	(calibration_target instrument24 Star2)
	(on_board instrument22 satellite10)
	(on_board instrument23 satellite10)
	(on_board instrument24 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Star7)
	(supports instrument25 infrared2)
	(supports instrument25 image4)
	(supports instrument25 image1)
	(calibration_target instrument25 GroundStation5)
	(calibration_target instrument25 GroundStation3)
	(on_board instrument25 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Planet10)
	(supports instrument26 infrared2)
	(calibration_target instrument26 GroundStation3)
	(calibration_target instrument26 GroundStation5)
	(supports instrument27 spectrograph0)
	(supports instrument27 image1)
	(supports instrument27 infrared2)
	(calibration_target instrument27 GroundStation1)
	(calibration_target instrument27 Star6)
	(supports instrument28 spectrograph0)
	(calibration_target instrument28 GroundStation1)
	(calibration_target instrument28 Star2)
	(on_board instrument26 satellite12)
	(on_board instrument27 satellite12)
	(on_board instrument28 satellite12)
	(power_avail satellite12)
	(pointing satellite12 Star9)
)
(:goal (and
	(pointing satellite8 Star0)
	(pointing satellite10 GroundStation1)
	(pointing satellite12 Star7)
	(have_image Star7 infrared2)
	(have_image Planet8 image1)
	(have_image Star9 image1)
	(have_image Planet10 infrared2)
	(have_image Phenomenon11 infrared2)
))

)
