(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite4 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite5 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite6 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite7 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	thermograph0 - mode
	infrared1 - mode
	infrared2 - mode
	spectrograph3 - mode
	GroundStation6 - direction
	Star0 - direction
	Star7 - direction
	GroundStation3 - direction
	GroundStation4 - direction
	Star1 - direction
	GroundStation2 - direction
	GroundStation5 - direction
	Planet8 - direction
	Star9 - direction
	Phenomenon10 - direction
	Planet11 - direction
	Phenomenon12 - direction
	Phenomenon13 - direction
	Planet14 - direction
	Star15 - direction
)
(:init
	(supports instrument0 infrared2)
	(supports instrument0 infrared1)
	(calibration_target instrument0 Star1)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 infrared1)
	(supports instrument1 spectrograph3)
	(calibration_target instrument1 Star7)
	(calibration_target instrument1 Star0)
	(supports instrument2 infrared1)
	(supports instrument2 spectrograph3)
	(calibration_target instrument2 GroundStation3)
	(calibration_target instrument2 GroundStation5)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon13)
	(supports instrument3 infrared1)
	(supports instrument3 spectrograph3)
	(calibration_target instrument3 GroundStation4)
	(supports instrument4 thermograph0)
	(supports instrument4 spectrograph3)
	(calibration_target instrument4 Star0)
	(supports instrument5 spectrograph3)
	(supports instrument5 infrared1)
	(supports instrument5 infrared2)
	(calibration_target instrument5 Star7)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star7)
	(supports instrument6 infrared2)
	(supports instrument6 infrared1)
	(calibration_target instrument6 GroundStation2)
	(calibration_target instrument6 Star1)
	(supports instrument7 spectrograph3)
	(supports instrument7 infrared2)
	(calibration_target instrument7 GroundStation3)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon12)
	(supports instrument8 thermograph0)
	(supports instrument8 spectrograph3)
	(calibration_target instrument8 GroundStation2)
	(supports instrument9 thermograph0)
	(calibration_target instrument9 Star1)
	(calibration_target instrument9 GroundStation5)
	(supports instrument10 infrared2)
	(supports instrument10 spectrograph3)
	(supports instrument10 infrared1)
	(calibration_target instrument10 GroundStation5)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation2)
	(supports instrument11 infrared2)
	(supports instrument11 thermograph0)
	(calibration_target instrument11 GroundStation3)
	(supports instrument12 infrared2)
	(calibration_target instrument12 Star7)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation5)
	(supports instrument13 spectrograph3)
	(supports instrument13 infrared2)
	(supports instrument13 infrared1)
	(calibration_target instrument13 GroundStation4)
	(supports instrument14 spectrograph3)
	(calibration_target instrument14 Star1)
	(calibration_target instrument14 GroundStation5)
	(supports instrument15 infrared1)
	(supports instrument15 thermograph0)
	(calibration_target instrument15 GroundStation5)
	(calibration_target instrument15 GroundStation2)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star9)
	(supports instrument16 infrared1)
	(supports instrument16 infrared2)
	(calibration_target instrument16 GroundStation2)
	(calibration_target instrument16 GroundStation3)
	(supports instrument17 spectrograph3)
	(supports instrument17 thermograph0)
	(supports instrument17 infrared2)
	(calibration_target instrument17 Star1)
	(calibration_target instrument17 GroundStation4)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet14)
	(supports instrument18 thermograph0)
	(supports instrument18 spectrograph3)
	(supports instrument18 infrared2)
	(calibration_target instrument18 Star1)
	(supports instrument19 thermograph0)
	(supports instrument19 infrared2)
	(calibration_target instrument19 GroundStation2)
	(supports instrument20 thermograph0)
	(calibration_target instrument20 GroundStation5)
	(calibration_target instrument20 GroundStation2)
	(on_board instrument18 satellite7)
	(on_board instrument19 satellite7)
	(on_board instrument20 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon13)
)
(:goal (and
	(pointing satellite0 GroundStation6)
	(pointing satellite1 GroundStation3)
	(pointing satellite4 Planet11)
	(pointing satellite7 Planet14)
	(have_image Planet8 spectrograph3)
	(have_image Star9 spectrograph3)
	(have_image Phenomenon10 infrared1)
	(have_image Planet11 infrared2)
	(have_image Phenomenon12 thermograph0)
	(have_image Phenomenon13 spectrograph3)
	(have_image Planet14 infrared2)
	(have_image Star15 infrared1)
))

)
