(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	instrument11 - instrument
	satellite5 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite6 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite7 - satellite
	instrument18 - instrument
	satellite8 - satellite
	instrument19 - instrument
	instrument20 - instrument
	satellite9 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	image1 - mode
	image2 - mode
	spectrograph0 - mode
	Star2 - direction
	GroundStation0 - direction
	GroundStation9 - direction
	GroundStation5 - direction
	GroundStation4 - direction
	Star7 - direction
	Star3 - direction
	GroundStation8 - direction
	GroundStation6 - direction
	Star1 - direction
	Phenomenon10 - direction
	Planet11 - direction
	Phenomenon12 - direction
	Planet13 - direction
	Planet14 - direction
	Star15 - direction
)
(:init
	(supports instrument0 image2)
	(supports instrument0 image1)
	(supports instrument0 spectrograph0)
	(calibration_target instrument0 Star1)
	(calibration_target instrument0 GroundStation0)
	(calibration_target instrument0 GroundStation8)
	(supports instrument1 spectrograph0)
	(supports instrument1 image1)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 GroundStation5)
	(calibration_target instrument1 GroundStation8)
	(supports instrument2 image2)
	(supports instrument2 image1)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 Star7)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation0)
	(supports instrument3 spectrograph0)
	(supports instrument3 image2)
	(supports instrument3 image1)
	(calibration_target instrument3 Star2)
	(supports instrument4 image1)
	(supports instrument4 spectrograph0)
	(calibration_target instrument4 GroundStation9)
	(supports instrument5 spectrograph0)
	(supports instrument5 image1)
	(supports instrument5 image2)
	(calibration_target instrument5 GroundStation9)
	(calibration_target instrument5 GroundStation0)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star3)
	(supports instrument6 spectrograph0)
	(supports instrument6 image1)
	(supports instrument6 image2)
	(calibration_target instrument6 Star1)
	(calibration_target instrument6 GroundStation4)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation6)
	(supports instrument7 image1)
	(supports instrument7 spectrograph0)
	(calibration_target instrument7 Star7)
	(supports instrument8 spectrograph0)
	(supports instrument8 image2)
	(calibration_target instrument8 GroundStation6)
	(calibration_target instrument8 Star7)
	(calibration_target instrument8 GroundStation9)
	(supports instrument9 spectrograph0)
	(supports instrument9 image1)
	(calibration_target instrument9 GroundStation5)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation9)
	(supports instrument10 image1)
	(calibration_target instrument10 Star7)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 GroundStation8)
	(supports instrument11 spectrograph0)
	(supports instrument11 image2)
	(supports instrument11 image1)
	(calibration_target instrument11 Star2)
	(calibration_target instrument11 GroundStation5)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star15)
	(supports instrument12 spectrograph0)
	(supports instrument12 image1)
	(supports instrument12 image2)
	(calibration_target instrument12 GroundStation5)
	(calibration_target instrument12 GroundStation8)
	(supports instrument13 image2)
	(supports instrument13 spectrograph0)
	(calibration_target instrument13 Star1)
	(calibration_target instrument13 Star7)
	(supports instrument14 image1)
	(calibration_target instrument14 GroundStation0)
	(calibration_target instrument14 GroundStation5)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation8)
	(supports instrument15 image1)
	(calibration_target instrument15 GroundStation8)
	(calibration_target instrument15 GroundStation4)
	(supports instrument16 spectrograph0)
	(calibration_target instrument16 Star3)
	(calibration_target instrument16 GroundStation6)
	(supports instrument17 image1)
	(supports instrument17 image2)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 GroundStation8)
	(calibration_target instrument17 GroundStation9)
	(calibration_target instrument17 GroundStation5)
	(on_board instrument15 satellite6)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet13)
	(supports instrument18 image2)
	(supports instrument18 image1)
	(calibration_target instrument18 GroundStation8)
	(calibration_target instrument18 GroundStation5)
	(on_board instrument18 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star3)
	(supports instrument19 spectrograph0)
	(supports instrument19 image1)
	(supports instrument19 image2)
	(calibration_target instrument19 GroundStation4)
	(supports instrument20 image1)
	(supports instrument20 spectrograph0)
	(calibration_target instrument20 GroundStation8)
	(on_board instrument19 satellite8)
	(on_board instrument20 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation9)
	(supports instrument21 image2)
	(supports instrument21 spectrograph0)
	(calibration_target instrument21 Star3)
	(calibration_target instrument21 Star7)
	(supports instrument22 image1)
	(supports instrument22 image2)
	(calibration_target instrument22 GroundStation6)
	(supports instrument23 image2)
	(supports instrument23 spectrograph0)
	(calibration_target instrument23 Star1)
	(calibration_target instrument23 GroundStation6)
	(calibration_target instrument23 GroundStation8)
	(on_board instrument21 satellite9)
	(on_board instrument22 satellite9)
	(on_board instrument23 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star15)
)
(:goal (and
	(pointing satellite0 Planet14)
	(pointing satellite8 GroundStation9)
	(have_image Phenomenon10 image2)
	(have_image Planet11 image2)
	(have_image Phenomenon12 image2)
	(have_image Planet13 image1)
	(have_image Planet14 spectrograph0)
	(have_image Star15 image2)
))

)
