(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite4 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite5 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite6 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite7 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite8 - satellite
	instrument21 - instrument
	satellite9 - satellite
	instrument22 - instrument
	instrument23 - instrument
	satellite10 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite11 - satellite
	instrument27 - instrument
	instrument28 - instrument
	satellite12 - satellite
	instrument29 - instrument
	satellite13 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite14 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite15 - satellite
	instrument36 - instrument
	satellite16 - satellite
	instrument37 - instrument
	instrument38 - instrument
	thermograph1 - mode
	thermograph0 - mode
	thermograph2 - mode
	Star4 - direction
	GroundStation2 - direction
	GroundStation0 - direction
	GroundStation1 - direction
	GroundStation3 - direction
	Planet5 - direction
	Star6 - direction
	Planet7 - direction
	Planet8 - direction
	Planet9 - direction
	Phenomenon10 - direction
)
(:init
	(supports instrument0 thermograph0)
	(supports instrument0 thermograph2)
	(calibration_target instrument0 Star4)
	(supports instrument1 thermograph0)
	(calibration_target instrument1 GroundStation0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star6)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 GroundStation2)
	(supports instrument3 thermograph1)
	(calibration_target instrument3 GroundStation1)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 GroundStation2)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet9)
	(supports instrument5 thermograph2)
	(supports instrument5 thermograph0)
	(supports instrument5 thermograph1)
	(calibration_target instrument5 GroundStation0)
	(supports instrument6 thermograph1)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 GroundStation1)
	(supports instrument7 thermograph1)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 GroundStation0)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star4)
	(supports instrument8 thermograph2)
	(supports instrument8 thermograph0)
	(calibration_target instrument8 GroundStation3)
	(supports instrument9 thermograph2)
	(supports instrument9 thermograph0)
	(supports instrument9 thermograph1)
	(calibration_target instrument9 GroundStation3)
	(supports instrument10 thermograph1)
	(supports instrument10 thermograph2)
	(calibration_target instrument10 GroundStation3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star6)
	(supports instrument11 thermograph0)
	(supports instrument11 thermograph2)
	(calibration_target instrument11 GroundStation3)
	(supports instrument12 thermograph2)
	(supports instrument12 thermograph0)
	(calibration_target instrument12 GroundStation1)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet9)
	(supports instrument13 thermograph0)
	(supports instrument13 thermograph2)
	(calibration_target instrument13 GroundStation2)
	(supports instrument14 thermograph1)
	(calibration_target instrument14 GroundStation0)
	(supports instrument15 thermograph1)
	(supports instrument15 thermograph0)
	(calibration_target instrument15 GroundStation2)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation2)
	(supports instrument16 thermograph1)
	(supports instrument16 thermograph0)
	(supports instrument16 thermograph2)
	(calibration_target instrument16 GroundStation1)
	(supports instrument17 thermograph1)
	(supports instrument17 thermograph0)
	(calibration_target instrument17 GroundStation3)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star4)
	(supports instrument18 thermograph0)
	(supports instrument18 thermograph1)
	(supports instrument18 thermograph2)
	(calibration_target instrument18 GroundStation3)
	(supports instrument19 thermograph1)
	(supports instrument19 thermograph2)
	(supports instrument19 thermograph0)
	(calibration_target instrument19 GroundStation3)
	(supports instrument20 thermograph0)
	(calibration_target instrument20 GroundStation0)
	(on_board instrument18 satellite7)
	(on_board instrument19 satellite7)
	(on_board instrument20 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation2)
	(supports instrument21 thermograph0)
	(supports instrument21 thermograph2)
	(supports instrument21 thermograph1)
	(calibration_target instrument21 GroundStation0)
	(on_board instrument21 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon10)
	(supports instrument22 thermograph2)
	(supports instrument22 thermograph0)
	(supports instrument22 thermograph1)
	(calibration_target instrument22 Star4)
	(supports instrument23 thermograph0)
	(supports instrument23 thermograph1)
	(supports instrument23 thermograph2)
	(calibration_target instrument23 GroundStation2)
	(on_board instrument22 satellite9)
	(on_board instrument23 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation2)
	(supports instrument24 thermograph0)
	(calibration_target instrument24 GroundStation0)
	(supports instrument25 thermograph0)
	(supports instrument25 thermograph1)
	(calibration_target instrument25 GroundStation3)
	(supports instrument26 thermograph2)
	(calibration_target instrument26 GroundStation2)
	(on_board instrument24 satellite10)
	(on_board instrument25 satellite10)
	(on_board instrument26 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Star4)
	(supports instrument27 thermograph1)
	(supports instrument27 thermograph0)
	(supports instrument27 thermograph2)
	(calibration_target instrument27 GroundStation0)
	(supports instrument28 thermograph1)
	(supports instrument28 thermograph0)
	(supports instrument28 thermograph2)
	(calibration_target instrument28 GroundStation2)
	(on_board instrument27 satellite11)
	(on_board instrument28 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Star4)
	(supports instrument29 thermograph2)
	(supports instrument29 thermograph0)
	(calibration_target instrument29 GroundStation3)
	(on_board instrument29 satellite12)
	(power_avail satellite12)
	(pointing satellite12 Planet8)
	(supports instrument30 thermograph1)
	(supports instrument30 thermograph0)
	(calibration_target instrument30 GroundStation1)
	(supports instrument31 thermograph2)
	(calibration_target instrument31 Star4)
	(supports instrument32 thermograph1)
	(calibration_target instrument32 GroundStation2)
	(on_board instrument30 satellite13)
	(on_board instrument31 satellite13)
	(on_board instrument32 satellite13)
	(power_avail satellite13)
	(pointing satellite13 Star4)
	(supports instrument33 thermograph2)
	(calibration_target instrument33 GroundStation3)
	(supports instrument34 thermograph1)
	(supports instrument34 thermograph0)
	(calibration_target instrument34 GroundStation2)
	(supports instrument35 thermograph1)
	(supports instrument35 thermograph2)
	(calibration_target instrument35 GroundStation0)
	(on_board instrument33 satellite14)
	(on_board instrument34 satellite14)
	(on_board instrument35 satellite14)
	(power_avail satellite14)
	(pointing satellite14 Star4)
	(supports instrument36 thermograph1)
	(supports instrument36 thermograph0)
	(calibration_target instrument36 GroundStation1)
	(on_board instrument36 satellite15)
	(power_avail satellite15)
	(pointing satellite15 Planet5)
	(supports instrument37 thermograph1)
	(calibration_target instrument37 GroundStation1)
	(supports instrument38 thermograph1)
	(supports instrument38 thermograph0)
	(supports instrument38 thermograph2)
	(calibration_target instrument38 GroundStation3)
	(on_board instrument37 satellite16)
	(on_board instrument38 satellite16)
	(power_avail satellite16)
	(pointing satellite16 Planet7)
)
(:goal (and
	(pointing satellite4 Planet7)
	(pointing satellite5 GroundStation2)
	(pointing satellite7 Star6)
	(pointing satellite12 Star6)
	(pointing satellite13 GroundStation2)
	(pointing satellite14 GroundStation3)
	(have_image Planet5 thermograph1)
	(have_image Star6 thermograph2)
	(have_image Planet7 thermograph0)
	(have_image Planet8 thermograph2)
	(have_image Planet9 thermograph1)
	(have_image Phenomenon10 thermograph0)
))

)
