(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite6 - satellite
	instrument13 - instrument
	instrument14 - instrument
	satellite7 - satellite
	instrument15 - instrument
	satellite8 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite9 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite10 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	spectrograph2 - mode
	image3 - mode
	spectrograph0 - mode
	thermograph1 - mode
	Star9 - direction
	GroundStation0 - direction
	Star7 - direction
	GroundStation2 - direction
	Star4 - direction
	GroundStation3 - direction
	Star6 - direction
	Star8 - direction
	GroundStation5 - direction
	Star1 - direction
	Planet10 - direction
	Star11 - direction
	Star12 - direction
	Phenomenon13 - direction
	Phenomenon14 - direction
)
(:init
	(supports instrument0 thermograph1)
	(supports instrument0 spectrograph2)
	(supports instrument0 image3)
	(calibration_target instrument0 GroundStation3)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 Star7)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon14)
	(supports instrument1 spectrograph2)
	(calibration_target instrument1 GroundStation3)
	(calibration_target instrument1 Star4)
	(supports instrument2 thermograph1)
	(supports instrument2 spectrograph2)
	(calibration_target instrument2 Star6)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 GroundStation0)
	(calibration_target instrument3 GroundStation3)
	(calibration_target instrument3 Star1)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon14)
	(supports instrument4 spectrograph0)
	(supports instrument4 thermograph1)
	(supports instrument4 spectrograph2)
	(calibration_target instrument4 Star1)
	(supports instrument5 thermograph1)
	(calibration_target instrument5 Star6)
	(calibration_target instrument5 Star4)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon13)
	(supports instrument6 spectrograph2)
	(calibration_target instrument6 Star6)
	(supports instrument7 thermograph1)
	(supports instrument7 spectrograph2)
	(calibration_target instrument7 Star9)
	(calibration_target instrument7 Star4)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star12)
	(supports instrument8 image3)
	(supports instrument8 spectrograph0)
	(supports instrument8 thermograph1)
	(calibration_target instrument8 Star4)
	(calibration_target instrument8 Star9)
	(calibration_target instrument8 Star7)
	(supports instrument9 spectrograph2)
	(supports instrument9 image3)
	(calibration_target instrument9 Star8)
	(calibration_target instrument9 Star6)
	(supports instrument10 spectrograph0)
	(supports instrument10 spectrograph2)
	(supports instrument10 thermograph1)
	(calibration_target instrument10 GroundStation0)
	(calibration_target instrument10 GroundStation3)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star7)
	(supports instrument11 spectrograph2)
	(calibration_target instrument11 Star4)
	(calibration_target instrument11 GroundStation2)
	(supports instrument12 thermograph1)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 GroundStation3)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star4)
	(supports instrument13 image3)
	(supports instrument13 spectrograph0)
	(supports instrument13 thermograph1)
	(calibration_target instrument13 GroundStation5)
	(calibration_target instrument13 Star7)
	(calibration_target instrument13 Star6)
	(supports instrument14 spectrograph0)
	(supports instrument14 spectrograph2)
	(supports instrument14 thermograph1)
	(calibration_target instrument14 GroundStation3)
	(calibration_target instrument14 Star7)
	(on_board instrument13 satellite6)
	(on_board instrument14 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation0)
	(supports instrument15 spectrograph0)
	(supports instrument15 image3)
	(supports instrument15 thermograph1)
	(calibration_target instrument15 Star8)
	(calibration_target instrument15 GroundStation5)
	(calibration_target instrument15 Star4)
	(on_board instrument15 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation0)
	(supports instrument16 spectrograph0)
	(supports instrument16 spectrograph2)
	(supports instrument16 image3)
	(calibration_target instrument16 Star9)
	(calibration_target instrument16 GroundStation5)
	(calibration_target instrument16 GroundStation2)
	(supports instrument17 image3)
	(calibration_target instrument17 Star1)
	(calibration_target instrument17 GroundStation3)
	(calibration_target instrument17 GroundStation0)
	(on_board instrument16 satellite8)
	(on_board instrument17 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation2)
	(supports instrument18 spectrograph2)
	(supports instrument18 thermograph1)
	(calibration_target instrument18 Star6)
	(calibration_target instrument18 Star1)
	(calibration_target instrument18 Star7)
	(supports instrument19 spectrograph0)
	(supports instrument19 image3)
	(calibration_target instrument19 GroundStation2)
	(calibration_target instrument19 GroundStation5)
	(supports instrument20 thermograph1)
	(supports instrument20 spectrograph2)
	(calibration_target instrument20 GroundStation5)
	(calibration_target instrument20 Star4)
	(on_board instrument18 satellite9)
	(on_board instrument19 satellite9)
	(on_board instrument20 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation0)
	(supports instrument21 image3)
	(calibration_target instrument21 Star8)
	(calibration_target instrument21 GroundStation3)
	(calibration_target instrument21 Star1)
	(supports instrument22 thermograph1)
	(calibration_target instrument22 Star6)
	(calibration_target instrument22 Star8)
	(supports instrument23 image3)
	(calibration_target instrument23 Star1)
	(calibration_target instrument23 GroundStation5)
	(calibration_target instrument23 Star8)
	(on_board instrument21 satellite10)
	(on_board instrument22 satellite10)
	(on_board instrument23 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Star8)
)
(:goal (and
	(pointing satellite4 Star12)
	(pointing satellite8 Star11)
	(pointing satellite9 Star4)
	(pointing satellite10 Star12)
	(have_image Planet10 spectrograph2)
	(have_image Star11 spectrograph0)
	(have_image Star12 spectrograph0)
	(have_image Phenomenon13 thermograph1)
	(have_image Phenomenon14 spectrograph0)
))

)
