(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	instrument11 - instrument
	satellite5 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite6 - satellite
	instrument15 - instrument
	instrument16 - instrument
	satellite7 - satellite
	instrument17 - instrument
	satellite8 - satellite
	instrument18 - instrument
	instrument19 - instrument
	satellite9 - satellite
	instrument20 - instrument
	instrument21 - instrument
	thermograph1 - mode
	infrared0 - mode
	GroundStation11 - direction
	GroundStation12 - direction
	Star4 - direction
	GroundStation0 - direction
	GroundStation5 - direction
	GroundStation3 - direction
	Star7 - direction
	GroundStation2 - direction
	GroundStation1 - direction
	Star6 - direction
	GroundStation8 - direction
	GroundStation10 - direction
	GroundStation9 - direction
	Planet13 - direction
	Star14 - direction
	Planet15 - direction
	Planet16 - direction
	Planet17 - direction
)
(:init
	(supports instrument0 thermograph1)
	(supports instrument0 infrared0)
	(calibration_target instrument0 GroundStation1)
	(calibration_target instrument0 GroundStation10)
	(supports instrument1 infrared0)
	(supports instrument1 thermograph1)
	(calibration_target instrument1 GroundStation5)
	(calibration_target instrument1 GroundStation9)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star14)
	(supports instrument2 thermograph1)
	(supports instrument2 infrared0)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 Star4)
	(supports instrument3 infrared0)
	(calibration_target instrument3 GroundStation10)
	(calibration_target instrument3 GroundStation11)
	(calibration_target instrument3 GroundStation12)
	(supports instrument4 thermograph1)
	(supports instrument4 infrared0)
	(calibration_target instrument4 Star4)
	(calibration_target instrument4 GroundStation0)
	(calibration_target instrument4 GroundStation12)
	(calibration_target instrument4 GroundStation5)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet15)
	(supports instrument5 infrared0)
	(supports instrument5 thermograph1)
	(calibration_target instrument5 GroundStation1)
	(calibration_target instrument5 GroundStation12)
	(calibration_target instrument5 GroundStation8)
	(calibration_target instrument5 GroundStation5)
	(supports instrument6 thermograph1)
	(supports instrument6 infrared0)
	(calibration_target instrument6 GroundStation8)
	(calibration_target instrument6 GroundStation3)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation8)
	(supports instrument7 thermograph1)
	(calibration_target instrument7 GroundStation1)
	(supports instrument8 thermograph1)
	(calibration_target instrument8 GroundStation0)
	(supports instrument9 infrared0)
	(calibration_target instrument9 GroundStation12)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation5)
	(supports instrument10 infrared0)
	(calibration_target instrument10 GroundStation8)
	(supports instrument11 thermograph1)
	(calibration_target instrument11 GroundStation12)
	(calibration_target instrument11 GroundStation5)
	(calibration_target instrument11 Star4)
	(calibration_target instrument11 Star6)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation11)
	(supports instrument12 thermograph1)
	(supports instrument12 infrared0)
	(calibration_target instrument12 GroundStation9)
	(supports instrument13 thermograph1)
	(supports instrument13 infrared0)
	(calibration_target instrument13 Star4)
	(calibration_target instrument13 GroundStation5)
	(supports instrument14 infrared0)
	(calibration_target instrument14 GroundStation9)
	(calibration_target instrument14 GroundStation5)
	(calibration_target instrument14 Star6)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet16)
	(supports instrument15 infrared0)
	(supports instrument15 thermograph1)
	(calibration_target instrument15 Star4)
	(calibration_target instrument15 GroundStation2)
	(calibration_target instrument15 Star6)
	(calibration_target instrument15 GroundStation3)
	(supports instrument16 thermograph1)
	(supports instrument16 infrared0)
	(calibration_target instrument16 GroundStation0)
	(calibration_target instrument16 Star7)
	(calibration_target instrument16 GroundStation9)
	(calibration_target instrument16 GroundStation10)
	(on_board instrument15 satellite6)
	(on_board instrument16 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation8)
	(supports instrument17 infrared0)
	(supports instrument17 thermograph1)
	(calibration_target instrument17 Star7)
	(calibration_target instrument17 GroundStation3)
	(calibration_target instrument17 GroundStation5)
	(on_board instrument17 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star6)
	(supports instrument18 thermograph1)
	(calibration_target instrument18 Star7)
	(calibration_target instrument18 GroundStation1)
	(calibration_target instrument18 GroundStation10)
	(supports instrument19 infrared0)
	(supports instrument19 thermograph1)
	(calibration_target instrument19 GroundStation2)
	(on_board instrument18 satellite8)
	(on_board instrument19 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation5)
	(supports instrument20 thermograph1)
	(calibration_target instrument20 GroundStation8)
	(calibration_target instrument20 Star6)
	(calibration_target instrument20 GroundStation1)
	(supports instrument21 infrared0)
	(supports instrument21 thermograph1)
	(calibration_target instrument21 GroundStation9)
	(calibration_target instrument21 GroundStation10)
	(on_board instrument20 satellite9)
	(on_board instrument21 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation3)
)
(:goal (and
	(pointing satellite0 Planet15)
	(pointing satellite5 GroundStation2)
	(pointing satellite7 GroundStation10)
	(pointing satellite8 Planet13)
	(pointing satellite9 Star14)
	(have_image Planet13 thermograph1)
	(have_image Star14 infrared0)
	(have_image Planet15 infrared0)
	(have_image Planet16 thermograph1)
	(have_image Planet17 thermograph1)
))

)
