(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite4 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite5 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite6 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite7 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite8 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	thermograph0 - mode
	thermograph2 - mode
	thermograph4 - mode
	image5 - mode
	infrared1 - mode
	image3 - mode
	Star4 - direction
	GroundStation3 - direction
	Star1 - direction
	Star0 - direction
	GroundStation2 - direction
	Phenomenon5 - direction
	Planet6 - direction
	Star7 - direction
	Planet8 - direction
	Planet9 - direction
)
(:init
	(supports instrument0 image3)
	(supports instrument0 image5)
	(calibration_target instrument0 Star1)
	(supports instrument1 image5)
	(supports instrument1 image3)
	(supports instrument1 infrared1)
	(calibration_target instrument1 GroundStation3)
	(supports instrument2 thermograph0)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 Star1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet6)
	(supports instrument3 image5)
	(supports instrument3 thermograph0)
	(supports instrument3 image3)
	(calibration_target instrument3 Star4)
	(supports instrument4 thermograph0)
	(supports instrument4 thermograph4)
	(calibration_target instrument4 Star1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star1)
	(supports instrument5 infrared1)
	(supports instrument5 image5)
	(supports instrument5 thermograph2)
	(calibration_target instrument5 GroundStation2)
	(supports instrument6 thermograph2)
	(supports instrument6 thermograph4)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 GroundStation2)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 Star1)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star1)
	(supports instrument8 image3)
	(supports instrument8 infrared1)
	(calibration_target instrument8 GroundStation2)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 Star1)
	(supports instrument10 thermograph0)
	(supports instrument10 image5)
	(calibration_target instrument10 GroundStation2)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star1)
	(supports instrument11 image3)
	(supports instrument11 image5)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 Star0)
	(supports instrument12 thermograph2)
	(supports instrument12 image3)
	(calibration_target instrument12 GroundStation2)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet8)
	(supports instrument13 thermograph4)
	(supports instrument13 image5)
	(calibration_target instrument13 GroundStation3)
	(supports instrument14 thermograph2)
	(supports instrument14 image5)
	(supports instrument14 image3)
	(calibration_target instrument14 Star1)
	(supports instrument15 infrared1)
	(supports instrument15 image5)
	(calibration_target instrument15 GroundStation3)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet9)
	(supports instrument16 thermograph4)
	(calibration_target instrument16 GroundStation3)
	(supports instrument17 image3)
	(supports instrument17 image5)
	(calibration_target instrument17 GroundStation2)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star7)
	(supports instrument18 image3)
	(supports instrument18 thermograph4)
	(calibration_target instrument18 Star1)
	(supports instrument19 thermograph0)
	(supports instrument19 image3)
	(supports instrument19 infrared1)
	(calibration_target instrument19 GroundStation2)
	(supports instrument20 thermograph0)
	(supports instrument20 image3)
	(supports instrument20 thermograph4)
	(calibration_target instrument20 Star0)
	(on_board instrument18 satellite7)
	(on_board instrument19 satellite7)
	(on_board instrument20 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon5)
	(supports instrument21 thermograph2)
	(supports instrument21 image3)
	(supports instrument21 thermograph4)
	(calibration_target instrument21 GroundStation2)
	(supports instrument22 infrared1)
	(calibration_target instrument22 GroundStation2)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 GroundStation2)
	(on_board instrument21 satellite8)
	(on_board instrument22 satellite8)
	(on_board instrument23 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet9)
)
(:goal (and
	(pointing satellite0 Planet8)
	(pointing satellite1 GroundStation2)
	(pointing satellite6 Star7)
	(pointing satellite7 Star4)
	(have_image Phenomenon5 thermograph0)
	(have_image Phenomenon5 infrared1)
	(have_image Planet6 infrared1)
	(have_image Planet6 thermograph4)
	(have_image Star7 thermograph4)
	(have_image Star7 image5)
	(have_image Planet8 thermograph4)
	(have_image Planet8 infrared1)
	(have_image Planet9 thermograph2)
	(have_image Planet9 image5)
))

)
