(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	satellite4 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite5 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite6 - satellite
	instrument12 - instrument
	instrument13 - instrument
	satellite7 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite8 - satellite
	instrument17 - instrument
	instrument18 - instrument
	satellite9 - satellite
	instrument19 - instrument
	instrument20 - instrument
	satellite10 - satellite
	instrument21 - instrument
	instrument22 - instrument
	satellite11 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite12 - satellite
	instrument26 - instrument
	instrument27 - instrument
	satellite13 - satellite
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	image3 - mode
	spectrograph5 - mode
	infrared0 - mode
	infrared1 - mode
	spectrograph2 - mode
	thermograph4 - mode
	GroundStation0 - direction
	Star2 - direction
	Star3 - direction
	Star1 - direction
	GroundStation5 - direction
	GroundStation4 - direction
	Star6 - direction
	Phenomenon7 - direction
	Star8 - direction
	Phenomenon9 - direction
	Star10 - direction
)
(:init
	(supports instrument0 spectrograph2)
	(supports instrument0 thermograph4)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 GroundStation4)
	(supports instrument1 infrared0)
	(calibration_target instrument1 Star2)
	(calibration_target instrument1 GroundStation4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star6)
	(supports instrument2 spectrograph2)
	(supports instrument2 thermograph4)
	(supports instrument2 infrared0)
	(calibration_target instrument2 Star1)
	(calibration_target instrument2 GroundStation4)
	(supports instrument3 image3)
	(calibration_target instrument3 GroundStation0)
	(calibration_target instrument3 Star3)
	(supports instrument4 spectrograph2)
	(supports instrument4 image3)
	(calibration_target instrument4 Star2)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation5)
	(supports instrument5 infrared0)
	(supports instrument5 spectrograph2)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 Star3)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon9)
	(supports instrument6 spectrograph5)
	(supports instrument6 spectrograph2)
	(calibration_target instrument6 Star2)
	(on_board instrument6 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star1)
	(supports instrument7 spectrograph5)
	(supports instrument7 spectrograph2)
	(calibration_target instrument7 Star3)
	(calibration_target instrument7 GroundStation4)
	(supports instrument8 infrared1)
	(supports instrument8 image3)
	(calibration_target instrument8 Star2)
	(calibration_target instrument8 Star3)
	(on_board instrument7 satellite4)
	(on_board instrument8 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star6)
	(supports instrument9 spectrograph5)
	(calibration_target instrument9 Star2)
	(calibration_target instrument9 GroundStation5)
	(supports instrument10 image3)
	(supports instrument10 infrared0)
	(calibration_target instrument10 GroundStation0)
	(supports instrument11 infrared0)
	(supports instrument11 infrared1)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 GroundStation5)
	(calibration_target instrument11 GroundStation0)
	(on_board instrument9 satellite5)
	(on_board instrument10 satellite5)
	(on_board instrument11 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star6)
	(supports instrument12 spectrograph2)
	(supports instrument12 infrared1)
	(calibration_target instrument12 GroundStation5)
	(supports instrument13 spectrograph2)
	(calibration_target instrument13 Star2)
	(on_board instrument12 satellite6)
	(on_board instrument13 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon7)
	(supports instrument14 spectrograph5)
	(supports instrument14 infrared1)
	(supports instrument14 infrared0)
	(calibration_target instrument14 Star1)
	(supports instrument15 spectrograph2)
	(supports instrument15 infrared0)
	(supports instrument15 spectrograph5)
	(calibration_target instrument15 GroundStation4)
	(calibration_target instrument15 GroundStation0)
	(supports instrument16 infrared0)
	(supports instrument16 spectrograph5)
	(calibration_target instrument16 Star1)
	(calibration_target instrument16 GroundStation0)
	(on_board instrument14 satellite7)
	(on_board instrument15 satellite7)
	(on_board instrument16 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star1)
	(supports instrument17 infrared0)
	(supports instrument17 image3)
	(supports instrument17 spectrograph2)
	(calibration_target instrument17 GroundStation5)
	(supports instrument18 spectrograph2)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 GroundStation4)
	(on_board instrument17 satellite8)
	(on_board instrument18 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation5)
	(supports instrument19 spectrograph2)
	(calibration_target instrument19 GroundStation0)
	(calibration_target instrument19 Star2)
	(supports instrument20 infrared1)
	(calibration_target instrument20 GroundStation5)
	(on_board instrument19 satellite9)
	(on_board instrument20 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation4)
	(supports instrument21 infrared1)
	(calibration_target instrument21 GroundStation5)
	(calibration_target instrument21 Star3)
	(supports instrument22 thermograph4)
	(calibration_target instrument22 GroundStation5)
	(calibration_target instrument22 GroundStation0)
	(on_board instrument21 satellite10)
	(on_board instrument22 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Star10)
	(supports instrument23 infrared0)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 Star2)
	(supports instrument24 infrared1)
	(calibration_target instrument24 GroundStation0)
	(supports instrument25 thermograph4)
	(supports instrument25 spectrograph2)
	(calibration_target instrument25 GroundStation5)
	(calibration_target instrument25 Star1)
	(on_board instrument23 satellite11)
	(on_board instrument24 satellite11)
	(on_board instrument25 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Star2)
	(supports instrument26 spectrograph5)
	(supports instrument26 thermograph4)
	(supports instrument26 image3)
	(calibration_target instrument26 Star2)
	(calibration_target instrument26 GroundStation0)
	(supports instrument27 infrared1)
	(supports instrument27 thermograph4)
	(supports instrument27 spectrograph2)
	(calibration_target instrument27 Star1)
	(calibration_target instrument27 GroundStation4)
	(on_board instrument26 satellite12)
	(on_board instrument27 satellite12)
	(power_avail satellite12)
	(pointing satellite12 GroundStation4)
	(supports instrument28 spectrograph5)
	(calibration_target instrument28 Star3)
	(supports instrument29 spectrograph5)
	(supports instrument29 infrared1)
	(supports instrument29 spectrograph2)
	(calibration_target instrument29 Star1)
	(calibration_target instrument29 GroundStation5)
	(supports instrument30 image3)
	(supports instrument30 infrared1)
	(supports instrument30 thermograph4)
	(calibration_target instrument30 GroundStation4)
	(calibration_target instrument30 GroundStation5)
	(on_board instrument28 satellite13)
	(on_board instrument29 satellite13)
	(on_board instrument30 satellite13)
	(power_avail satellite13)
	(pointing satellite13 Star6)
)
(:goal (and
	(pointing satellite4 Star8)
	(pointing satellite8 Star8)
	(pointing satellite9 Star10)
	(pointing satellite10 Star10)
	(pointing satellite11 Star8)
	(pointing satellite13 GroundStation4)
	(have_image Star6 image3)
	(have_image Phenomenon7 spectrograph5)
	(have_image Phenomenon7 image3)
	(have_image Star8 infrared1)
	(have_image Phenomenon9 infrared0)
	(have_image Phenomenon9 image3)
	(have_image Star10 thermograph4)
	(have_image Star10 spectrograph5)
))

)
