(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite4 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite5 - satellite
	instrument13 - instrument
	instrument14 - instrument
	satellite6 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite7 - satellite
	instrument18 - instrument
	instrument19 - instrument
	satellite8 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite9 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	spectrograph1 - mode
	thermograph0 - mode
	thermograph4 - mode
	infrared3 - mode
	infrared2 - mode
	GroundStation4 - direction
	Star3 - direction
	GroundStation1 - direction
	GroundStation2 - direction
	GroundStation5 - direction
	GroundStation0 - direction
	GroundStation6 - direction
	Star7 - direction
	Phenomenon8 - direction
	Phenomenon9 - direction
	Phenomenon10 - direction
	Phenomenon11 - direction
	Star12 - direction
)
(:init
	(supports instrument0 thermograph0)
	(supports instrument0 spectrograph1)
	(supports instrument0 infrared3)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 infrared3)
	(supports instrument1 thermograph0)
	(calibration_target instrument1 GroundStation6)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon8)
	(supports instrument2 spectrograph1)
	(supports instrument2 thermograph4)
	(supports instrument2 infrared3)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 GroundStation6)
	(supports instrument3 spectrograph1)
	(supports instrument3 infrared2)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 GroundStation5)
	(supports instrument4 thermograph0)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 GroundStation4)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation0)
	(supports instrument5 spectrograph1)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 GroundStation2)
	(supports instrument6 spectrograph1)
	(supports instrument6 thermograph4)
	(supports instrument6 infrared3)
	(calibration_target instrument6 Star3)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 GroundStation2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star7)
	(supports instrument8 spectrograph1)
	(supports instrument8 thermograph0)
	(supports instrument8 infrared2)
	(calibration_target instrument8 GroundStation2)
	(calibration_target instrument8 Star3)
	(supports instrument9 spectrograph1)
	(calibration_target instrument9 GroundStation2)
	(supports instrument10 infrared3)
	(supports instrument10 thermograph4)
	(supports instrument10 spectrograph1)
	(calibration_target instrument10 GroundStation6)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon9)
	(supports instrument11 spectrograph1)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 GroundStation1)
	(supports instrument12 spectrograph1)
	(supports instrument12 thermograph0)
	(calibration_target instrument12 GroundStation0)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation1)
	(supports instrument13 spectrograph1)
	(supports instrument13 thermograph0)
	(supports instrument13 infrared2)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 GroundStation2)
	(supports instrument14 thermograph0)
	(calibration_target instrument14 GroundStation6)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star12)
	(supports instrument15 infrared3)
	(supports instrument15 thermograph4)
	(calibration_target instrument15 GroundStation5)
	(supports instrument16 infrared3)
	(supports instrument16 spectrograph1)
	(supports instrument16 thermograph0)
	(calibration_target instrument16 GroundStation1)
	(calibration_target instrument16 GroundStation2)
	(supports instrument17 thermograph0)
	(supports instrument17 infrared3)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 GroundStation6)
	(on_board instrument15 satellite6)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon10)
	(supports instrument18 thermograph4)
	(supports instrument18 spectrograph1)
	(supports instrument18 thermograph0)
	(calibration_target instrument18 GroundStation2)
	(supports instrument19 thermograph0)
	(supports instrument19 thermograph4)
	(supports instrument19 infrared2)
	(calibration_target instrument19 GroundStation5)
	(on_board instrument18 satellite7)
	(on_board instrument19 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon9)
	(supports instrument20 thermograph0)
	(supports instrument20 thermograph4)
	(calibration_target instrument20 GroundStation1)
	(supports instrument21 infrared3)
	(supports instrument21 infrared2)
	(supports instrument21 thermograph4)
	(calibration_target instrument21 GroundStation5)
	(calibration_target instrument21 GroundStation2)
	(supports instrument22 infrared2)
	(calibration_target instrument22 GroundStation5)
	(on_board instrument20 satellite8)
	(on_board instrument21 satellite8)
	(on_board instrument22 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon10)
	(supports instrument23 infrared3)
	(supports instrument23 thermograph0)
	(supports instrument23 infrared2)
	(calibration_target instrument23 GroundStation0)
	(supports instrument24 thermograph0)
	(calibration_target instrument24 GroundStation0)
	(calibration_target instrument24 GroundStation5)
	(supports instrument25 thermograph0)
	(supports instrument25 spectrograph1)
	(supports instrument25 infrared3)
	(calibration_target instrument25 GroundStation6)
	(on_board instrument23 satellite9)
	(on_board instrument24 satellite9)
	(on_board instrument25 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation4)
)
(:goal (and
	(pointing satellite0 GroundStation6)
	(pointing satellite2 GroundStation4)
	(pointing satellite6 GroundStation0)
	(have_image Star7 infrared3)
	(have_image Phenomenon8 thermograph0)
	(have_image Phenomenon9 spectrograph1)
	(have_image Phenomenon10 spectrograph1)
	(have_image Phenomenon11 infrared3)
	(have_image Star12 infrared2)
))

)
