(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	satellite6 - satellite
	instrument12 - instrument
	satellite7 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite8 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite9 - satellite
	instrument18 - instrument
	satellite10 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite11 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite12 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	spectrograph2 - mode
	image3 - mode
	infrared1 - mode
	spectrograph0 - mode
	GroundStation1 - direction
	GroundStation5 - direction
	Star3 - direction
	Star2 - direction
	GroundStation4 - direction
	Star0 - direction
	Planet6 - direction
	Phenomenon7 - direction
	Phenomenon8 - direction
	Star9 - direction
	Star10 - direction
	Phenomenon11 - direction
)
(:init
	(supports instrument0 infrared1)
	(calibration_target instrument0 GroundStation5)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon7)
	(supports instrument1 image3)
	(supports instrument1 spectrograph2)
	(supports instrument1 infrared1)
	(calibration_target instrument1 GroundStation5)
	(supports instrument2 infrared1)
	(supports instrument2 spectrograph0)
	(supports instrument2 spectrograph2)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 GroundStation4)
	(supports instrument3 spectrograph0)
	(supports instrument3 image3)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 Star3)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon7)
	(supports instrument4 spectrograph0)
	(supports instrument4 infrared1)
	(calibration_target instrument4 Star2)
	(supports instrument5 spectrograph2)
	(calibration_target instrument5 GroundStation4)
	(calibration_target instrument5 GroundStation5)
	(supports instrument6 image3)
	(calibration_target instrument6 Star2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star3)
	(supports instrument7 spectrograph2)
	(supports instrument7 infrared1)
	(calibration_target instrument7 Star3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star3)
	(supports instrument8 infrared1)
	(supports instrument8 spectrograph0)
	(calibration_target instrument8 GroundStation5)
	(calibration_target instrument8 Star2)
	(supports instrument9 spectrograph2)
	(calibration_target instrument9 Star3)
	(supports instrument10 infrared1)
	(supports instrument10 image3)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 GroundStation5)
	(calibration_target instrument10 GroundStation4)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet6)
	(supports instrument11 infrared1)
	(supports instrument11 spectrograph2)
	(supports instrument11 spectrograph0)
	(calibration_target instrument11 Star2)
	(on_board instrument11 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon7)
	(supports instrument12 infrared1)
	(calibration_target instrument12 Star3)
	(calibration_target instrument12 GroundStation5)
	(on_board instrument12 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet6)
	(supports instrument13 spectrograph0)
	(calibration_target instrument13 GroundStation5)
	(supports instrument14 spectrograph2)
	(supports instrument14 infrared1)
	(supports instrument14 image3)
	(calibration_target instrument14 Star0)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 Star2)
	(calibration_target instrument15 GroundStation4)
	(on_board instrument13 satellite7)
	(on_board instrument14 satellite7)
	(on_board instrument15 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation5)
	(supports instrument16 spectrograph0)
	(supports instrument16 spectrograph2)
	(calibration_target instrument16 GroundStation1)
	(calibration_target instrument16 Star2)
	(supports instrument17 infrared1)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 GroundStation1)
	(calibration_target instrument17 Star3)
	(on_board instrument16 satellite8)
	(on_board instrument17 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star3)
	(supports instrument18 spectrograph0)
	(supports instrument18 image3)
	(supports instrument18 infrared1)
	(calibration_target instrument18 Star3)
	(on_board instrument18 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star0)
	(supports instrument19 infrared1)
	(supports instrument19 image3)
	(supports instrument19 spectrograph2)
	(calibration_target instrument19 Star0)
	(supports instrument20 spectrograph2)
	(supports instrument20 spectrograph0)
	(calibration_target instrument20 GroundStation1)
	(calibration_target instrument20 GroundStation4)
	(supports instrument21 spectrograph2)
	(supports instrument21 image3)
	(supports instrument21 infrared1)
	(calibration_target instrument21 GroundStation5)
	(on_board instrument19 satellite10)
	(on_board instrument20 satellite10)
	(on_board instrument21 satellite10)
	(power_avail satellite10)
	(pointing satellite10 GroundStation5)
	(supports instrument22 infrared1)
	(supports instrument22 image3)
	(supports instrument22 spectrograph0)
	(calibration_target instrument22 GroundStation4)
	(calibration_target instrument22 Star0)
	(supports instrument23 spectrograph0)
	(supports instrument23 infrared1)
	(supports instrument23 image3)
	(calibration_target instrument23 Star3)
	(calibration_target instrument23 GroundStation5)
	(supports instrument24 spectrograph2)
	(supports instrument24 image3)
	(calibration_target instrument24 Star0)
	(calibration_target instrument24 Star3)
	(on_board instrument22 satellite11)
	(on_board instrument23 satellite11)
	(on_board instrument24 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Phenomenon7)
	(supports instrument25 spectrograph2)
	(supports instrument25 image3)
	(calibration_target instrument25 GroundStation4)
	(supports instrument26 spectrograph0)
	(supports instrument26 infrared1)
	(supports instrument26 spectrograph2)
	(calibration_target instrument26 GroundStation4)
	(calibration_target instrument26 Star2)
	(supports instrument27 spectrograph0)
	(supports instrument27 image3)
	(supports instrument27 spectrograph2)
	(calibration_target instrument27 Star0)
	(on_board instrument25 satellite12)
	(on_board instrument26 satellite12)
	(on_board instrument27 satellite12)
	(power_avail satellite12)
	(pointing satellite12 Star9)
)
(:goal (and
	(pointing satellite4 Star10)
	(pointing satellite7 Phenomenon11)
	(pointing satellite8 Phenomenon11)
	(pointing satellite12 GroundStation4)
	(have_image Planet6 spectrograph2)
	(have_image Phenomenon7 infrared1)
	(have_image Phenomenon8 spectrograph0)
	(have_image Star9 infrared1)
	(have_image Star10 spectrograph0)
	(have_image Phenomenon11 spectrograph2)
))

)
