(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite5 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite6 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite7 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	thermograph3 - mode
	thermograph1 - mode
	infrared4 - mode
	image0 - mode
	image5 - mode
	image6 - mode
	spectrograph2 - mode
	Star1 - direction
	Star0 - direction
	Star2 - direction
	GroundStation3 - direction
	GroundStation6 - direction
	GroundStation5 - direction
	Star4 - direction
	Star7 - direction
	Phenomenon8 - direction
	Phenomenon9 - direction
	Star10 - direction
	Star11 - direction
	Planet12 - direction
	Phenomenon13 - direction
)
(:init
	(supports instrument0 image5)
	(supports instrument0 thermograph3)
	(calibration_target instrument0 Star4)
	(calibration_target instrument0 Star0)
	(supports instrument1 infrared4)
	(calibration_target instrument1 GroundStation5)
	(calibration_target instrument1 GroundStation3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon9)
	(supports instrument2 infrared4)
	(supports instrument2 image5)
	(supports instrument2 image6)
	(calibration_target instrument2 GroundStation5)
	(calibration_target instrument2 Star4)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star2)
	(supports instrument3 thermograph3)
	(supports instrument3 infrared4)
	(calibration_target instrument3 GroundStation5)
	(supports instrument4 thermograph3)
	(supports instrument4 image5)
	(calibration_target instrument4 Star4)
	(calibration_target instrument4 GroundStation5)
	(supports instrument5 image5)
	(supports instrument5 infrared4)
	(supports instrument5 thermograph3)
	(calibration_target instrument5 Star0)
	(calibration_target instrument5 Star4)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument6 thermograph3)
	(supports instrument6 thermograph1)
	(supports instrument6 infrared4)
	(calibration_target instrument6 GroundStation6)
	(calibration_target instrument6 Star1)
	(supports instrument7 thermograph1)
	(supports instrument7 thermograph3)
	(supports instrument7 image5)
	(calibration_target instrument7 Star1)
	(calibration_target instrument7 Star0)
	(supports instrument8 infrared4)
	(supports instrument8 thermograph1)
	(calibration_target instrument8 GroundStation3)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star0)
	(supports instrument9 image6)
	(supports instrument9 spectrograph2)
	(supports instrument9 image5)
	(calibration_target instrument9 Star0)
	(supports instrument10 image6)
	(supports instrument10 thermograph3)
	(calibration_target instrument10 Star0)
	(supports instrument11 spectrograph2)
	(supports instrument11 image5)
	(supports instrument11 infrared4)
	(calibration_target instrument11 GroundStation5)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon8)
	(supports instrument12 infrared4)
	(supports instrument12 image5)
	(calibration_target instrument12 Star4)
	(supports instrument13 spectrograph2)
	(supports instrument13 image0)
	(calibration_target instrument13 Star2)
	(supports instrument14 thermograph3)
	(calibration_target instrument14 GroundStation6)
	(calibration_target instrument14 GroundStation3)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star11)
	(supports instrument15 image5)
	(supports instrument15 thermograph1)
	(calibration_target instrument15 GroundStation5)
	(supports instrument16 image5)
	(supports instrument16 thermograph3)
	(supports instrument16 image6)
	(calibration_target instrument16 Star4)
	(calibration_target instrument16 GroundStation6)
	(supports instrument17 image6)
	(supports instrument17 thermograph3)
	(supports instrument17 image5)
	(calibration_target instrument17 Star4)
	(on_board instrument15 satellite6)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon8)
	(supports instrument18 thermograph3)
	(calibration_target instrument18 GroundStation5)
	(supports instrument19 thermograph3)
	(supports instrument19 image0)
	(calibration_target instrument19 Star4)
	(supports instrument20 image0)
	(supports instrument20 spectrograph2)
	(calibration_target instrument20 Star4)
	(on_board instrument18 satellite7)
	(on_board instrument19 satellite7)
	(on_board instrument20 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation5)
)
(:goal (and
	(pointing satellite2 Star4)
	(pointing satellite4 Star7)
	(pointing satellite5 Star1)
	(pointing satellite6 Star7)
	(have_image Star7 image0)
	(have_image Phenomenon8 image6)
	(have_image Phenomenon8 image0)
	(have_image Phenomenon9 image5)
	(have_image Phenomenon9 thermograph1)
	(have_image Star10 thermograph1)
	(have_image Star11 image0)
	(have_image Planet12 thermograph1)
	(have_image Phenomenon13 thermograph1)
	(have_image Phenomenon13 spectrograph2)
))

)
