(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite6 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite7 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite8 - satellite
	instrument18 - instrument
	instrument19 - instrument
	satellite9 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite10 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	infrared1 - mode
	image2 - mode
	infrared3 - mode
	infrared0 - mode
	GroundStation4 - direction
	Star7 - direction
	Star1 - direction
	GroundStation3 - direction
	Star6 - direction
	GroundStation5 - direction
	Star0 - direction
	GroundStation2 - direction
	Star8 - direction
	Star9 - direction
	Star10 - direction
	Star11 - direction
	Star12 - direction
	Phenomenon13 - direction
	Phenomenon14 - direction
	Planet15 - direction
)
(:init
	(supports instrument0 infrared1)
	(supports instrument0 infrared0)
	(supports instrument0 infrared3)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 infrared0)
	(calibration_target instrument1 GroundStation4)
	(calibration_target instrument1 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet15)
	(supports instrument2 infrared3)
	(supports instrument2 image2)
	(calibration_target instrument2 GroundStation3)
	(supports instrument3 infrared1)
	(supports instrument3 image2)
	(calibration_target instrument3 GroundStation3)
	(calibration_target instrument3 GroundStation4)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation2)
	(supports instrument4 infrared3)
	(calibration_target instrument4 Star6)
	(calibration_target instrument4 GroundStation5)
	(supports instrument5 infrared1)
	(supports instrument5 infrared3)
	(supports instrument5 image2)
	(calibration_target instrument5 GroundStation2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star7)
	(supports instrument6 infrared1)
	(supports instrument6 infrared0)
	(calibration_target instrument6 GroundStation4)
	(supports instrument7 infrared3)
	(supports instrument7 image2)
	(calibration_target instrument7 GroundStation3)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star6)
	(supports instrument8 infrared0)
	(supports instrument8 infrared3)
	(supports instrument8 infrared1)
	(calibration_target instrument8 GroundStation3)
	(calibration_target instrument8 Star1)
	(supports instrument9 infrared1)
	(supports instrument9 infrared3)
	(calibration_target instrument9 Star6)
	(supports instrument10 infrared1)
	(supports instrument10 image2)
	(calibration_target instrument10 Star0)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation2)
	(supports instrument11 infrared1)
	(supports instrument11 infrared0)
	(calibration_target instrument11 Star0)
	(supports instrument12 infrared0)
	(supports instrument12 infrared1)
	(calibration_target instrument12 GroundStation2)
	(calibration_target instrument12 Star7)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star1)
	(supports instrument13 infrared3)
	(calibration_target instrument13 Star6)
	(supports instrument14 infrared3)
	(supports instrument14 image2)
	(supports instrument14 infrared1)
	(calibration_target instrument14 GroundStation3)
	(supports instrument15 infrared3)
	(supports instrument15 image2)
	(calibration_target instrument15 Star1)
	(on_board instrument13 satellite6)
	(on_board instrument14 satellite6)
	(on_board instrument15 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star11)
	(supports instrument16 infrared3)
	(supports instrument16 infrared0)
	(supports instrument16 image2)
	(calibration_target instrument16 GroundStation5)
	(calibration_target instrument16 Star1)
	(supports instrument17 infrared3)
	(supports instrument17 infrared0)
	(calibration_target instrument17 Star1)
	(on_board instrument16 satellite7)
	(on_board instrument17 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation5)
	(supports instrument18 infrared3)
	(supports instrument18 image2)
	(calibration_target instrument18 GroundStation3)
	(supports instrument19 infrared0)
	(supports instrument19 infrared1)
	(supports instrument19 infrared3)
	(calibration_target instrument19 GroundStation2)
	(on_board instrument18 satellite8)
	(on_board instrument19 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star9)
	(supports instrument20 image2)
	(supports instrument20 infrared0)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 GroundStation3)
	(supports instrument21 infrared3)
	(supports instrument21 image2)
	(supports instrument21 infrared1)
	(calibration_target instrument21 Star6)
	(calibration_target instrument21 GroundStation3)
	(supports instrument22 infrared0)
	(supports instrument22 image2)
	(calibration_target instrument22 GroundStation5)
	(on_board instrument20 satellite9)
	(on_board instrument21 satellite9)
	(on_board instrument22 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star6)
	(supports instrument23 infrared3)
	(supports instrument23 infrared1)
	(supports instrument23 image2)
	(calibration_target instrument23 Star0)
	(supports instrument24 image2)
	(calibration_target instrument24 GroundStation2)
	(supports instrument25 infrared1)
	(supports instrument25 image2)
	(supports instrument25 infrared3)
	(calibration_target instrument25 GroundStation2)
	(on_board instrument23 satellite10)
	(on_board instrument24 satellite10)
	(on_board instrument25 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Star12)
)
(:goal (and
	(pointing satellite4 Planet15)
	(pointing satellite5 Star11)
	(pointing satellite8 Star7)
	(have_image Star8 infrared1)
	(have_image Star9 infrared3)
	(have_image Star10 infrared1)
	(have_image Star11 infrared3)
	(have_image Star12 infrared1)
	(have_image Phenomenon13 image2)
	(have_image Phenomenon14 infrared3)
	(have_image Planet15 infrared3)
))

)
