(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite5 - satellite
	instrument15 - instrument
	satellite6 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite7 - satellite
	instrument19 - instrument
	satellite8 - satellite
	instrument20 - instrument
	instrument21 - instrument
	satellite9 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite10 - satellite
	instrument25 - instrument
	instrument26 - instrument
	satellite11 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite12 - satellite
	instrument30 - instrument
	spectrograph0 - mode
	infrared1 - mode
	GroundStation1 - direction
	GroundStation6 - direction
	Star3 - direction
	GroundStation5 - direction
	GroundStation2 - direction
	Star0 - direction
	GroundStation4 - direction
	Planet7 - direction
	Phenomenon8 - direction
	Planet9 - direction
	Phenomenon10 - direction
	Planet11 - direction
	Planet12 - direction
	Planet13 - direction
	Star14 - direction
)
(:init
	(supports instrument0 spectrograph0)
	(supports instrument0 infrared1)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 GroundStation5)
	(supports instrument1 spectrograph0)
	(calibration_target instrument1 GroundStation5)
	(calibration_target instrument1 Star3)
	(supports instrument2 spectrograph0)
	(supports instrument2 infrared1)
	(calibration_target instrument2 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon8)
	(supports instrument3 infrared1)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 GroundStation5)
	(supports instrument4 spectrograph0)
	(supports instrument4 infrared1)
	(calibration_target instrument4 GroundStation6)
	(supports instrument5 infrared1)
	(supports instrument5 spectrograph0)
	(calibration_target instrument5 GroundStation2)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation1)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 Star3)
	(supports instrument7 infrared1)
	(calibration_target instrument7 GroundStation2)
	(supports instrument8 infrared1)
	(calibration_target instrument8 GroundStation1)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star0)
	(supports instrument9 infrared1)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 GroundStation1)
	(calibration_target instrument9 GroundStation6)
	(supports instrument10 infrared1)
	(supports instrument10 spectrograph0)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 GroundStation2)
	(supports instrument11 spectrograph0)
	(supports instrument11 infrared1)
	(calibration_target instrument11 GroundStation4)
	(calibration_target instrument11 Star0)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet12)
	(supports instrument12 infrared1)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 GroundStation4)
	(supports instrument13 infrared1)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 GroundStation5)
	(supports instrument14 spectrograph0)
	(supports instrument14 infrared1)
	(calibration_target instrument14 GroundStation4)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet12)
	(supports instrument15 infrared1)
	(supports instrument15 spectrograph0)
	(calibration_target instrument15 Star3)
	(on_board instrument15 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation5)
	(supports instrument16 infrared1)
	(calibration_target instrument16 Star0)
	(supports instrument17 infrared1)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 GroundStation2)
	(supports instrument18 infrared1)
	(supports instrument18 spectrograph0)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 Star0)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(on_board instrument18 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star14)
	(supports instrument19 spectrograph0)
	(supports instrument19 infrared1)
	(calibration_target instrument19 GroundStation5)
	(calibration_target instrument19 GroundStation2)
	(on_board instrument19 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet11)
	(supports instrument20 spectrograph0)
	(calibration_target instrument20 Star3)
	(supports instrument21 infrared1)
	(supports instrument21 spectrograph0)
	(calibration_target instrument21 GroundStation4)
	(calibration_target instrument21 Star3)
	(on_board instrument20 satellite8)
	(on_board instrument21 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star0)
	(supports instrument22 spectrograph0)
	(calibration_target instrument22 Star3)
	(calibration_target instrument22 GroundStation5)
	(supports instrument23 spectrograph0)
	(supports instrument23 infrared1)
	(calibration_target instrument23 Star3)
	(supports instrument24 spectrograph0)
	(supports instrument24 infrared1)
	(calibration_target instrument24 GroundStation6)
	(calibration_target instrument24 Star3)
	(on_board instrument22 satellite9)
	(on_board instrument23 satellite9)
	(on_board instrument24 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet9)
	(supports instrument25 infrared1)
	(calibration_target instrument25 Star0)
	(calibration_target instrument25 GroundStation6)
	(supports instrument26 spectrograph0)
	(supports instrument26 infrared1)
	(calibration_target instrument26 GroundStation2)
	(on_board instrument25 satellite10)
	(on_board instrument26 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Planet13)
	(supports instrument27 spectrograph0)
	(calibration_target instrument27 Star3)
	(supports instrument28 spectrograph0)
	(calibration_target instrument28 GroundStation5)
	(supports instrument29 infrared1)
	(supports instrument29 spectrograph0)
	(calibration_target instrument29 GroundStation2)
	(on_board instrument27 satellite11)
	(on_board instrument28 satellite11)
	(on_board instrument29 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Phenomenon8)
	(supports instrument30 spectrograph0)
	(supports instrument30 infrared1)
	(calibration_target instrument30 GroundStation4)
	(calibration_target instrument30 Star0)
	(on_board instrument30 satellite12)
	(power_avail satellite12)
	(pointing satellite12 Planet11)
)
(:goal (and
	(pointing satellite0 Planet13)
	(pointing satellite3 Planet11)
	(pointing satellite6 Phenomenon10)
	(pointing satellite7 GroundStation6)
	(pointing satellite10 GroundStation5)
	(have_image Planet7 spectrograph0)
	(have_image Phenomenon8 infrared1)
	(have_image Planet9 spectrograph0)
	(have_image Phenomenon10 spectrograph0)
	(have_image Planet11 spectrograph0)
	(have_image Planet12 spectrograph0)
	(have_image Planet13 spectrograph0)
	(have_image Star14 spectrograph0)
))

)
