(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	satellite5 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite6 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite7 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite8 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite9 - satellite
	instrument19 - instrument
	satellite10 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite11 - satellite
	instrument23 - instrument
	instrument24 - instrument
	infrared0 - mode
	infrared1 - mode
	Star5 - direction
	GroundStation2 - direction
	GroundStation3 - direction
	Star8 - direction
	GroundStation4 - direction
	GroundStation6 - direction
	GroundStation1 - direction
	Star0 - direction
	GroundStation7 - direction
	Phenomenon9 - direction
	Planet10 - direction
	Planet11 - direction
	Planet12 - direction
	Star13 - direction
	Phenomenon14 - direction
)
(:init
	(supports instrument0 infrared1)
	(calibration_target instrument0 Star5)
	(calibration_target instrument0 GroundStation6)
	(calibration_target instrument0 GroundStation4)
	(supports instrument1 infrared0)
	(supports instrument1 infrared1)
	(calibration_target instrument1 GroundStation2)
	(calibration_target instrument1 Star0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation7)
	(supports instrument2 infrared1)
	(supports instrument2 infrared0)
	(calibration_target instrument2 GroundStation1)
	(calibration_target instrument2 GroundStation3)
	(calibration_target instrument2 GroundStation6)
	(supports instrument3 infrared0)
	(supports instrument3 infrared1)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 GroundStation7)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star13)
	(supports instrument4 infrared0)
	(supports instrument4 infrared1)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 GroundStation3)
	(supports instrument5 infrared1)
	(calibration_target instrument5 GroundStation2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation3)
	(supports instrument6 infrared1)
	(supports instrument6 infrared0)
	(calibration_target instrument6 GroundStation2)
	(calibration_target instrument6 GroundStation1)
	(supports instrument7 infrared1)
	(supports instrument7 infrared0)
	(calibration_target instrument7 GroundStation1)
	(calibration_target instrument7 Star0)
	(calibration_target instrument7 GroundStation4)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation4)
	(supports instrument8 infrared0)
	(supports instrument8 infrared1)
	(calibration_target instrument8 GroundStation2)
	(on_board instrument8 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon9)
	(supports instrument9 infrared1)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 GroundStation1)
	(supports instrument10 infrared1)
	(calibration_target instrument10 Star5)
	(calibration_target instrument10 GroundStation4)
	(on_board instrument9 satellite5)
	(on_board instrument10 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star5)
	(supports instrument11 infrared1)
	(supports instrument11 infrared0)
	(calibration_target instrument11 Star8)
	(calibration_target instrument11 GroundStation3)
	(supports instrument12 infrared1)
	(supports instrument12 infrared0)
	(calibration_target instrument12 GroundStation7)
	(calibration_target instrument12 Star0)
	(on_board instrument11 satellite6)
	(on_board instrument12 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation4)
	(supports instrument13 infrared1)
	(calibration_target instrument13 GroundStation1)
	(calibration_target instrument13 Star8)
	(calibration_target instrument13 GroundStation6)
	(supports instrument14 infrared0)
	(supports instrument14 infrared1)
	(calibration_target instrument14 Star0)
	(calibration_target instrument14 GroundStation3)
	(supports instrument15 infrared0)
	(calibration_target instrument15 GroundStation2)
	(calibration_target instrument15 GroundStation3)
	(on_board instrument13 satellite7)
	(on_board instrument14 satellite7)
	(on_board instrument15 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet12)
	(supports instrument16 infrared1)
	(supports instrument16 infrared0)
	(calibration_target instrument16 GroundStation3)
	(calibration_target instrument16 GroundStation1)
	(calibration_target instrument16 Star5)
	(supports instrument17 infrared1)
	(calibration_target instrument17 Star5)
	(calibration_target instrument17 GroundStation6)
	(calibration_target instrument17 Star8)
	(supports instrument18 infrared0)
	(calibration_target instrument18 GroundStation1)
	(calibration_target instrument18 Star8)
	(calibration_target instrument18 GroundStation2)
	(on_board instrument16 satellite8)
	(on_board instrument17 satellite8)
	(on_board instrument18 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star13)
	(supports instrument19 infrared0)
	(calibration_target instrument19 GroundStation4)
	(on_board instrument19 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon9)
	(supports instrument20 infrared0)
	(supports instrument20 infrared1)
	(calibration_target instrument20 GroundStation3)
	(supports instrument21 infrared1)
	(supports instrument21 infrared0)
	(calibration_target instrument21 GroundStation4)
	(calibration_target instrument21 Star8)
	(calibration_target instrument21 GroundStation6)
	(supports instrument22 infrared0)
	(calibration_target instrument22 GroundStation1)
	(calibration_target instrument22 GroundStation6)
	(on_board instrument20 satellite10)
	(on_board instrument21 satellite10)
	(on_board instrument22 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Planet10)
	(supports instrument23 infrared0)
	(calibration_target instrument23 Star0)
	(supports instrument24 infrared0)
	(supports instrument24 infrared1)
	(calibration_target instrument24 GroundStation7)
	(calibration_target instrument24 Star0)
	(on_board instrument23 satellite11)
	(on_board instrument24 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Planet12)
)
(:goal (and
	(pointing satellite1 Star8)
	(pointing satellite4 GroundStation1)
	(pointing satellite5 Planet11)
	(pointing satellite6 GroundStation4)
	(pointing satellite9 Star0)
	(pointing satellite10 GroundStation2)
	(pointing satellite11 Phenomenon14)
	(have_image Phenomenon9 infrared1)
	(have_image Planet10 infrared0)
	(have_image Planet11 infrared1)
	(have_image Planet12 infrared0)
	(have_image Star13 infrared0)
	(have_image Phenomenon14 infrared0)
))

)
