(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	satellite2 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite3 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite4 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite5 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite6 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite7 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite8 - satellite
	instrument19 - instrument
	satellite9 - satellite
	instrument20 - instrument
	instrument21 - instrument
	satellite10 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	image6 - mode
	image1 - mode
	spectrograph4 - mode
	infrared0 - mode
	infrared2 - mode
	spectrograph3 - mode
	spectrograph5 - mode
	GroundStation2 - direction
	GroundStation5 - direction
	Star3 - direction
	GroundStation4 - direction
	Star1 - direction
	Star0 - direction
	Phenomenon6 - direction
	Phenomenon7 - direction
	Phenomenon8 - direction
	Phenomenon9 - direction
	Planet10 - direction
	Planet11 - direction
)
(:init
	(supports instrument0 spectrograph5)
	(calibration_target instrument0 GroundStation4)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet10)
	(supports instrument1 spectrograph5)
	(supports instrument1 spectrograph3)
	(supports instrument1 image6)
	(calibration_target instrument1 GroundStation4)
	(on_board instrument1 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon7)
	(supports instrument2 spectrograph5)
	(supports instrument2 spectrograph4)
	(supports instrument2 image1)
	(calibration_target instrument2 GroundStation2)
	(supports instrument3 infrared2)
	(calibration_target instrument3 Star1)
	(calibration_target instrument3 GroundStation5)
	(supports instrument4 image1)
	(calibration_target instrument4 Star1)
	(calibration_target instrument4 GroundStation4)
	(on_board instrument2 satellite2)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon6)
	(supports instrument5 spectrograph3)
	(calibration_target instrument5 Star0)
	(supports instrument6 spectrograph5)
	(supports instrument6 infrared2)
	(calibration_target instrument6 GroundStation2)
	(on_board instrument5 satellite3)
	(on_board instrument6 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon8)
	(supports instrument7 spectrograph3)
	(supports instrument7 spectrograph5)
	(calibration_target instrument7 Star3)
	(supports instrument8 infrared2)
	(supports instrument8 spectrograph5)
	(supports instrument8 spectrograph3)
	(calibration_target instrument8 Star3)
	(supports instrument9 image6)
	(supports instrument9 spectrograph5)
	(calibration_target instrument9 Star0)
	(on_board instrument7 satellite4)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star0)
	(supports instrument10 infrared2)
	(supports instrument10 infrared0)
	(supports instrument10 spectrograph3)
	(calibration_target instrument10 GroundStation2)
	(calibration_target instrument10 GroundStation5)
	(supports instrument11 spectrograph5)
	(calibration_target instrument11 GroundStation2)
	(supports instrument12 spectrograph4)
	(supports instrument12 spectrograph5)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star1)
	(on_board instrument10 satellite5)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon6)
	(supports instrument13 spectrograph4)
	(calibration_target instrument13 GroundStation2)
	(supports instrument14 image6)
	(supports instrument14 infrared2)
	(supports instrument14 image1)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 GroundStation5)
	(supports instrument15 spectrograph3)
	(calibration_target instrument15 Star1)
	(calibration_target instrument15 Star3)
	(on_board instrument13 satellite6)
	(on_board instrument14 satellite6)
	(on_board instrument15 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet10)
	(supports instrument16 infrared2)
	(calibration_target instrument16 Star0)
	(calibration_target instrument16 GroundStation5)
	(supports instrument17 infrared0)
	(supports instrument17 spectrograph5)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 GroundStation5)
	(supports instrument18 spectrograph5)
	(supports instrument18 spectrograph3)
	(calibration_target instrument18 GroundStation5)
	(calibration_target instrument18 GroundStation4)
	(on_board instrument16 satellite7)
	(on_board instrument17 satellite7)
	(on_board instrument18 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star0)
	(supports instrument19 spectrograph5)
	(supports instrument19 infrared0)
	(calibration_target instrument19 Star3)
	(on_board instrument19 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet10)
	(supports instrument20 infrared0)
	(supports instrument20 spectrograph3)
	(supports instrument20 image1)
	(calibration_target instrument20 Star0)
	(calibration_target instrument20 Star3)
	(supports instrument21 infrared0)
	(supports instrument21 spectrograph3)
	(calibration_target instrument21 GroundStation5)
	(on_board instrument20 satellite9)
	(on_board instrument21 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation2)
	(supports instrument22 image1)
	(supports instrument22 spectrograph4)
	(calibration_target instrument22 Star1)
	(calibration_target instrument22 Star3)
	(supports instrument23 spectrograph5)
	(supports instrument23 infrared0)
	(supports instrument23 spectrograph3)
	(calibration_target instrument23 GroundStation4)
	(calibration_target instrument23 Star1)
	(supports instrument24 spectrograph4)
	(calibration_target instrument24 Star0)
	(calibration_target instrument24 Star1)
	(on_board instrument22 satellite10)
	(on_board instrument23 satellite10)
	(on_board instrument24 satellite10)
	(power_avail satellite10)
	(pointing satellite10 GroundStation4)
)
(:goal (and
	(pointing satellite4 Planet10)
	(pointing satellite6 Planet11)
	(pointing satellite9 Phenomenon7)
	(pointing satellite10 Planet10)
	(have_image Phenomenon6 image1)
	(have_image Phenomenon7 spectrograph3)
	(have_image Phenomenon8 spectrograph5)
	(have_image Phenomenon8 infrared0)
	(have_image Phenomenon9 spectrograph4)
	(have_image Planet10 infrared2)
	(have_image Planet11 image1)
	(have_image Planet11 spectrograph3)
))

)
