(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite5 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite6 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite7 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite8 - satellite
	instrument21 - instrument
	instrument22 - instrument
	satellite9 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite10 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite11 - satellite
	instrument29 - instrument
	instrument30 - instrument
	satellite12 - satellite
	instrument31 - instrument
	instrument32 - instrument
	satellite13 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite14 - satellite
	instrument36 - instrument
	instrument37 - instrument
	satellite15 - satellite
	instrument38 - instrument
	satellite16 - satellite
	instrument39 - instrument
	spectrograph1 - mode
	infrared0 - mode
	Star5 - direction
	Star2 - direction
	Star0 - direction
	Star6 - direction
	Star1 - direction
	GroundStation4 - direction
	Star3 - direction
	Star7 - direction
	Phenomenon8 - direction
	Planet9 - direction
	Phenomenon10 - direction
	Star11 - direction
)
(:init
	(supports instrument0 spectrograph1)
	(supports instrument0 infrared0)
	(calibration_target instrument0 Star3)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star2)
	(supports instrument1 spectrograph1)
	(supports instrument1 infrared0)
	(calibration_target instrument1 GroundStation4)
	(calibration_target instrument1 Star1)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 Star3)
	(calibration_target instrument2 Star0)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star6)
	(supports instrument3 spectrograph1)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 Star5)
	(supports instrument4 infrared0)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 Star2)
	(supports instrument5 spectrograph1)
	(supports instrument5 infrared0)
	(calibration_target instrument5 Star2)
	(calibration_target instrument5 Star3)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star7)
	(supports instrument6 spectrograph1)
	(supports instrument6 infrared0)
	(calibration_target instrument6 Star5)
	(supports instrument7 infrared0)
	(calibration_target instrument7 GroundStation4)
	(calibration_target instrument7 Star5)
	(supports instrument8 infrared0)
	(supports instrument8 spectrograph1)
	(calibration_target instrument8 Star6)
	(calibration_target instrument8 Star1)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon10)
	(supports instrument9 spectrograph1)
	(supports instrument9 infrared0)
	(calibration_target instrument9 Star6)
	(calibration_target instrument9 Star5)
	(supports instrument10 infrared0)
	(supports instrument10 spectrograph1)
	(calibration_target instrument10 GroundStation4)
	(supports instrument11 spectrograph1)
	(calibration_target instrument11 Star0)
	(calibration_target instrument11 Star1)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon8)
	(supports instrument12 spectrograph1)
	(supports instrument12 infrared0)
	(calibration_target instrument12 Star0)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 Star2)
	(supports instrument14 infrared0)
	(supports instrument14 spectrograph1)
	(calibration_target instrument14 Star2)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star5)
	(supports instrument15 spectrograph1)
	(calibration_target instrument15 Star1)
	(calibration_target instrument15 Star2)
	(supports instrument16 infrared0)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 Star6)
	(calibration_target instrument16 Star0)
	(supports instrument17 spectrograph1)
	(supports instrument17 infrared0)
	(calibration_target instrument17 Star2)
	(on_board instrument15 satellite6)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star6)
	(supports instrument18 spectrograph1)
	(supports instrument18 infrared0)
	(calibration_target instrument18 Star2)
	(calibration_target instrument18 Star1)
	(supports instrument19 spectrograph1)
	(calibration_target instrument19 Star1)
	(supports instrument20 infrared0)
	(supports instrument20 spectrograph1)
	(calibration_target instrument20 GroundStation4)
	(calibration_target instrument20 Star5)
	(on_board instrument18 satellite7)
	(on_board instrument19 satellite7)
	(on_board instrument20 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet9)
	(supports instrument21 spectrograph1)
	(supports instrument21 infrared0)
	(calibration_target instrument21 GroundStation4)
	(calibration_target instrument21 Star1)
	(supports instrument22 infrared0)
	(calibration_target instrument22 Star5)
	(calibration_target instrument22 Star0)
	(on_board instrument21 satellite8)
	(on_board instrument22 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Phenomenon10)
	(supports instrument23 infrared0)
	(supports instrument23 spectrograph1)
	(calibration_target instrument23 Star3)
	(supports instrument24 infrared0)
	(calibration_target instrument24 Star6)
	(supports instrument25 infrared0)
	(supports instrument25 spectrograph1)
	(calibration_target instrument25 Star1)
	(on_board instrument23 satellite9)
	(on_board instrument24 satellite9)
	(on_board instrument25 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star1)
	(supports instrument26 spectrograph1)
	(supports instrument26 infrared0)
	(calibration_target instrument26 Star6)
	(supports instrument27 infrared0)
	(calibration_target instrument27 Star1)
	(calibration_target instrument27 GroundStation4)
	(supports instrument28 infrared0)
	(supports instrument28 spectrograph1)
	(calibration_target instrument28 Star6)
	(on_board instrument26 satellite10)
	(on_board instrument27 satellite10)
	(on_board instrument28 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Phenomenon8)
	(supports instrument29 spectrograph1)
	(supports instrument29 infrared0)
	(calibration_target instrument29 Star2)
	(calibration_target instrument29 Star1)
	(supports instrument30 spectrograph1)
	(calibration_target instrument30 GroundStation4)
	(on_board instrument29 satellite11)
	(on_board instrument30 satellite11)
	(power_avail satellite11)
	(pointing satellite11 GroundStation4)
	(supports instrument31 infrared0)
	(supports instrument31 spectrograph1)
	(calibration_target instrument31 Star5)
	(supports instrument32 spectrograph1)
	(supports instrument32 infrared0)
	(calibration_target instrument32 Star0)
	(on_board instrument31 satellite12)
	(on_board instrument32 satellite12)
	(power_avail satellite12)
	(pointing satellite12 Star5)
	(supports instrument33 infrared0)
	(calibration_target instrument33 Star2)
	(supports instrument34 infrared0)
	(calibration_target instrument34 Star3)
	(calibration_target instrument34 Star0)
	(supports instrument35 infrared0)
	(supports instrument35 spectrograph1)
	(calibration_target instrument35 Star3)
	(on_board instrument33 satellite13)
	(on_board instrument34 satellite13)
	(on_board instrument35 satellite13)
	(power_avail satellite13)
	(pointing satellite13 Star7)
	(supports instrument36 infrared0)
	(supports instrument36 spectrograph1)
	(calibration_target instrument36 GroundStation4)
	(calibration_target instrument36 Star6)
	(supports instrument37 spectrograph1)
	(calibration_target instrument37 Star1)
	(on_board instrument36 satellite14)
	(on_board instrument37 satellite14)
	(power_avail satellite14)
	(pointing satellite14 Planet9)
	(supports instrument38 infrared0)
	(supports instrument38 spectrograph1)
	(calibration_target instrument38 Star1)
	(calibration_target instrument38 Star3)
	(on_board instrument38 satellite15)
	(power_avail satellite15)
	(pointing satellite15 Star7)
	(supports instrument39 infrared0)
	(calibration_target instrument39 Star3)
	(calibration_target instrument39 GroundStation4)
	(on_board instrument39 satellite16)
	(power_avail satellite16)
	(pointing satellite16 Star1)
)
(:goal (and
	(pointing satellite8 Star6)
	(pointing satellite11 Star0)
	(have_image Star7 infrared0)
	(have_image Phenomenon8 infrared0)
	(have_image Planet9 spectrograph1)
	(have_image Phenomenon10 infrared0)
	(have_image Star11 infrared0)
))

)
