(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	satellite5 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite6 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite7 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite8 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite9 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite10 - satellite
	instrument22 - instrument
	satellite11 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite12 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite13 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite14 - satellite
	instrument32 - instrument
	instrument33 - instrument
	satellite15 - satellite
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	infrared1 - mode
	spectrograph0 - mode
	GroundStation4 - direction
	GroundStation0 - direction
	GroundStation5 - direction
	Star2 - direction
	GroundStation6 - direction
	GroundStation1 - direction
	GroundStation3 - direction
	GroundStation7 - direction
	Star8 - direction
	Phenomenon9 - direction
	Planet10 - direction
	Star11 - direction
	Star12 - direction
)
(:init
	(supports instrument0 infrared1)
	(supports instrument0 spectrograph0)
	(calibration_target instrument0 Star2)
	(supports instrument1 infrared1)
	(supports instrument1 spectrograph0)
	(calibration_target instrument1 GroundStation1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star8)
	(supports instrument2 infrared1)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 Star2)
	(calibration_target instrument2 GroundStation1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon9)
	(supports instrument3 spectrograph0)
	(supports instrument3 infrared1)
	(calibration_target instrument3 GroundStation7)
	(supports instrument4 spectrograph0)
	(supports instrument4 infrared1)
	(calibration_target instrument4 GroundStation4)
	(supports instrument5 infrared1)
	(supports instrument5 spectrograph0)
	(calibration_target instrument5 GroundStation7)
	(calibration_target instrument5 Star2)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star12)
	(supports instrument6 infrared1)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 GroundStation6)
	(calibration_target instrument6 GroundStation4)
	(supports instrument7 spectrograph0)
	(calibration_target instrument7 GroundStation3)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star2)
	(supports instrument8 spectrograph0)
	(supports instrument8 infrared1)
	(calibration_target instrument8 Star2)
	(on_board instrument8 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star2)
	(supports instrument9 infrared1)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 GroundStation0)
	(calibration_target instrument9 GroundStation6)
	(supports instrument10 spectrograph0)
	(supports instrument10 infrared1)
	(calibration_target instrument10 GroundStation0)
	(on_board instrument9 satellite5)
	(on_board instrument10 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation7)
	(supports instrument11 spectrograph0)
	(supports instrument11 infrared1)
	(calibration_target instrument11 GroundStation5)
	(supports instrument12 infrared1)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 GroundStation3)
	(supports instrument13 spectrograph0)
	(supports instrument13 infrared1)
	(calibration_target instrument13 GroundStation0)
	(calibration_target instrument13 GroundStation7)
	(on_board instrument11 satellite6)
	(on_board instrument12 satellite6)
	(on_board instrument13 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation6)
	(supports instrument14 spectrograph0)
	(supports instrument14 infrared1)
	(calibration_target instrument14 Star2)
	(supports instrument15 infrared1)
	(calibration_target instrument15 GroundStation3)
	(calibration_target instrument15 GroundStation4)
	(on_board instrument14 satellite7)
	(on_board instrument15 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon9)
	(supports instrument16 spectrograph0)
	(supports instrument16 infrared1)
	(calibration_target instrument16 GroundStation4)
	(calibration_target instrument16 GroundStation5)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 GroundStation0)
	(supports instrument18 spectrograph0)
	(calibration_target instrument18 GroundStation5)
	(calibration_target instrument18 GroundStation3)
	(on_board instrument16 satellite8)
	(on_board instrument17 satellite8)
	(on_board instrument18 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation6)
	(supports instrument19 spectrograph0)
	(supports instrument19 infrared1)
	(calibration_target instrument19 GroundStation7)
	(calibration_target instrument19 GroundStation3)
	(supports instrument20 infrared1)
	(supports instrument20 spectrograph0)
	(calibration_target instrument20 Star2)
	(supports instrument21 infrared1)
	(supports instrument21 spectrograph0)
	(calibration_target instrument21 GroundStation0)
	(on_board instrument19 satellite9)
	(on_board instrument20 satellite9)
	(on_board instrument21 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation7)
	(supports instrument22 spectrograph0)
	(supports instrument22 infrared1)
	(calibration_target instrument22 GroundStation4)
	(on_board instrument22 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Star8)
	(supports instrument23 spectrograph0)
	(supports instrument23 infrared1)
	(calibration_target instrument23 GroundStation5)
	(supports instrument24 spectrograph0)
	(supports instrument24 infrared1)
	(calibration_target instrument24 GroundStation3)
	(supports instrument25 spectrograph0)
	(supports instrument25 infrared1)
	(calibration_target instrument25 Star2)
	(calibration_target instrument25 GroundStation3)
	(on_board instrument23 satellite11)
	(on_board instrument24 satellite11)
	(on_board instrument25 satellite11)
	(power_avail satellite11)
	(pointing satellite11 GroundStation1)
	(supports instrument26 infrared1)
	(calibration_target instrument26 GroundStation3)
	(supports instrument27 spectrograph0)
	(calibration_target instrument27 GroundStation0)
	(supports instrument28 infrared1)
	(calibration_target instrument28 GroundStation5)
	(on_board instrument26 satellite12)
	(on_board instrument27 satellite12)
	(on_board instrument28 satellite12)
	(power_avail satellite12)
	(pointing satellite12 GroundStation1)
	(supports instrument29 infrared1)
	(calibration_target instrument29 GroundStation6)
	(supports instrument30 spectrograph0)
	(supports instrument30 infrared1)
	(calibration_target instrument30 GroundStation3)
	(supports instrument31 infrared1)
	(supports instrument31 spectrograph0)
	(calibration_target instrument31 Star2)
	(calibration_target instrument31 GroundStation5)
	(on_board instrument29 satellite13)
	(on_board instrument30 satellite13)
	(on_board instrument31 satellite13)
	(power_avail satellite13)
	(pointing satellite13 Star12)
	(supports instrument32 spectrograph0)
	(calibration_target instrument32 GroundStation1)
	(supports instrument33 spectrograph0)
	(calibration_target instrument33 GroundStation6)
	(on_board instrument32 satellite14)
	(on_board instrument33 satellite14)
	(power_avail satellite14)
	(pointing satellite14 Star12)
	(supports instrument34 spectrograph0)
	(supports instrument34 infrared1)
	(calibration_target instrument34 GroundStation3)
	(supports instrument35 infrared1)
	(supports instrument35 spectrograph0)
	(calibration_target instrument35 GroundStation1)
	(supports instrument36 spectrograph0)
	(supports instrument36 infrared1)
	(calibration_target instrument36 GroundStation7)
	(calibration_target instrument36 GroundStation3)
	(on_board instrument34 satellite15)
	(on_board instrument35 satellite15)
	(on_board instrument36 satellite15)
	(power_avail satellite15)
	(pointing satellite15 Star12)
)
(:goal (and
	(pointing satellite0 Star12)
	(pointing satellite1 Planet10)
	(pointing satellite10 GroundStation1)
	(pointing satellite12 GroundStation0)
	(have_image Star8 spectrograph0)
	(have_image Phenomenon9 infrared1)
	(have_image Planet10 infrared1)
	(have_image Star11 spectrograph0)
	(have_image Star12 spectrograph0)
))

)
