(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite5 - satellite
	instrument12 - instrument
	satellite6 - satellite
	instrument13 - instrument
	instrument14 - instrument
	thermograph0 - mode
	image1 - mode
	Star2 - direction
	GroundStation10 - direction
	Star14 - direction
	Star3 - direction
	Star6 - direction
	Star11 - direction
	Star8 - direction
	Star5 - direction
	Star1 - direction
	Star13 - direction
	GroundStation12 - direction
	GroundStation0 - direction
	GroundStation9 - direction
	GroundStation4 - direction
	Star15 - direction
	GroundStation7 - direction
	Phenomenon16 - direction
	Star17 - direction
	Planet18 - direction
	Star19 - direction
	Star20 - direction
	Star21 - direction
)
(:init
	(supports instrument0 thermograph0)
	(calibration_target instrument0 GroundStation10)
	(supports instrument1 image1)
	(supports instrument1 thermograph0)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 Star15)
	(supports instrument2 image1)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 Star15)
	(calibration_target instrument2 GroundStation12)
	(calibration_target instrument2 GroundStation7)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation7)
	(supports instrument3 image1)
	(supports instrument3 thermograph0)
	(calibration_target instrument3 Star11)
	(calibration_target instrument3 GroundStation9)
	(calibration_target instrument3 Star14)
	(calibration_target instrument3 GroundStation7)
	(calibration_target instrument3 Star3)
	(supports instrument4 image1)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 Star15)
	(calibration_target instrument4 GroundStation12)
	(calibration_target instrument4 Star5)
	(calibration_target instrument4 GroundStation9)
	(calibration_target instrument4 Star1)
	(supports instrument5 thermograph0)
	(calibration_target instrument5 GroundStation4)
	(calibration_target instrument5 Star15)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation0)
	(supports instrument6 image1)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 Star8)
	(calibration_target instrument6 Star11)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation10)
	(supports instrument7 thermograph0)
	(supports instrument7 image1)
	(calibration_target instrument7 Star13)
	(calibration_target instrument7 GroundStation4)
	(calibration_target instrument7 Star5)
	(calibration_target instrument7 GroundStation0)
	(supports instrument8 thermograph0)
	(supports instrument8 image1)
	(calibration_target instrument8 Star1)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 Star14)
	(calibration_target instrument8 Star11)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star3)
	(supports instrument9 image1)
	(calibration_target instrument9 Star11)
	(calibration_target instrument9 GroundStation0)
	(calibration_target instrument9 GroundStation7)
	(supports instrument10 thermograph0)
	(supports instrument10 image1)
	(calibration_target instrument10 Star14)
	(supports instrument11 image1)
	(supports instrument11 thermograph0)
	(calibration_target instrument11 Star1)
	(calibration_target instrument11 GroundStation10)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star2)
	(supports instrument12 thermograph0)
	(supports instrument12 image1)
	(calibration_target instrument12 Star11)
	(calibration_target instrument12 Star6)
	(calibration_target instrument12 Star3)
	(calibration_target instrument12 GroundStation12)
	(calibration_target instrument12 Star14)
	(on_board instrument12 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation12)
	(supports instrument13 image1)
	(supports instrument13 thermograph0)
	(calibration_target instrument13 GroundStation12)
	(calibration_target instrument13 Star13)
	(calibration_target instrument13 Star1)
	(calibration_target instrument13 Star5)
	(calibration_target instrument13 Star8)
	(supports instrument14 thermograph0)
	(calibration_target instrument14 GroundStation7)
	(calibration_target instrument14 Star15)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 GroundStation9)
	(calibration_target instrument14 GroundStation0)
	(on_board instrument13 satellite6)
	(on_board instrument14 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation10)
)
(:goal (and
	(pointing satellite1 Star11)
	(pointing satellite2 Star13)
	(pointing satellite3 Star17)
	(have_image Phenomenon16 thermograph0)
	(have_image Star17 thermograph0)
	(have_image Planet18 thermograph0)
	(have_image Star19 image1)
	(have_image Star20 thermograph0)
	(have_image Star21 thermograph0)
))

)
