(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	satellite3 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	instrument9 - instrument
	satellite5 - satellite
	instrument10 - instrument
	instrument11 - instrument
	satellite6 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite7 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite8 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite9 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite10 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	satellite11 - satellite
	instrument27 - instrument
	instrument28 - instrument
	spectrograph0 - mode
	spectrograph6 - mode
	infrared3 - mode
	spectrograph2 - mode
	infrared5 - mode
	infrared1 - mode
	infrared4 - mode
	infrared7 - mode
	GroundStation0 - direction
	GroundStation4 - direction
	Star5 - direction
	GroundStation2 - direction
	Star1 - direction
	GroundStation3 - direction
	Phenomenon6 - direction
	Phenomenon7 - direction
	Star8 - direction
	Star9 - direction
	Phenomenon10 - direction
)
(:init
	(supports instrument0 spectrograph2)
	(supports instrument0 infrared3)
	(supports instrument0 infrared7)
	(calibration_target instrument0 Star5)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star1)
	(supports instrument1 infrared1)
	(calibration_target instrument1 GroundStation3)
	(calibration_target instrument1 Star1)
	(supports instrument2 infrared5)
	(supports instrument2 infrared4)
	(calibration_target instrument2 Star5)
	(calibration_target instrument2 GroundStation3)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star5)
	(supports instrument3 infrared5)
	(supports instrument3 spectrograph2)
	(supports instrument3 infrared4)
	(calibration_target instrument3 GroundStation2)
	(calibration_target instrument3 GroundStation4)
	(supports instrument4 infrared4)
	(calibration_target instrument4 GroundStation4)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star1)
	(supports instrument5 infrared1)
	(supports instrument5 spectrograph0)
	(supports instrument5 infrared7)
	(calibration_target instrument5 GroundStation3)
	(supports instrument6 spectrograph6)
	(calibration_target instrument6 Star1)
	(calibration_target instrument6 GroundStation0)
	(supports instrument7 infrared1)
	(supports instrument7 infrared5)
	(supports instrument7 spectrograph6)
	(calibration_target instrument7 GroundStation3)
	(on_board instrument5 satellite3)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star9)
	(supports instrument8 infrared3)
	(calibration_target instrument8 GroundStation3)
	(supports instrument9 spectrograph2)
	(calibration_target instrument9 Star1)
	(calibration_target instrument9 GroundStation4)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon7)
	(supports instrument10 infrared1)
	(supports instrument10 infrared4)
	(supports instrument10 spectrograph0)
	(calibration_target instrument10 GroundStation4)
	(supports instrument11 infrared7)
	(calibration_target instrument11 Star5)
	(calibration_target instrument11 Star1)
	(on_board instrument10 satellite5)
	(on_board instrument11 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation2)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 GroundStation4)
	(calibration_target instrument12 Star5)
	(supports instrument13 spectrograph2)
	(calibration_target instrument13 GroundStation4)
	(supports instrument14 spectrograph6)
	(calibration_target instrument14 Star5)
	(on_board instrument12 satellite6)
	(on_board instrument13 satellite6)
	(on_board instrument14 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star9)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 GroundStation3)
	(supports instrument16 infrared4)
	(supports instrument16 spectrograph0)
	(supports instrument16 infrared7)
	(calibration_target instrument16 GroundStation0)
	(supports instrument17 infrared7)
	(supports instrument17 spectrograph2)
	(supports instrument17 infrared5)
	(calibration_target instrument17 Star5)
	(calibration_target instrument17 Star1)
	(on_board instrument15 satellite7)
	(on_board instrument16 satellite7)
	(on_board instrument17 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star5)
	(supports instrument18 spectrograph2)
	(calibration_target instrument18 GroundStation3)
	(calibration_target instrument18 GroundStation0)
	(supports instrument19 spectrograph2)
	(calibration_target instrument19 GroundStation0)
	(supports instrument20 spectrograph2)
	(calibration_target instrument20 GroundStation0)
	(calibration_target instrument20 Star1)
	(on_board instrument18 satellite8)
	(on_board instrument19 satellite8)
	(on_board instrument20 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star9)
	(supports instrument21 spectrograph6)
	(calibration_target instrument21 Star1)
	(supports instrument22 infrared4)
	(supports instrument22 infrared7)
	(calibration_target instrument22 Star1)
	(calibration_target instrument22 GroundStation3)
	(supports instrument23 spectrograph6)
	(supports instrument23 spectrograph2)
	(calibration_target instrument23 Star1)
	(on_board instrument21 satellite9)
	(on_board instrument22 satellite9)
	(on_board instrument23 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation2)
	(supports instrument24 infrared4)
	(calibration_target instrument24 GroundStation4)
	(supports instrument25 infrared7)
	(supports instrument25 infrared3)
	(calibration_target instrument25 Star1)
	(supports instrument26 infrared5)
	(supports instrument26 spectrograph2)
	(calibration_target instrument26 GroundStation2)
	(calibration_target instrument26 Star5)
	(on_board instrument24 satellite10)
	(on_board instrument25 satellite10)
	(on_board instrument26 satellite10)
	(power_avail satellite10)
	(pointing satellite10 GroundStation3)
	(supports instrument27 spectrograph6)
	(supports instrument27 infrared4)
	(supports instrument27 infrared3)
	(calibration_target instrument27 Star1)
	(supports instrument28 infrared4)
	(supports instrument28 infrared5)
	(calibration_target instrument28 GroundStation3)
	(on_board instrument27 satellite11)
	(on_board instrument28 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Phenomenon7)
)
(:goal (and
	(pointing satellite1 Star8)
	(pointing satellite2 GroundStation2)
	(pointing satellite4 Star8)
	(pointing satellite5 Phenomenon10)
	(have_image Phenomenon6 infrared3)
	(have_image Phenomenon6 infrared4)
	(have_image Phenomenon7 infrared4)
	(have_image Star8 infrared1)
	(have_image Star8 infrared4)
	(have_image Star9 infrared5)
	(have_image Star9 spectrograph6)
	(have_image Phenomenon10 infrared1)
	(have_image Phenomenon10 spectrograph2)
))

)
