(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	satellite5 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite6 - satellite
	instrument12 - instrument
	satellite7 - satellite
	instrument13 - instrument
	instrument14 - instrument
	satellite8 - satellite
	instrument15 - instrument
	instrument16 - instrument
	infrared0 - mode
	infrared1 - mode
	image2 - mode
	GroundStation6 - direction
	GroundStation1 - direction
	GroundStation9 - direction
	Star13 - direction
	GroundStation7 - direction
	GroundStation5 - direction
	GroundStation4 - direction
	Star0 - direction
	GroundStation11 - direction
	GroundStation10 - direction
	GroundStation2 - direction
	Star3 - direction
	Star8 - direction
	Star12 - direction
	Phenomenon14 - direction
	Star15 - direction
	Planet16 - direction
	Star17 - direction
	Star18 - direction
)
(:init
	(supports instrument0 infrared1)
	(supports instrument0 image2)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 GroundStation10)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 infrared1)
	(supports instrument1 infrared0)
	(supports instrument1 image2)
	(calibration_target instrument1 GroundStation1)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 Star8)
	(supports instrument2 infrared1)
	(supports instrument2 infrared0)
	(supports instrument2 image2)
	(calibration_target instrument2 GroundStation9)
	(calibration_target instrument2 Star12)
	(calibration_target instrument2 Star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation10)
	(supports instrument3 infrared0)
	(supports instrument3 infrared1)
	(supports instrument3 image2)
	(calibration_target instrument3 Star3)
	(calibration_target instrument3 Star13)
	(calibration_target instrument3 Star12)
	(calibration_target instrument3 GroundStation1)
	(supports instrument4 infrared0)
	(calibration_target instrument4 GroundStation10)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 Star13)
	(supports instrument5 image2)
	(supports instrument5 infrared0)
	(supports instrument5 infrared1)
	(calibration_target instrument5 GroundStation4)
	(calibration_target instrument5 GroundStation5)
	(calibration_target instrument5 Star12)
	(calibration_target instrument5 GroundStation9)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star12)
	(supports instrument6 image2)
	(supports instrument6 infrared0)
	(calibration_target instrument6 Star13)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation2)
	(supports instrument7 image2)
	(supports instrument7 infrared1)
	(supports instrument7 infrared0)
	(calibration_target instrument7 GroundStation9)
	(calibration_target instrument7 GroundStation1)
	(calibration_target instrument7 GroundStation2)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon14)
	(supports instrument8 image2)
	(supports instrument8 infrared0)
	(supports instrument8 infrared1)
	(calibration_target instrument8 Star3)
	(calibration_target instrument8 Star13)
	(calibration_target instrument8 GroundStation4)
	(on_board instrument8 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star18)
	(supports instrument9 infrared0)
	(supports instrument9 image2)
	(supports instrument9 infrared1)
	(calibration_target instrument9 GroundStation2)
	(supports instrument10 image2)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 GroundStation5)
	(calibration_target instrument10 GroundStation11)
	(calibration_target instrument10 GroundStation7)
	(supports instrument11 image2)
	(supports instrument11 infrared0)
	(supports instrument11 infrared1)
	(calibration_target instrument11 GroundStation2)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 GroundStation7)
	(on_board instrument9 satellite5)
	(on_board instrument10 satellite5)
	(on_board instrument11 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation11)
	(supports instrument12 infrared1)
	(calibration_target instrument12 GroundStation5)
	(on_board instrument12 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation5)
	(supports instrument13 infrared0)
	(supports instrument13 image2)
	(calibration_target instrument13 GroundStation4)
	(supports instrument14 infrared1)
	(supports instrument14 infrared0)
	(supports instrument14 image2)
	(calibration_target instrument14 GroundStation11)
	(calibration_target instrument14 Star8)
	(calibration_target instrument14 Star0)
	(calibration_target instrument14 Star12)
	(on_board instrument13 satellite7)
	(on_board instrument14 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation10)
	(supports instrument15 infrared1)
	(calibration_target instrument15 Star8)
	(calibration_target instrument15 Star3)
	(calibration_target instrument15 GroundStation2)
	(calibration_target instrument15 GroundStation10)
	(supports instrument16 infrared0)
	(supports instrument16 image2)
	(calibration_target instrument16 Star12)
	(on_board instrument15 satellite8)
	(on_board instrument16 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation10)
)
(:goal (and
	(pointing satellite0 Star3)
	(pointing satellite2 GroundStation1)
	(pointing satellite3 GroundStation11)
	(pointing satellite4 Phenomenon14)
	(pointing satellite5 Star15)
	(pointing satellite8 GroundStation1)
	(have_image Phenomenon14 infrared0)
	(have_image Star15 infrared0)
	(have_image Planet16 infrared0)
	(have_image Star17 infrared1)
	(have_image Star18 infrared0)
))

)
