(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite5 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite6 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	thermograph4 - mode
	infrared3 - mode
	infrared1 - mode
	spectrograph0 - mode
	spectrograph2 - mode
	GroundStation1 - direction
	GroundStation8 - direction
	Star10 - direction
	Star3 - direction
	Star11 - direction
	Star2 - direction
	Star6 - direction
	GroundStation9 - direction
	Star4 - direction
	Star0 - direction
	Star5 - direction
	GroundStation7 - direction
	Planet12 - direction
	Planet13 - direction
	Phenomenon14 - direction
	Planet15 - direction
	Planet16 - direction
)
(:init
	(supports instrument0 spectrograph2)
	(calibration_target instrument0 GroundStation1)
	(calibration_target instrument0 GroundStation9)
	(calibration_target instrument0 Star6)
	(calibration_target instrument0 Star3)
	(supports instrument1 spectrograph0)
	(supports instrument1 thermograph4)
	(supports instrument1 infrared1)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 Star10)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star0)
	(supports instrument2 spectrograph2)
	(supports instrument2 spectrograph0)
	(supports instrument2 infrared3)
	(calibration_target instrument2 Star10)
	(calibration_target instrument2 Star4)
	(calibration_target instrument2 Star6)
	(supports instrument3 infrared3)
	(supports instrument3 spectrograph0)
	(supports instrument3 infrared1)
	(calibration_target instrument3 Star10)
	(calibration_target instrument3 GroundStation8)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet15)
	(supports instrument4 thermograph4)
	(supports instrument4 infrared1)
	(supports instrument4 spectrograph2)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 Star5)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 Star11)
	(supports instrument5 infrared1)
	(supports instrument5 spectrograph2)
	(supports instrument5 infrared3)
	(calibration_target instrument5 Star10)
	(calibration_target instrument5 Star5)
	(supports instrument6 spectrograph2)
	(supports instrument6 thermograph4)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star4)
	(calibration_target instrument6 Star10)
	(calibration_target instrument6 Star6)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star11)
	(supports instrument7 spectrograph2)
	(supports instrument7 infrared3)
	(calibration_target instrument7 Star10)
	(supports instrument8 infrared1)
	(supports instrument8 thermograph4)
	(calibration_target instrument8 Star3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation9)
	(supports instrument9 thermograph4)
	(supports instrument9 spectrograph0)
	(supports instrument9 infrared1)
	(calibration_target instrument9 Star6)
	(calibration_target instrument9 Star3)
	(supports instrument10 infrared1)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 GroundStation7)
	(calibration_target instrument10 Star4)
	(calibration_target instrument10 Star10)
	(supports instrument11 infrared3)
	(supports instrument11 spectrograph2)
	(calibration_target instrument11 Star4)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 Star0)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star10)
	(supports instrument12 infrared3)
	(supports instrument12 infrared1)
	(supports instrument12 spectrograph2)
	(calibration_target instrument12 Star2)
	(calibration_target instrument12 Star11)
	(supports instrument13 infrared1)
	(supports instrument13 infrared3)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 Star6)
	(supports instrument14 spectrograph0)
	(supports instrument14 infrared3)
	(calibration_target instrument14 Star4)
	(calibration_target instrument14 GroundStation9)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star2)
	(supports instrument15 spectrograph2)
	(supports instrument15 infrared1)
	(calibration_target instrument15 GroundStation7)
	(calibration_target instrument15 Star0)
	(supports instrument16 spectrograph0)
	(supports instrument16 thermograph4)
	(supports instrument16 spectrograph2)
	(calibration_target instrument16 Star5)
	(supports instrument17 spectrograph0)
	(supports instrument17 infrared3)
	(supports instrument17 spectrograph2)
	(calibration_target instrument17 GroundStation7)
	(on_board instrument15 satellite6)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon14)
)
(:goal (and
	(pointing satellite1 Star0)
	(pointing satellite2 Planet12)
	(pointing satellite3 GroundStation9)
	(pointing satellite5 Star11)
	(have_image Planet12 spectrograph0)
	(have_image Planet13 infrared1)
	(have_image Phenomenon14 spectrograph0)
	(have_image Planet15 thermograph4)
	(have_image Planet16 infrared3)
))

)
