(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	satellite3 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite6 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite7 - satellite
	instrument16 - instrument
	instrument17 - instrument
	thermograph1 - mode
	image2 - mode
	spectrograph0 - mode
	Star1 - direction
	GroundStation9 - direction
	Star10 - direction
	Star0 - direction
	Star7 - direction
	GroundStation4 - direction
	GroundStation11 - direction
	GroundStation2 - direction
	Star8 - direction
	GroundStation5 - direction
	GroundStation12 - direction
	Star3 - direction
	GroundStation6 - direction
	Planet13 - direction
	Planet14 - direction
	Planet15 - direction
	Star16 - direction
	Phenomenon17 - direction
	Star18 - direction
)
(:init
	(supports instrument0 thermograph1)
	(supports instrument0 image2)
	(supports instrument0 spectrograph0)
	(calibration_target instrument0 Star0)
	(calibration_target instrument0 Star7)
	(calibration_target instrument0 Star10)
	(supports instrument1 thermograph1)
	(supports instrument1 spectrograph0)
	(calibration_target instrument1 GroundStation11)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 GroundStation5)
	(calibration_target instrument1 GroundStation12)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet13)
	(supports instrument2 spectrograph0)
	(supports instrument2 thermograph1)
	(supports instrument2 image2)
	(calibration_target instrument2 Star8)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 GroundStation4)
	(supports instrument3 spectrograph0)
	(supports instrument3 thermograph1)
	(calibration_target instrument3 GroundStation5)
	(calibration_target instrument3 Star7)
	(calibration_target instrument3 GroundStation4)
	(calibration_target instrument3 Star8)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star16)
	(supports instrument4 thermograph1)
	(supports instrument4 spectrograph0)
	(supports instrument4 image2)
	(calibration_target instrument4 GroundStation12)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 Star8)
	(on_board instrument4 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation9)
	(supports instrument5 spectrograph0)
	(supports instrument5 image2)
	(calibration_target instrument5 GroundStation12)
	(calibration_target instrument5 Star3)
	(calibration_target instrument5 Star1)
	(calibration_target instrument5 Star10)
	(supports instrument6 image2)
	(calibration_target instrument6 Star3)
	(supports instrument7 spectrograph0)
	(supports instrument7 thermograph1)
	(supports instrument7 image2)
	(calibration_target instrument7 GroundStation9)
	(calibration_target instrument7 GroundStation5)
	(calibration_target instrument7 Star8)
	(calibration_target instrument7 GroundStation12)
	(on_board instrument5 satellite3)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation4)
	(supports instrument8 thermograph1)
	(supports instrument8 spectrograph0)
	(calibration_target instrument8 GroundStation11)
	(calibration_target instrument8 Star0)
	(supports instrument9 spectrograph0)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 GroundStation5)
	(calibration_target instrument9 Star8)
	(calibration_target instrument9 Star7)
	(supports instrument10 thermograph1)
	(supports instrument10 image2)
	(supports instrument10 spectrograph0)
	(calibration_target instrument10 GroundStation5)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 GroundStation12)
	(supports instrument11 image2)
	(supports instrument11 thermograph1)
	(supports instrument11 spectrograph0)
	(calibration_target instrument11 Star10)
	(supports instrument12 spectrograph0)
	(supports instrument12 thermograph1)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star3)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation9)
	(supports instrument13 thermograph1)
	(supports instrument13 image2)
	(calibration_target instrument13 Star0)
	(supports instrument14 spectrograph0)
	(supports instrument14 thermograph1)
	(calibration_target instrument14 GroundStation11)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 Star7)
	(supports instrument15 thermograph1)
	(calibration_target instrument15 Star8)
	(calibration_target instrument15 GroundStation12)
	(calibration_target instrument15 GroundStation2)
	(on_board instrument13 satellite6)
	(on_board instrument14 satellite6)
	(on_board instrument15 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation11)
	(supports instrument16 spectrograph0)
	(supports instrument16 thermograph1)
	(supports instrument16 image2)
	(calibration_target instrument16 Star3)
	(calibration_target instrument16 GroundStation12)
	(calibration_target instrument16 GroundStation5)
	(supports instrument17 spectrograph0)
	(supports instrument17 thermograph1)
	(calibration_target instrument17 GroundStation6)
	(on_board instrument16 satellite7)
	(on_board instrument17 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation4)
)
(:goal (and
	(pointing satellite1 Star3)
	(pointing satellite5 Star0)
	(pointing satellite7 GroundStation12)
	(have_image Planet13 spectrograph0)
	(have_image Planet14 thermograph1)
	(have_image Planet15 thermograph1)
	(have_image Star16 image2)
	(have_image Phenomenon17 image2)
	(have_image Star18 spectrograph0)
))

)
