(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite6 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite7 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite8 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite9 - satellite
	instrument21 - instrument
	spectrograph2 - mode
	image0 - mode
	spectrograph1 - mode
	GroundStation9 - direction
	Star8 - direction
	Star0 - direction
	GroundStation12 - direction
	Star5 - direction
	GroundStation10 - direction
	Star6 - direction
	GroundStation4 - direction
	GroundStation1 - direction
	Star7 - direction
	Star2 - direction
	GroundStation3 - direction
	GroundStation11 - direction
	Planet13 - direction
	Planet14 - direction
	Phenomenon15 - direction
	Phenomenon16 - direction
	Star17 - direction
)
(:init
	(supports instrument0 spectrograph1)
	(supports instrument0 spectrograph2)
	(supports instrument0 image0)
	(calibration_target instrument0 Star8)
	(calibration_target instrument0 GroundStation3)
	(calibration_target instrument0 Star5)
	(calibration_target instrument0 Star6)
	(supports instrument1 spectrograph1)
	(supports instrument1 image0)
	(calibration_target instrument1 Star2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation9)
	(supports instrument2 spectrograph2)
	(supports instrument2 image0)
	(calibration_target instrument2 GroundStation11)
	(calibration_target instrument2 Star2)
	(calibration_target instrument2 GroundStation3)
	(calibration_target instrument2 GroundStation10)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star17)
	(supports instrument3 image0)
	(supports instrument3 spectrograph2)
	(calibration_target instrument3 GroundStation11)
	(calibration_target instrument3 GroundStation12)
	(calibration_target instrument3 Star6)
	(supports instrument4 image0)
	(calibration_target instrument4 Star7)
	(calibration_target instrument4 GroundStation1)
	(calibration_target instrument4 Star2)
	(calibration_target instrument4 Star6)
	(supports instrument5 spectrograph2)
	(calibration_target instrument5 Star5)
	(calibration_target instrument5 Star8)
	(calibration_target instrument5 GroundStation9)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation10)
	(supports instrument6 spectrograph2)
	(calibration_target instrument6 GroundStation12)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 GroundStation3)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation4)
	(supports instrument8 spectrograph1)
	(supports instrument8 image0)
	(calibration_target instrument8 Star6)
	(calibration_target instrument8 GroundStation3)
	(calibration_target instrument8 Star2)
	(supports instrument9 spectrograph1)
	(supports instrument9 spectrograph2)
	(calibration_target instrument9 GroundStation3)
	(calibration_target instrument9 Star2)
	(calibration_target instrument9 GroundStation4)
	(calibration_target instrument9 GroundStation11)
	(supports instrument10 image0)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 Star6)
	(calibration_target instrument10 Star7)
	(calibration_target instrument10 GroundStation12)
	(calibration_target instrument10 GroundStation1)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet14)
	(supports instrument11 spectrograph1)
	(supports instrument11 image0)
	(calibration_target instrument11 GroundStation10)
	(calibration_target instrument11 GroundStation1)
	(supports instrument12 spectrograph1)
	(supports instrument12 image0)
	(calibration_target instrument12 GroundStation12)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 Star7)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 Star5)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation4)
	(supports instrument14 spectrograph2)
	(supports instrument14 spectrograph1)
	(calibration_target instrument14 Star6)
	(supports instrument15 image0)
	(supports instrument15 spectrograph1)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 Star5)
	(on_board instrument14 satellite6)
	(on_board instrument15 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star7)
	(supports instrument16 image0)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 GroundStation1)
	(calibration_target instrument16 GroundStation3)
	(supports instrument17 spectrograph2)
	(calibration_target instrument17 Star7)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 GroundStation10)
	(calibration_target instrument17 Star5)
	(on_board instrument16 satellite7)
	(on_board instrument17 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star17)
	(supports instrument18 spectrograph1)
	(supports instrument18 spectrograph2)
	(supports instrument18 image0)
	(calibration_target instrument18 GroundStation4)
	(calibration_target instrument18 GroundStation3)
	(calibration_target instrument18 Star6)
	(calibration_target instrument18 GroundStation11)
	(supports instrument19 image0)
	(calibration_target instrument19 Star7)
	(calibration_target instrument19 GroundStation1)
	(supports instrument20 image0)
	(calibration_target instrument20 Star2)
	(on_board instrument18 satellite8)
	(on_board instrument19 satellite8)
	(on_board instrument20 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star8)
	(supports instrument21 spectrograph1)
	(supports instrument21 image0)
	(calibration_target instrument21 GroundStation11)
	(calibration_target instrument21 GroundStation3)
	(on_board instrument21 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation12)
)
(:goal (and
	(pointing satellite0 Planet14)
	(pointing satellite5 Star6)
	(pointing satellite8 Star8)
	(pointing satellite9 Star5)
	(have_image Planet13 spectrograph1)
	(have_image Planet14 spectrograph1)
	(have_image Phenomenon15 image0)
	(have_image Phenomenon16 spectrograph1)
	(have_image Star17 spectrograph1)
))

)
