(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	satellite5 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite6 - satellite
	instrument17 - instrument
	satellite7 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	satellite8 - satellite
	instrument21 - instrument
	instrument22 - instrument
	satellite9 - satellite
	instrument23 - instrument
	instrument24 - instrument
	infrared0 - mode
	image1 - mode
	image2 - mode
	infrared3 - mode
	Star2 - direction
	Star6 - direction
	Star0 - direction
	GroundStation1 - direction
	Star4 - direction
	Star5 - direction
	Star3 - direction
	Planet7 - direction
	Star8 - direction
	Planet9 - direction
	Planet10 - direction
	Planet11 - direction
	Planet12 - direction
)
(:init
	(supports instrument0 image2)
	(supports instrument0 image1)
	(calibration_target instrument0 Star4)
	(supports instrument1 image2)
	(supports instrument1 infrared0)
	(supports instrument1 infrared3)
	(calibration_target instrument1 GroundStation1)
	(calibration_target instrument1 Star0)
	(supports instrument2 infrared0)
	(supports instrument2 image2)
	(calibration_target instrument2 Star6)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet12)
	(supports instrument3 image2)
	(supports instrument3 infrared3)
	(calibration_target instrument3 Star0)
	(supports instrument4 infrared0)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 Star2)
	(supports instrument5 infrared3)
	(supports instrument5 image2)
	(supports instrument5 image1)
	(calibration_target instrument5 Star2)
	(calibration_target instrument5 Star3)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet7)
	(supports instrument6 image2)
	(supports instrument6 infrared0)
	(supports instrument6 image1)
	(calibration_target instrument6 Star5)
	(supports instrument7 image1)
	(supports instrument7 infrared0)
	(supports instrument7 infrared3)
	(calibration_target instrument7 Star0)
	(supports instrument8 infrared3)
	(supports instrument8 image1)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 Star3)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet12)
	(supports instrument9 infrared3)
	(calibration_target instrument9 Star3)
	(calibration_target instrument9 Star4)
	(supports instrument10 image2)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 Star5)
	(supports instrument11 infrared0)
	(calibration_target instrument11 Star4)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star0)
	(supports instrument12 image2)
	(supports instrument12 infrared3)
	(supports instrument12 image1)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 GroundStation1)
	(supports instrument13 image1)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 Star5)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star2)
	(supports instrument14 image1)
	(supports instrument14 infrared0)
	(supports instrument14 image2)
	(calibration_target instrument14 Star4)
	(calibration_target instrument14 Star6)
	(supports instrument15 infrared3)
	(supports instrument15 image2)
	(supports instrument15 infrared0)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 Star5)
	(supports instrument16 infrared3)
	(supports instrument16 image2)
	(calibration_target instrument16 Star3)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star3)
	(supports instrument17 image1)
	(calibration_target instrument17 Star0)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star6)
	(supports instrument18 image2)
	(supports instrument18 infrared0)
	(supports instrument18 infrared3)
	(calibration_target instrument18 Star0)
	(calibration_target instrument18 Star3)
	(supports instrument19 image2)
	(supports instrument19 infrared0)
	(supports instrument19 image1)
	(calibration_target instrument19 GroundStation1)
	(supports instrument20 image1)
	(supports instrument20 infrared0)
	(calibration_target instrument20 Star3)
	(calibration_target instrument20 Star0)
	(on_board instrument18 satellite7)
	(on_board instrument19 satellite7)
	(on_board instrument20 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star0)
	(supports instrument21 image1)
	(calibration_target instrument21 Star4)
	(calibration_target instrument21 GroundStation1)
	(supports instrument22 infrared0)
	(calibration_target instrument22 Star4)
	(on_board instrument21 satellite8)
	(on_board instrument22 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation1)
	(supports instrument23 image1)
	(supports instrument23 infrared3)
	(calibration_target instrument23 Star5)
	(supports instrument24 infrared0)
	(supports instrument24 image2)
	(supports instrument24 image1)
	(calibration_target instrument24 Star3)
	(on_board instrument23 satellite9)
	(on_board instrument24 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star6)
)
(:goal (and
	(pointing satellite1 Star5)
	(pointing satellite2 Star0)
	(pointing satellite3 Planet12)
	(pointing satellite4 Planet12)
	(pointing satellite6 Star6)
	(pointing satellite8 GroundStation1)
	(have_image Planet7 infrared0)
	(have_image Star8 image2)
	(have_image Planet9 image2)
	(have_image Planet10 image2)
	(have_image Planet11 image2)
	(have_image Planet12 image2)
))

)
