(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	instrument11 - instrument
	image0 - mode
	image1 - mode
	Star2 - direction
	GroundStation11 - direction
	GroundStation7 - direction
	Star14 - direction
	GroundStation16 - direction
	GroundStation8 - direction
	Star17 - direction
	GroundStation6 - direction
	GroundStation9 - direction
	Star1 - direction
	Star4 - direction
	GroundStation13 - direction
	GroundStation5 - direction
	Star12 - direction
	GroundStation0 - direction
	GroundStation3 - direction
	Star10 - direction
	GroundStation15 - direction
	Phenomenon18 - direction
	Planet19 - direction
	Phenomenon20 - direction
	Planet21 - direction
	Planet22 - direction
)
(:init
	(supports instrument0 image1)
	(supports instrument0 image0)
	(calibration_target instrument0 GroundStation13)
	(calibration_target instrument0 Star1)
	(calibration_target instrument0 Star12)
	(calibration_target instrument0 Star2)
	(calibration_target instrument0 GroundStation8)
	(calibration_target instrument0 GroundStation3)
	(supports instrument1 image0)
	(calibration_target instrument1 Star4)
	(calibration_target instrument1 GroundStation9)
	(supports instrument2 image1)
	(calibration_target instrument2 GroundStation9)
	(calibration_target instrument2 GroundStation5)
	(calibration_target instrument2 GroundStation0)
	(calibration_target instrument2 GroundStation3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star17)
	(supports instrument3 image0)
	(calibration_target instrument3 Star12)
	(calibration_target instrument3 GroundStation11)
	(calibration_target instrument3 Star1)
	(supports instrument4 image0)
	(supports instrument4 image1)
	(calibration_target instrument4 Star10)
	(calibration_target instrument4 GroundStation8)
	(calibration_target instrument4 GroundStation15)
	(calibration_target instrument4 GroundStation6)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star1)
	(supports instrument5 image1)
	(supports instrument5 image0)
	(calibration_target instrument5 GroundStation6)
	(supports instrument6 image0)
	(supports instrument6 image1)
	(calibration_target instrument6 GroundStation11)
	(calibration_target instrument6 GroundStation8)
	(calibration_target instrument6 GroundStation0)
	(calibration_target instrument6 GroundStation9)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation0)
	(supports instrument7 image1)
	(supports instrument7 image0)
	(calibration_target instrument7 GroundStation3)
	(calibration_target instrument7 GroundStation16)
	(calibration_target instrument7 GroundStation0)
	(calibration_target instrument7 GroundStation6)
	(calibration_target instrument7 Star14)
	(calibration_target instrument7 GroundStation7)
	(supports instrument8 image1)
	(calibration_target instrument8 GroundStation0)
	(calibration_target instrument8 GroundStation8)
	(calibration_target instrument8 GroundStation16)
	(calibration_target instrument8 Star10)
	(calibration_target instrument8 Star17)
	(supports instrument9 image1)
	(calibration_target instrument9 Star1)
	(calibration_target instrument9 GroundStation9)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 Star17)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation9)
	(supports instrument10 image0)
	(supports instrument10 image1)
	(calibration_target instrument10 GroundStation13)
	(calibration_target instrument10 GroundStation15)
	(calibration_target instrument10 GroundStation5)
	(calibration_target instrument10 Star4)
	(supports instrument11 image1)
	(calibration_target instrument11 GroundStation15)
	(calibration_target instrument11 Star10)
	(calibration_target instrument11 GroundStation3)
	(calibration_target instrument11 GroundStation0)
	(calibration_target instrument11 Star12)
	(calibration_target instrument11 GroundStation5)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star1)
)
(:goal (and
	(pointing satellite0 GroundStation16)
	(pointing satellite2 Planet22)
	(pointing satellite3 Planet21)
	(have_image Phenomenon18 image0)
	(have_image Planet19 image1)
	(have_image Phenomenon20 image0)
	(have_image Planet21 image1)
	(have_image Planet22 image0)
))

)
