(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite6 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite7 - satellite
	instrument17 - instrument
	instrument18 - instrument
	satellite8 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	thermograph1 - mode
	spectrograph0 - mode
	infrared2 - mode
	infrared3 - mode
	Star1 - direction
	GroundStation6 - direction
	Star4 - direction
	GroundStation8 - direction
	Star0 - direction
	GroundStation2 - direction
	Star7 - direction
	GroundStation3 - direction
	Star5 - direction
	Phenomenon9 - direction
	Planet10 - direction
	Planet11 - direction
	Phenomenon12 - direction
	Planet13 - direction
)
(:init
	(supports instrument0 thermograph1)
	(calibration_target instrument0 Star7)
	(calibration_target instrument0 GroundStation8)
	(supports instrument1 infrared3)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 GroundStation2)
	(calibration_target instrument1 Star4)
	(supports instrument2 infrared2)
	(supports instrument2 spectrograph0)
	(supports instrument2 infrared3)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 GroundStation2)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation2)
	(supports instrument3 infrared2)
	(supports instrument3 thermograph1)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 GroundStation8)
	(calibration_target instrument3 GroundStation3)
	(calibration_target instrument3 Star7)
	(supports instrument4 infrared3)
	(supports instrument4 infrared2)
	(calibration_target instrument4 Star5)
	(calibration_target instrument4 GroundStation3)
	(calibration_target instrument4 GroundStation8)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star5)
	(supports instrument5 spectrograph0)
	(calibration_target instrument5 Star4)
	(calibration_target instrument5 Star5)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon9)
	(supports instrument6 infrared3)
	(calibration_target instrument6 Star4)
	(calibration_target instrument6 Star7)
	(supports instrument7 spectrograph0)
	(supports instrument7 infrared3)
	(calibration_target instrument7 Star5)
	(supports instrument8 spectrograph0)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 GroundStation2)
	(calibration_target instrument8 Star5)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet10)
	(supports instrument9 infrared2)
	(calibration_target instrument9 Star7)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 Star5)
	(supports instrument10 infrared2)
	(supports instrument10 infrared3)
	(calibration_target instrument10 Star4)
	(calibration_target instrument10 GroundStation3)
	(calibration_target instrument10 GroundStation6)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet11)
	(supports instrument11 spectrograph0)
	(supports instrument11 infrared3)
	(supports instrument11 thermograph1)
	(calibration_target instrument11 Star0)
	(calibration_target instrument11 Star4)
	(calibration_target instrument11 Star7)
	(supports instrument12 infrared2)
	(calibration_target instrument12 Star7)
	(supports instrument13 spectrograph0)
	(supports instrument13 infrared3)
	(calibration_target instrument13 GroundStation3)
	(calibration_target instrument13 GroundStation8)
	(calibration_target instrument13 Star1)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon9)
	(supports instrument14 infrared3)
	(supports instrument14 spectrograph0)
	(supports instrument14 thermograph1)
	(calibration_target instrument14 Star0)
	(calibration_target instrument14 GroundStation6)
	(supports instrument15 spectrograph0)
	(supports instrument15 infrared2)
	(calibration_target instrument15 GroundStation3)
	(supports instrument16 infrared3)
	(supports instrument16 infrared2)
	(supports instrument16 thermograph1)
	(calibration_target instrument16 GroundStation6)
	(calibration_target instrument16 Star4)
	(on_board instrument14 satellite6)
	(on_board instrument15 satellite6)
	(on_board instrument16 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation6)
	(supports instrument17 thermograph1)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 Star4)
	(calibration_target instrument17 Star0)
	(calibration_target instrument17 Star5)
	(supports instrument18 thermograph1)
	(supports instrument18 spectrograph0)
	(supports instrument18 infrared3)
	(calibration_target instrument18 GroundStation8)
	(calibration_target instrument18 GroundStation2)
	(on_board instrument17 satellite7)
	(on_board instrument18 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Phenomenon12)
	(supports instrument19 infrared3)
	(calibration_target instrument19 GroundStation2)
	(calibration_target instrument19 Star0)
	(supports instrument20 infrared2)
	(supports instrument20 infrared3)
	(supports instrument20 spectrograph0)
	(calibration_target instrument20 GroundStation3)
	(supports instrument21 spectrograph0)
	(supports instrument21 infrared2)
	(supports instrument21 infrared3)
	(calibration_target instrument21 Star5)
	(calibration_target instrument21 GroundStation3)
	(calibration_target instrument21 Star7)
	(on_board instrument19 satellite8)
	(on_board instrument20 satellite8)
	(on_board instrument21 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation2)
)
(:goal (and
	(pointing satellite0 GroundStation3)
	(pointing satellite1 GroundStation6)
	(pointing satellite2 Star5)
	(pointing satellite5 Star5)
	(pointing satellite6 Star7)
	(have_image Phenomenon9 spectrograph0)
	(have_image Planet10 spectrograph0)
	(have_image Planet11 infrared3)
	(have_image Phenomenon12 infrared3)
	(have_image Planet13 thermograph1)
))

)
