(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite4 - satellite
	instrument11 - instrument
	satellite5 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite6 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite7 - satellite
	instrument18 - instrument
	satellite8 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite9 - satellite
	instrument22 - instrument
	satellite10 - satellite
	instrument23 - instrument
	instrument24 - instrument
	satellite11 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	image3 - mode
	spectrograph2 - mode
	infrared6 - mode
	thermograph1 - mode
	thermograph5 - mode
	image0 - mode
	infrared4 - mode
	Star5 - direction
	Star4 - direction
	Star0 - direction
	Star2 - direction
	Star1 - direction
	GroundStation3 - direction
	Phenomenon6 - direction
	Phenomenon7 - direction
	Star8 - direction
	Phenomenon9 - direction
	Star10 - direction
	Phenomenon11 - direction
)
(:init
	(supports instrument0 spectrograph2)
	(supports instrument0 image3)
	(supports instrument0 thermograph5)
	(calibration_target instrument0 Star2)
	(calibration_target instrument0 Star1)
	(supports instrument1 infrared6)
	(supports instrument1 image0)
	(supports instrument1 thermograph5)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 Star5)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation3)
	(supports instrument2 spectrograph2)
	(calibration_target instrument2 Star4)
	(supports instrument3 thermograph5)
	(supports instrument3 infrared6)
	(supports instrument3 spectrograph2)
	(calibration_target instrument3 Star2)
	(supports instrument4 image3)
	(supports instrument4 infrared4)
	(calibration_target instrument4 Star1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star2)
	(supports instrument5 image0)
	(supports instrument5 spectrograph2)
	(calibration_target instrument5 Star4)
	(supports instrument6 thermograph1)
	(supports instrument6 thermograph5)
	(calibration_target instrument6 Star5)
	(calibration_target instrument6 Star4)
	(supports instrument7 image0)
	(supports instrument7 spectrograph2)
	(supports instrument7 infrared6)
	(calibration_target instrument7 Star0)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon7)
	(supports instrument8 image3)
	(supports instrument8 spectrograph2)
	(supports instrument8 thermograph5)
	(calibration_target instrument8 Star0)
	(supports instrument9 infrared4)
	(calibration_target instrument9 GroundStation3)
	(supports instrument10 thermograph5)
	(calibration_target instrument10 Star5)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star4)
	(supports instrument11 thermograph5)
	(supports instrument11 image3)
	(supports instrument11 thermograph1)
	(calibration_target instrument11 Star2)
	(calibration_target instrument11 Star5)
	(on_board instrument11 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star1)
	(supports instrument12 infrared6)
	(supports instrument12 thermograph5)
	(supports instrument12 image3)
	(calibration_target instrument12 Star4)
	(calibration_target instrument12 GroundStation3)
	(supports instrument13 image3)
	(supports instrument13 infrared4)
	(supports instrument13 image0)
	(calibration_target instrument13 Star2)
	(supports instrument14 thermograph5)
	(calibration_target instrument14 Star4)
	(calibration_target instrument14 Star5)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Phenomenon11)
	(supports instrument15 image3)
	(supports instrument15 infrared4)
	(supports instrument15 thermograph5)
	(calibration_target instrument15 GroundStation3)
	(calibration_target instrument15 Star1)
	(supports instrument16 infrared4)
	(supports instrument16 thermograph1)
	(calibration_target instrument16 Star1)
	(calibration_target instrument16 Star2)
	(supports instrument17 image3)
	(calibration_target instrument17 Star0)
	(on_board instrument15 satellite6)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon9)
	(supports instrument18 thermograph1)
	(calibration_target instrument18 Star0)
	(on_board instrument18 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star2)
	(supports instrument19 image3)
	(supports instrument19 image0)
	(calibration_target instrument19 Star5)
	(supports instrument20 thermograph5)
	(supports instrument20 thermograph1)
	(supports instrument20 spectrograph2)
	(calibration_target instrument20 Star0)
	(calibration_target instrument20 Star2)
	(supports instrument21 infrared4)
	(supports instrument21 thermograph1)
	(calibration_target instrument21 GroundStation3)
	(calibration_target instrument21 Star1)
	(on_board instrument19 satellite8)
	(on_board instrument20 satellite8)
	(on_board instrument21 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation3)
	(supports instrument22 thermograph5)
	(supports instrument22 thermograph1)
	(supports instrument22 image0)
	(calibration_target instrument22 GroundStation3)
	(calibration_target instrument22 Star5)
	(on_board instrument22 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon11)
	(supports instrument23 image3)
	(supports instrument23 spectrograph2)
	(calibration_target instrument23 Star1)
	(supports instrument24 thermograph5)
	(calibration_target instrument24 Star4)
	(on_board instrument23 satellite10)
	(on_board instrument24 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Phenomenon9)
	(supports instrument25 image3)
	(supports instrument25 thermograph1)
	(calibration_target instrument25 Star0)
	(calibration_target instrument25 Star4)
	(supports instrument26 image0)
	(supports instrument26 image3)
	(supports instrument26 thermograph1)
	(calibration_target instrument26 Star1)
	(calibration_target instrument26 Star2)
	(supports instrument27 image3)
	(supports instrument27 infrared6)
	(supports instrument27 spectrograph2)
	(calibration_target instrument27 GroundStation3)
	(on_board instrument25 satellite11)
	(on_board instrument26 satellite11)
	(on_board instrument27 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Phenomenon7)
)
(:goal (and
	(pointing satellite0 Star2)
	(pointing satellite4 Star2)
	(pointing satellite6 Star5)
	(pointing satellite7 Star0)
	(pointing satellite9 Phenomenon9)
	(pointing satellite10 Star10)
	(pointing satellite11 Star4)
	(have_image Phenomenon6 image0)
	(have_image Phenomenon7 spectrograph2)
	(have_image Star8 infrared6)
	(have_image Phenomenon9 infrared4)
	(have_image Star10 thermograph5)
	(have_image Phenomenon11 thermograph1)
))

)
