(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	satellite5 - satellite
	instrument10 - instrument
	satellite6 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite7 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite8 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite9 - satellite
	instrument20 - instrument
	instrument21 - instrument
	satellite10 - satellite
	instrument22 - instrument
	satellite11 - satellite
	instrument23 - instrument
	instrument24 - instrument
	spectrograph1 - mode
	image3 - mode
	image0 - mode
	thermograph2 - mode
	GroundStation2 - direction
	GroundStation0 - direction
	GroundStation5 - direction
	GroundStation1 - direction
	GroundStation4 - direction
	GroundStation3 - direction
	Star6 - direction
	Star7 - direction
	Planet8 - direction
	Planet9 - direction
	Phenomenon10 - direction
	Phenomenon11 - direction
	Star12 - direction
	Planet13 - direction
	Planet14 - direction
)
(:init
	(supports instrument0 image3)
	(supports instrument0 spectrograph1)
	(calibration_target instrument0 GroundStation2)
	(calibration_target instrument0 GroundStation5)
	(supports instrument1 image3)
	(calibration_target instrument1 GroundStation4)
	(calibration_target instrument1 GroundStation3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon11)
	(supports instrument2 image0)
	(calibration_target instrument2 GroundStation3)
	(calibration_target instrument2 GroundStation2)
	(supports instrument3 image0)
	(supports instrument3 spectrograph1)
	(supports instrument3 image3)
	(calibration_target instrument3 GroundStation0)
	(calibration_target instrument3 GroundStation5)
	(supports instrument4 image0)
	(supports instrument4 thermograph2)
	(calibration_target instrument4 GroundStation2)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon10)
	(supports instrument5 thermograph2)
	(supports instrument5 spectrograph1)
	(calibration_target instrument5 GroundStation3)
	(calibration_target instrument5 GroundStation4)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation2)
	(supports instrument6 spectrograph1)
	(supports instrument6 image0)
	(calibration_target instrument6 GroundStation0)
	(calibration_target instrument6 GroundStation4)
	(supports instrument7 image3)
	(supports instrument7 spectrograph1)
	(calibration_target instrument7 GroundStation3)
	(calibration_target instrument7 GroundStation0)
	(supports instrument8 thermograph2)
	(supports instrument8 spectrograph1)
	(calibration_target instrument8 GroundStation4)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet8)
	(supports instrument9 image0)
	(supports instrument9 spectrograph1)
	(supports instrument9 image3)
	(calibration_target instrument9 GroundStation2)
	(on_board instrument9 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon10)
	(supports instrument10 image3)
	(supports instrument10 image0)
	(calibration_target instrument10 GroundStation4)
	(on_board instrument10 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation3)
	(supports instrument11 spectrograph1)
	(calibration_target instrument11 GroundStation5)
	(calibration_target instrument11 GroundStation0)
	(supports instrument12 image0)
	(supports instrument12 thermograph2)
	(supports instrument12 spectrograph1)
	(calibration_target instrument12 GroundStation0)
	(calibration_target instrument12 GroundStation3)
	(supports instrument13 thermograph2)
	(supports instrument13 image3)
	(calibration_target instrument13 GroundStation4)
	(calibration_target instrument13 GroundStation5)
	(on_board instrument11 satellite6)
	(on_board instrument12 satellite6)
	(on_board instrument13 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet14)
	(supports instrument14 image0)
	(supports instrument14 image3)
	(calibration_target instrument14 GroundStation0)
	(calibration_target instrument14 GroundStation3)
	(supports instrument15 image0)
	(supports instrument15 image3)
	(supports instrument15 thermograph2)
	(calibration_target instrument15 GroundStation1)
	(calibration_target instrument15 GroundStation0)
	(supports instrument16 thermograph2)
	(supports instrument16 image3)
	(calibration_target instrument16 GroundStation1)
	(calibration_target instrument16 GroundStation5)
	(on_board instrument14 satellite7)
	(on_board instrument15 satellite7)
	(on_board instrument16 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation5)
	(supports instrument17 image3)
	(supports instrument17 image0)
	(calibration_target instrument17 GroundStation2)
	(calibration_target instrument17 GroundStation4)
	(supports instrument18 spectrograph1)
	(supports instrument18 image0)
	(supports instrument18 image3)
	(calibration_target instrument18 GroundStation5)
	(supports instrument19 spectrograph1)
	(supports instrument19 thermograph2)
	(supports instrument19 image0)
	(calibration_target instrument19 GroundStation0)
	(on_board instrument17 satellite8)
	(on_board instrument18 satellite8)
	(on_board instrument19 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation1)
	(supports instrument20 thermograph2)
	(supports instrument20 spectrograph1)
	(supports instrument20 image3)
	(calibration_target instrument20 GroundStation5)
	(supports instrument21 image0)
	(supports instrument21 spectrograph1)
	(calibration_target instrument21 GroundStation4)
	(on_board instrument20 satellite9)
	(on_board instrument21 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Phenomenon10)
	(supports instrument22 spectrograph1)
	(calibration_target instrument22 GroundStation4)
	(on_board instrument22 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Phenomenon11)
	(supports instrument23 image3)
	(supports instrument23 spectrograph1)
	(calibration_target instrument23 GroundStation4)
	(calibration_target instrument23 GroundStation1)
	(supports instrument24 spectrograph1)
	(supports instrument24 image0)
	(supports instrument24 image3)
	(calibration_target instrument24 GroundStation3)
	(on_board instrument23 satellite11)
	(on_board instrument24 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Star12)
)
(:goal (and
	(pointing satellite0 Phenomenon11)
	(pointing satellite2 GroundStation3)
	(pointing satellite3 Planet14)
	(pointing satellite4 GroundStation3)
	(pointing satellite7 Planet14)
	(have_image Star6 image0)
	(have_image Star7 thermograph2)
	(have_image Planet8 spectrograph1)
	(have_image Planet9 image0)
	(have_image Phenomenon10 image3)
	(have_image Phenomenon11 thermograph2)
	(have_image Star12 image0)
	(have_image Planet13 thermograph2)
	(have_image Planet14 image3)
))

)
