(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	satellite5 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite6 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite7 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite8 - satellite
	instrument19 - instrument
	instrument20 - instrument
	satellite9 - satellite
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	spectrograph5 - mode
	spectrograph0 - mode
	infrared3 - mode
	thermograph1 - mode
	infrared6 - mode
	thermograph4 - mode
	image2 - mode
	Star3 - direction
	GroundStation0 - direction
	Star1 - direction
	GroundStation5 - direction
	GroundStation2 - direction
	Star4 - direction
	Star6 - direction
	Phenomenon7 - direction
	Star8 - direction
	Phenomenon9 - direction
	Phenomenon10 - direction
	Star11 - direction
)
(:init
	(supports instrument0 infrared6)
	(supports instrument0 spectrograph5)
	(calibration_target instrument0 GroundStation2)
	(supports instrument1 thermograph4)
	(supports instrument1 infrared3)
	(supports instrument1 thermograph1)
	(calibration_target instrument1 Star4)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation0)
	(supports instrument2 spectrograph0)
	(supports instrument2 infrared3)
	(calibration_target instrument2 Star6)
	(calibration_target instrument2 Star4)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star6)
	(supports instrument3 thermograph1)
	(supports instrument3 infrared6)
	(supports instrument3 thermograph4)
	(calibration_target instrument3 GroundStation2)
	(calibration_target instrument3 Star6)
	(supports instrument4 image2)
	(calibration_target instrument4 GroundStation2)
	(calibration_target instrument4 GroundStation5)
	(supports instrument5 infrared3)
	(calibration_target instrument5 GroundStation2)
	(calibration_target instrument5 Star6)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon9)
	(supports instrument6 thermograph1)
	(supports instrument6 thermograph4)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 Star1)
	(supports instrument7 infrared3)
	(calibration_target instrument7 GroundStation0)
	(calibration_target instrument7 Star6)
	(supports instrument8 spectrograph0)
	(calibration_target instrument8 Star4)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon10)
	(supports instrument9 spectrograph0)
	(supports instrument9 image2)
	(supports instrument9 thermograph1)
	(calibration_target instrument9 GroundStation5)
	(calibration_target instrument9 Star1)
	(on_board instrument9 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Phenomenon7)
	(supports instrument10 image2)
	(supports instrument10 thermograph1)
	(calibration_target instrument10 GroundStation2)
	(calibration_target instrument10 GroundStation5)
	(supports instrument11 spectrograph5)
	(supports instrument11 infrared3)
	(supports instrument11 spectrograph0)
	(calibration_target instrument11 GroundStation2)
	(calibration_target instrument11 GroundStation5)
	(supports instrument12 image2)
	(calibration_target instrument12 Star4)
	(calibration_target instrument12 GroundStation2)
	(on_board instrument10 satellite5)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation0)
	(supports instrument13 spectrograph0)
	(supports instrument13 thermograph1)
	(supports instrument13 infrared3)
	(calibration_target instrument13 GroundStation0)
	(calibration_target instrument13 Star6)
	(supports instrument14 thermograph4)
	(supports instrument14 spectrograph0)
	(calibration_target instrument14 Star3)
	(supports instrument15 spectrograph0)
	(calibration_target instrument15 Star4)
	(calibration_target instrument15 GroundStation2)
	(on_board instrument13 satellite6)
	(on_board instrument14 satellite6)
	(on_board instrument15 satellite6)
	(power_avail satellite6)
	(pointing satellite6 GroundStation0)
	(supports instrument16 infrared3)
	(supports instrument16 thermograph4)
	(supports instrument16 spectrograph5)
	(calibration_target instrument16 GroundStation5)
	(calibration_target instrument16 Star6)
	(supports instrument17 spectrograph5)
	(supports instrument17 infrared3)
	(supports instrument17 infrared6)
	(calibration_target instrument17 Star1)
	(supports instrument18 image2)
	(calibration_target instrument18 GroundStation0)
	(calibration_target instrument18 Star6)
	(on_board instrument16 satellite7)
	(on_board instrument17 satellite7)
	(on_board instrument18 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation0)
	(supports instrument19 thermograph1)
	(calibration_target instrument19 GroundStation0)
	(supports instrument20 spectrograph0)
	(calibration_target instrument20 Star4)
	(calibration_target instrument20 Star1)
	(on_board instrument19 satellite8)
	(on_board instrument20 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star1)
	(supports instrument21 image2)
	(supports instrument21 infrared6)
	(supports instrument21 thermograph4)
	(calibration_target instrument21 GroundStation5)
	(supports instrument22 infrared3)
	(supports instrument22 spectrograph5)
	(calibration_target instrument22 Star4)
	(calibration_target instrument22 GroundStation2)
	(supports instrument23 spectrograph0)
	(calibration_target instrument23 Star6)
	(calibration_target instrument23 Star4)
	(on_board instrument21 satellite9)
	(on_board instrument22 satellite9)
	(on_board instrument23 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation0)
)
(:goal (and
	(pointing satellite0 Star3)
	(pointing satellite3 Star4)
	(pointing satellite6 Star4)
	(pointing satellite7 Phenomenon10)
	(pointing satellite8 Star6)
	(have_image Phenomenon7 thermograph1)
	(have_image Phenomenon7 infrared3)
	(have_image Star8 image2)
	(have_image Phenomenon9 spectrograph5)
	(have_image Phenomenon9 infrared3)
	(have_image Phenomenon10 spectrograph0)
	(have_image Phenomenon10 thermograph4)
	(have_image Star11 spectrograph5)
))

)
