(define (problem depot-4-2-2-6-6-7) (:domain depots)
(:objects
	depot0 depot1 depot2 depot3 - Depot
	distributor0 distributor1 - Distributor
	truck0 truck1 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 - Crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 - Hoist)
(:init
	(at pallet0 depot0)
	(clear crate1)
	(at pallet1 depot1)
	(clear crate4)
	(at pallet2 depot2)
	(clear pallet2)
	(at pallet3 depot3)
	(clear crate6)
	(at pallet4 distributor0)
	(clear pallet4)
	(at pallet5 distributor1)
	(clear crate3)
	(at truck0 depot1)
	(at truck1 depot0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 depot3)
	(available hoist3)
	(at hoist4 distributor0)
	(available hoist4)
	(at hoist5 distributor1)
	(available hoist5)
	(at crate0 distributor1)
	(on crate0 pallet5)
	(at crate1 depot0)
	(on crate1 pallet0)
	(at crate2 depot3)
	(on crate2 pallet3)
	(at crate3 distributor1)
	(on crate3 crate0)
	(at crate4 depot1)
	(on crate4 pallet1)
	(at crate5 depot3)
	(on crate5 crate2)
	(at crate6 depot3)
	(on crate6 crate5)
)

(:goal (and
		(on crate0 pallet5)
		(on crate1 pallet4)
		(on crate2 pallet2)
		(on crate3 crate2)
		(on crate4 pallet1)
		(on crate5 crate3)
	)
))
