(define (problem depot-3-4-2-7-7-9) (:domain depots)
(:objects
	depot0 depot1 depot2 - Depot
	distributor0 distributor1 distributor2 distributor3 - Distributor
	truck0 truck1 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 - Crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 - Hoist)
(:init
	(at pallet0 depot0)
	(clear pallet0)
	(at pallet1 depot1)
	(clear pallet1)
	(at pallet2 depot2)
	(clear crate7)
	(at pallet3 distributor0)
	(clear crate8)
	(at pallet4 distributor1)
	(clear crate6)
	(at pallet5 distributor2)
	(clear crate5)
	(at pallet6 distributor3)
	(clear crate3)
	(at truck0 distributor3)
	(at truck1 distributor0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at hoist5 distributor2)
	(available hoist5)
	(at hoist6 distributor3)
	(available hoist6)
	(at crate0 distributor0)
	(on crate0 pallet3)
	(at crate1 depot2)
	(on crate1 pallet2)
	(at crate2 distributor1)
	(on crate2 pallet4)
	(at crate3 distributor3)
	(on crate3 pallet6)
	(at crate4 distributor2)
	(on crate4 pallet5)
	(at crate5 distributor2)
	(on crate5 crate4)
	(at crate6 distributor1)
	(on crate6 crate2)
	(at crate7 depot2)
	(on crate7 crate1)
	(at crate8 distributor0)
	(on crate8 crate0)
)

(:goal (and
		(on crate0 pallet2)
		(on crate1 pallet6)
		(on crate2 pallet0)
		(on crate3 crate1)
		(on crate4 pallet3)
		(on crate5 pallet4)
		(on crate6 crate4)
		(on crate8 crate5)
	)
))
