(define (problem depot-3-2-4-5-5-9) (:domain depots)
(:objects
	depot0 depot1 depot2 - Depot
	distributor0 distributor1 - Distributor
	truck0 truck1 truck2 truck3 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 crate7 crate8 - Crate
	hoist0 hoist1 hoist2 hoist3 hoist4 - Hoist)
(:init
	(at pallet0 depot0)
	(clear crate8)
	(at pallet1 depot1)
	(clear crate7)
	(at pallet2 depot2)
	(clear crate4)
	(at pallet3 distributor0)
	(clear crate1)
	(at pallet4 distributor1)
	(clear crate5)
	(at truck0 distributor0)
	(at truck1 distributor0)
	(at truck2 distributor0)
	(at truck3 distributor0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 distributor0)
	(available hoist3)
	(at hoist4 distributor1)
	(available hoist4)
	(at crate0 depot2)
	(on crate0 pallet2)
	(at crate1 distributor0)
	(on crate1 pallet3)
	(at crate2 depot1)
	(on crate2 pallet1)
	(at crate3 distributor1)
	(on crate3 pallet4)
	(at crate4 depot2)
	(on crate4 crate0)
	(at crate5 distributor1)
	(on crate5 crate3)
	(at crate6 depot1)
	(on crate6 crate2)
	(at crate7 depot1)
	(on crate7 crate6)
	(at crate8 depot0)
	(on crate8 pallet0)
)

(:goal (and
		(on crate0 pallet3)
		(on crate1 crate7)
		(on crate2 pallet1)
		(on crate3 crate5)
		(on crate4 pallet0)
		(on crate5 crate8)
		(on crate6 pallet2)
		(on crate7 pallet4)
		(on crate8 crate0)
	)
))
