(define (problem depot-7-3-2-10-10-5) (:domain depots)
(:objects
	depot0 depot1 depot2 depot3 depot4 depot5 depot6 - Depot
	distributor0 distributor1 distributor2 - Distributor
	truck0 truck1 - Truck
	pallet0 pallet1 pallet2 pallet3 pallet4 pallet5 pallet6 pallet7 pallet8 pallet9 - Pallet
	crate0 crate1 crate2 crate3 crate4 - Crate
	hoist0 hoist1 hoist2 hoist3 hoist4 hoist5 hoist6 hoist7 hoist8 hoist9 - Hoist)
(:init
	(at pallet0 depot0)
	(clear crate2)
	(at pallet1 depot1)
	(clear pallet1)
	(at pallet2 depot2)
	(clear crate3)
	(at pallet3 depot3)
	(clear pallet3)
	(at pallet4 depot4)
	(clear pallet4)
	(at pallet5 depot5)
	(clear crate4)
	(at pallet6 depot6)
	(clear pallet6)
	(at pallet7 distributor0)
	(clear pallet7)
	(at pallet8 distributor1)
	(clear pallet8)
	(at pallet9 distributor2)
	(clear pallet9)
	(at truck0 depot2)
	(at truck1 distributor2)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 depot2)
	(available hoist2)
	(at hoist3 depot3)
	(available hoist3)
	(at hoist4 depot4)
	(available hoist4)
	(at hoist5 depot5)
	(available hoist5)
	(at hoist6 depot6)
	(available hoist6)
	(at hoist7 distributor0)
	(available hoist7)
	(at hoist8 distributor1)
	(available hoist8)
	(at hoist9 distributor2)
	(available hoist9)
	(at crate0 depot5)
	(on crate0 pallet5)
	(at crate1 depot2)
	(on crate1 pallet2)
	(at crate2 depot0)
	(on crate2 pallet0)
	(at crate3 depot2)
	(on crate3 crate1)
	(at crate4 depot5)
	(on crate4 crate0)
)

(:goal (and
		(on crate0 pallet0)
		(on crate1 pallet9)
		(on crate3 pallet3)
		(on crate4 pallet7)
	)
))
